### ISSUE TITLE
Universal word replace?

### ISSUE THREAD

**Issue by tuomassalo** [talonvoice/talon#10]
I never want to write 'e-mail' or 'plug-in'.  I prefer 'email' and 'plugin'. I'd like those dashless forms to work wherever I say them.

Please consider adding support for a global replacement map. Or maybe something else that would solve this problem.

**Comment by lunixbochs** [comment]
How many places do you use `<dgndictation>`? You can wire up a placeholder version of this pretty easily while you wait for the new apis.

**Comment by lunixbochs** [comment]
New API has captures, as well as a global word map (settings.dictate.word_map)
