### ISSUE TITLE
Discrete GPU triggered

### ISSUE THREAD

**Issue by raubreywhite** [talonvoice/talon#100]
1. I installed Talon
2. I downloaded a language for "built-in speech recognition"
3. Then I checked my graphics card status using https://gfx.io and found that I was using the discrete graphics card for my 2015 15" MBP

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1532091/63216468-a6146b80-c13e-11e9-9f3f-498d04af7e82.png">

4. I restarted Talon and the same issue occurred.
5. I also renamed my `~/.talon/user` directory, restarted Talon, and the same issue occurred.

**Comment by hotsoupisgood** [comment]
I get this too with the 2012 15" pro

**Comment by lunixbochs** [comment]
The Talon overlay, used for drawing on the screen, holds GPU resources even when it's not drawing. I think the solution is going to be to completely destroy the overlay when nothing is registered to draw to it, and be careful about what draws to it.

**Comment by priggins2** [comment]
Is there a temporary fix available for this? Like a way to forcibly destroy the overlay? Since upgrading to Mojave, I seem to get random distracting screen flickers (screen fills with static for a moment) whenever the GPU is engaged, including all the time when talon is running

**Comment by lunixbochs** [comment]
What’s your Mac model? Sounds like a bad GPU.

This should remove all the overlays until you change screen layout:

from talon import canvas
canvas.overlay.screen_update([])

From there you could maybe say:

canvas.overlay.screen_update = lambda screens: None

This doesn’t help with individual canvas creation, you’ll need to make sure none of the scripts you use create a Canvas. You might need to edit scripts in talon_plugins and your user directory to remove canvas use.

**Comment by priggins2** [comment]
Great, thank you! Yeah, it might be, although it only started happening after Mojave, and I've found other people online complaining about the same issue also only since Mojave. I'm crossing my fingers it will go away with Catalina.

Is there a way to check which canvases currently exist? It's looking like I'll have to fairly dissect the eye mouse plugins, though it looks like some of those canvases only get created when I run calibration or some such.

![image](https://user-images.githubusercontent.com/20117014/66227921-0c276480-e693-11e9-8a7f-80f5c04fba83.png)

**Comment by lunixbochs** [comment]
Looks like eye_zoom_mouse only creates a canvas on demand, eye_mouse.py should be the only place besides the overlay that has canvases.

If you're not using eye tracking at all, it _might_ work to just delete (rename) canvas.pyc, not sure what all that will break for you - just restart talon and check the talon log.

**Comment by lunixbochs** [comment]
This should be completely fixed as of the next private beta release.
