### ISSUE TITLE
Any advice for bluetooth microphone?

### ISSUE THREAD

**Issue by Madd0g** [talonvoice/talon#104]
I have a weird behavior where the built-in microphone always works, but when I switch to the bluetooth microphone in my headset it only works if Talon is not running (I'm looking at the bar movement in the sound input panel, with talon running the bars aren't moving).

Anything I can check or try?

**Comment by lunixbochs** [comment]
Does the microphone work with macos enhanced dictation?

**Comment by Madd0g** [comment]
Sorry, apparently it's just really really bad, if I bring it really close to my mouth talon does pick up some sounds.
