### ISSUE TITLE
Can contexts override commands in each other?

### ISSUE THREAD

**Issue by erapoport** [talonvoice/talon#105]
If I have an unrestricted context (`std.py`) and a context for my editor (`vscode.py`), how can I override a command from my narrower context? Is it possible to easily do that?

I'm really new to talon, my files look like this:

std.py: `ctx = Context('input')`
vscode.py: `ctx = Context("VSCode", bundle="com.microsoft.VSCode")`

And I want to put the same command word in both, but have vscode override the default when it's active.

Thanks

**Comment by lunixbochs** [comment]
This is possible in the newapi version of talon which is still in private beta.

**Comment by lunixbochs** [comment]
In the interim, there are two ways to do this:

1. Make a context that is explicitly "not VSCode":

```
ctx = Context("not_vscode", lambda app, win: app.bundle != "com.microsoft.VSCode")
```

2. Map a single global command, but make it do something different when you're in VSCode:

```
from talon import ui

def func(m):
    if ui.active_app().bundle == "com.microsoft.VSCode":
        pass
    else:
        pass

ctx.keymap({
    'global command': func,
})
```

**Comment by erapoport** [comment]
Very good, thank you!
