### ISSUE TITLE
Toggling of speech features?

### ISSUE THREAD

**Issue by Madd0g** [talonvoice/talon#106]
I know it is possible to completely disable talon listening by picking "None" from the microphone menu. 

I'm wondering if it would be possible to disable speech completely but keep the noises feature? Right now I noticed that when I disable speech from the menu (or from the code), it is still listening to commands (for the wake up command I guess?) and if I pick the "None" microphone noises don't work.

I want to use some features at work (noises, maybe eye tracking) and speech at home. I have a pretty old laptop so I prefer speech to be "completely" disabled at work.

Is this possible somehow?

Thanks

**Comment by landonwilkins** [comment]
**EDIT: I misinterpreted the question as**
> **Can Talon still execute noise commands while speech is off?**

I've moved my answer (a long-winded "Yes!") to [my Talon scratchpad wiki here](https://github.com/landonwilkins/docs/wiki/Talon%3A-Do-noise-commands-work-while-speech-is-off%3F).

**Comment by Madd0g** [comment]
Hey, thanks for your reply. 

I am using parts of [dwiel/talon_community](https://github.com/dwiel/talon_community). I did see the code in `speech_toggle.py`. But my question is not how to temporarily mute speech to makes some noises. It is how to disable speech completely for a major part of the day.

Right now even when "sleeping" talon still listens to the mic, I was hoping I could completely disable the speech part while at work but still keep the noises feature.

**Comment by lunixbochs** [comment]
With the builtin engine, you can run this from the repl to kill the engine until the next mic switch:

```
from talon import speechd
speechd.kill()
```

**Comment by landonwilkins** [comment]
~EDIT: Removed for clarity (I misunderstood the issue)~

**Comment by lunixbochs** [comment]
@landonwilkins I think you're missing the main point:

> I have a pretty old laptop so I prefer speech to be "completely" disabled at work.

I believe this is a performance thing.

**Comment by landonwilkins** [comment]
ooooo 👍

**Comment by Madd0g** [comment]
@lunixbochs - thanks, it works.

I still see very active CPU usage (steady at 10+%) from the talon process and my laptop getting warm. 

I was hoping that without the speech part it'll drop significantly.

**Comment by lunixbochs** [comment]
The speech part isn't even in the Talon process. What sort of features are you using? Do you have eye tracking active?

What are your laptop specifications?

**Comment by Madd0g** [comment]
Specs are: Late 2013 MBP with 2.3 GHz Intel Core i7 with 16 GB 1600 MHz DDR3

What I was doing is turning off eye tracking after talon starts, but I see that when I start talon without the eye-tracking python file, it does not ever reach 10% CPU. 

I think I know what was causing it - the canvas drawing from [lens_mouse.py](https://github.com/dwiel/talon_community/blob/78fec4871ce65045db0826338a9985137fceede4/misc/lens_mouse.py). It keeps drawing it even when eye tracking is disabled.

**Comment by lunixbochs** [comment]
Oh, yeah, that's not optimal... it's also just always enabled by default?

**Comment by Madd0g** [comment]
Yeah, it's enabled by default (it errors out if the eye-tracker is not connected).

Would be really nice if my toggle that turns eye tracking off could also somehow disable the canvas drawing, I couldn't find any docs on how to use the canvas api.

This is how it starts:

```py
canvas.register('overlay', self.draw)
```

Would calling `unregister` work? I don't fully understand how drawing is actually triggered, is it just on an interval?

**Comment by lunixbochs** [comment]
I mean, lens mouse definitely shouldn't be enabled by default. Do you use it?

**Comment by Madd0g** [comment]
I only got the eye tracker last week (and only because talon supports it), I don't know yet which features I want to keep using.

So far, I do prefer the lens mouse over all the other eye tracking features (like moving the cursor directly), it's like a second "targeting" cursor. I have a keyword to make the circle bigger/smaller and to click wherever it's pointing. I'm in the process of connecting the noises feature so I can click with the circle by hissing.

I think the thing that would help me most is having more control over the drawing - I was thinking of experimenting with features like:

1. turning the circle on/off completely (stop drawing the canvas, but keep all the rest of the lens mouse features, like keeping a history of the last XX gaze locations)
2. drawing it only when it hangs around the same area for a while (I asked [here](https://github.com/dwiel/talon_community/issues/185) what the DwellFilter is and how to use it).

**Comment by lunixbochs** [comment]
Try just `return False` instead of `return` in the lens mouse draw callback.

**Comment by lunixbochs** [comment]
There's no api for "gaze sticks around a while" yet.

**Comment by lunixbochs** [comment]
unregister with the same arguments should remove the draw callback. draw is called for every frame that is drawn on vsync

**Comment by Madd0g** [comment]
perfect, `unregister` does the trick, CPU just drops to nothing, thank you very much!l
