### ISSUE TITLE
no warning if repeated declaration in .talon files

### ISSUE THREAD

**Issue by towc** [talonvoice/talon#112]
In the same `vim.talon`, you can have:

```
delete line:
  key(escape d d)
delete line:
  key(d d)
```

and the second will overwrite the first without warning. Would be nice to have a warning, as this is probably a mistake, and can take a while to debug.

**Comment by lunixbochs** [comment]
Hi, you should report beta bugs on talonvoice/beta, sorry for the confusion. Either way, this will be done in next release, thanks for the suggestion.

**Comment by lunixbochs** [comment]
fixed in 1328
