### ISSUE TITLE
Repl throwing "Python.exe is not recognized" error

### ISSUE THREAD

**Issue by tararoys** [talonvoice/talon#113]
in Windows 10, when clicking on the talon icon in the lower right-hand section of the screen, and going to scripting > console (repl) and clicking on it to open it,
![image](https://user-images.githubusercontent.com/1163925/84294871-6c6a8200-ab0f-11ea-812e-cd2dd8133cd5.png)

 the following error message occurs:

'""\python.exe' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

![Console REPL error message](https://user-images.githubusercontent.com/1163925/84294779-47760f00-ab0f-11ea-8b92-88efd678d5a5.png)

**Comment by lunixbochs** [comment]
This is caused by having a space in your username. It will be fixed in the next beta.
