### ISSUE TITLE
Feature request: change color of Talon icon based on current mode

### ISSUE THREAD

**Issue by MartijnB** [talonvoice/talon#115]
It would be convenient if the color of the Talon icon (at least the Windows taskbar would support this I think?) was based on the mode it is currently in: for example green for command mode, red for dictate mode, grey for sleep, etc.

**Comment by lunixbochs** [comment]
This is done and landing in the next beta and v0.1.5.

I need to clean up the tray icons on Windows and Linux to look better for this, but that will be a separate task.

**Comment by vHanda** [comment]
I'm on osx 10.14 and Talon 0.1.5, and this is showing "red" when speech recognition is off (via 'talon sleep' or manually switching it off) and green when on. It doesn't show the difference between modes. Is this intended?

Additionally, the color difference is very subtle, as only a small part of the icon changes the color. I would love for it to be more apparent. Please let me know if I should open another issue.

**Comment by mankoff** [comment]
Agreed. I suggest all red, all green, and maybe all blue for 'dictation mode'? But there are other modes too (presentation, etc.) so just sleep v. not-sleep makes sense. Also, note that ~10 % of the population cannot distinguish red vs. green, so an app that focuses on accessibility should probably take this into account.
