### ISSUE TITLE
Protection against OOM from making gigantic word lists

### ISSUE THREAD

**Issue by jgarvin** [talonvoice/talon#117]
I accidentally assigned an enormous list (182177 entries!), which promptly caused Talon to get killed by the OOM killer. Some sort of protection against doing this so users don't lose recognition by accident would be helpful. Easy way would be a configurable limit that defaults to something high but runnable on most machines, fancy could be making it a function of detected system RAM.

**Comment by lunixbochs** [comment]
I think I can cap the max ram used by the ram heavy part of this process

**Comment by lunixbochs** [comment]
Fixed in beta 0.2.0-184, now you can make lists with millions of items in them and not run out of ram.
