### ISSUE TITLE
"failed to parse phrase", decoding detecting nonsense word "wordss"

### ISSUE THREAD

**Issue by jgarvin** [talonvoice/talon#122]
I'm getting this error sometimes: `talon.engines.EngineError: failed to parse phrase: ['buff', 'shell', 'key', 'wordss']` . First the error is confusing since it seems to have parsed it by giving the list :slightly_smiling_face: I have grammars setup so "buff" must be followed by an entry in a word list, and "key" must be followed by an entry in a word list. In this case I am saying "buff shell keywords" and I expect it to be parsed as one buff command. But the error makes me think Talon believes I'm saying "buff shell" followed by "key wordss" which would be a "buff" command followed by a "key" command. I could understand Talon erroring and complaining the match was ambiguous if "shell key wordss" was in the buff list and "wordss" was in the key list, but neither of those is present AFAICT. 

Upon examining talon file realized '$' should have made matching "key" impossible anyway:

`buff <user.buffer_name>$: user.switch_buffer(buffer_name)`

Buffer names was this dictionary:

```
{
    "keywords": [
        "shell_keywords.json"
    ],
    "shell keywords json": [
        "shell_keywords.json"
    ],
    "shell keywords": [
        "shell_keywords.json"
    ],
    "json": [
        "shell_keywords.json"
    ],
    "shell json": [
        "shell_keywords.json"
    ],
    "shell": [
        "shell_keywords.json"
    ],
    "keywords json": [
        "shell_keywords.json"
    ]
}
```

`@aegis` had me dump `speech_system.engine.engine.cfg_blobs['talon_main']` and found this:

```
match('_b', 'uff', '#', '_shell', '_key', 'word', 's')
True
```

"the dfa looks correct, so it's probably a wav2letter decoder bug with sconv "

This was running `v0.1.2-55-g3016bf9` w/ sconvb6 model on Linux.

**Comment by lunixbochs** [comment]
I'm pretty sure this is fixed / obsoleted by Conformer, please reopen if it's not.
