### ISSUE TITLE
iTerm2 hotkey windows with ctrl in hotkey do not work

### ISSUE THREAD

**Issue by EdJoJob** [talonvoice/talon#123]
The discussion on the slack started [here](https://talonvoice.slack.com/archives/C7ENXA7C4/p1603859885014900)

## Reproduction

Using iTerm2 set up a profile to be opened by a dedicated hotkey including `ctrl`

* Preferences → Profiles → {profile name} → Keys → "A hotkey opens a dedicated window with this profile"
* Configure the hotkey (for me either `ctrl-cmd-enter` or `ctrl-alt-cmd-enter`)

Set up a talon command to send the chosen key
Talon sends the key
iTerm2 does not open the dedicated hotkey window

## Anti-reproduction
Change the hotkey to not include `ctrl`
change the talon command
See that iTerm2 now does open the dedicated window

**Comment by EdJoJob** [comment]
further checking seems to imply that it is only the `ctrl-enter` being swallowed somewhere, as a `cmd-ctrl-z` or `cmd-alt-ctrl-z`set as the hotkey does work

**Comment by lunixbochs** [comment]
From #41, ctrl-space is also broken.

**Comment by lunixbochs** [comment]
fixed in next beta
