### ISSUE TITLE
Feature request: command hotword

### ISSUE THREAD

**Issue by lslunis** [talonvoice/talon#130]
I'd love to be able to define a hotword that let me execute something defined in command mode even if I was in dictation or sleep mode, e.g. something equivalent to:

```
mode: all
-
simon says <command>+: execute(command_list)
```

**Comment by lunixbochs** [comment]
I implemented a variant of this today in #help, it can only work in wav2letter though

**Comment by lslunis** [comment]
Is this documented anywhere else? #help only supports scrollback to January 9.

**Comment by lunixbochs** [comment]
Search files in #help for "momentary"
