### ISSUE TITLE
Windows - Add setting for switching between keyboard input modes?

### ISSUE THREAD

**Issue by mirober** [talonvoice/talon#133]
Playing with the key_hold and key_wait seems to have fixed the issue I was having with TIS-100, but if other games/apps are more stubborn then might it be worth adding a `use_keybd_event` setting or similar? Will update this issue if I come across any.

**Comment by lunixbochs** [comment]
Going to close this as nothing else has come up. I do note that there are a couple of other issues open for mouse input to DirectX games that still need deeper investigation.
