### ISSUE TITLE
Only enable talon if one of a set of microphones is available

### ISSUE THREAD

**Issue by nriley** [talonvoice/talon#134]
I have some higher quality microphones that I move between computers.  Right now, if I unplug one of these microphones, Talon continues to listen but using the internal microphone or something else unwanted.   This results in unexpected input when I am dictating to a different computer in earshot of the internal microphone.

I would prefer in this case that Talon disable itself if it cannot find a good-quality/preferred microphone to use.   When a preferred microphone is subsequently plugged in, Talon could (optionally) re-enable itself, but should switch to that microphone regardless.

I implemented a basic version of this [here](https://github.com/nriley/knausj_talon/blob/nriley/misc/microphone.py).

**Comment by lunixbochs** [comment]
Supported in beta `v0.1.5-367` - your microphone preferences are now saved across runs of Talon. So if you select None, then each of your chosen microphone(s) in order of lowest to highest priority, Talon will automatically pick the right microphones for you in the future.
