### ISSUE TITLE
Add negative anchors/anchor negation

### ISSUE THREAD

**Issue by brxck** [talonvoice/talon#137]
It would be useful to specify whether commands _shouldn't_ begin or end a group.

If I had a repeat command:

```
<number>: core.repeat_command(number-1)
```

I would like the command to only activate after another command.

"dot five" - `.....`
"five" or "five dot" - should not trigger

**Comment by lunixbochs** [comment]
I'm not going to do this anytime soon due to the grammar complexity, closing.
