### ISSUE TITLE
[repl] Actions tab completion should work

### ISSUE THREAD

**Issue by hunner** [talonvoice/talon#143]
What happens:
Opening the repl and typing `talon.actions.<tab>` only tab-completes `talon.actions.registry`.

What should happen:
All of the actions should be listed, such as `talon.actions.key` and `talon.actions.insert`

Motivation:
Actions are the building-blocks of talon files, and discovery is important to adoption.

**Comment by lunixbochs** [comment]
fixed in beta v0.1.5-433
