### ISSUE TITLE
ui.windows() is not Z ordered on Windows

### ISSUE THREAD

**Issue by jamesmugford** [talonvoice/talon#147]
`windows = ui.windows()` seems broken

Properties attached to window object are not correct.

e.g: `window.height `and `window.y ` for specific windows all return the same result

Hope this help

OS: Windows 10

**Comment by lunixbochs** [comment]
https://stackoverflow.com/q/295996

> Previous answers need considerable refinement. Enum-order = Z-order only if GetSystemMetrics(SM_IMMENABLED)=0, i.e. Input Method Manager/Input Method Editor features are disabled. Because all windows class "IME" (the title "Default IME") and "MSCTFIME UI" are enumerated after the window "Progman" ("Program Manager"), - i.e. not in Z-order.

**Comment by lunixbochs** [comment]
Fixed in 0.1.5-452
