### ISSUE TITLE
talon __init__.pyi is missing actions object

### ISSUE THREAD

**Issue by crypdick** [talonvoice/talon#148]
I have PyCharm pointed to the talon venv, and it finds the packages. However, a few objects such as `actions` and `settings` are not found. According to my chat with aegis on slack, these should be in `talonroot/resources/python/lib/python3.8/site-packages/talon/__init__.pyi`but they are not:

![image](https://user-images.githubusercontent.com/5415776/98276082-39b89e80-1f74-11eb-8228-aead9eb4ea9b.png)

**Comment by lunixbochs** [comment]
should be fixed in next beta
