### ISSUE TITLE
ui.active_window().children returns empty list always

### ISSUE THREAD

**Issue by geeogi** [talonvoice/talon#151]
Running `ui.active_window().children` in a python script or in the talon repl returns an empty list `[]`. This prevents implementing the 'show numbers' feature.

os: catalina 
talon: 1.2-102

**Comment by lunixbochs** [comment]
do you have any more information? what application is focused when this happens? can you try a known good application like TextEdit or Safari?

**Comment by knausj85** [comment]
FYI I was exploring this.

On 11.1 with either Safari and TextEdit focused, I get an empty list too. Talon has accessibility and automation permissions for both.

**Comment by lunixbochs** [comment]
this is fixed in v0.1.5 / beta v0.1.4-189
