### ISSUE TITLE
[Windows] visible rects provided by ui.screens() aren't updated when reserved space changes

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#156]
The easiest repro:
1. Start menu on bottom of main monitor
2. Start Talon 
3. repl =>  print(str(ui.screens()[0].visible_rect))
4. Move the start menu to the left, right, or top of the screen
5. repl =>  print(str(ui.screens()[0].visible_rect)). Note the visible_rect is the same as in step 3.

Pretty minor thing I noticed when Optikey is started after Talon, causes issues with window snapping etc.

**Comment by lunixbochs** [comment]
Hrm. Not completely sure what to do about this.

**Comment by lunixbochs** [comment]
Does windows post some kind of notification when the reserved space changes?

**Comment by knausj85** [comment]
I think the only events that are fired are for registered app bars, which might be workable
https://docs.microsoft.com/en-us/windows/win32/shell/abn-poschanged

**Comment by lunixbochs** [comment]
I don't have an app bar, I think I can watch for window rect changes of the Shell_TrayWnd class?

**Comment by lunixbochs** [comment]
this is done in beta 0.2.0-85, please test and report any issues to the beta channel or on #382
