### ISSUE TITLE
Linux package repositories

### ISSUE THREAD

**Issue by lunixbochs** [talonvoice/talon#159]
Can likely provide the same kinds of repositories as Sublime: https://www.sublimetext.com/docs/3/linux_repositories.html

**Comment by lunixbochs** [comment]
Options for nix include nix flakes (experimental) and nix channels (soon to be replaced by flakes?)

https://github.com/nix-community/home-manager#installation

https://nixos.wiki/wiki/Flakes

**Comment by xsuchy** [comment]
I am willing to help with an RPM packaging for Fedora. But I need an upstream co-operation. E.g. provide space where to store the repository etc.

**Comment by lunixbochs** [comment]
closing this until linux wayland future seems more certain

**Comment by xsuchy** [comment]
??? How is Wayland relevant to packaging?

And the future has nothing but Wayland. There is no alternative. X11 is merely in maintenance mode. And Compiz, Mir and XQuartz never lift off.

**Comment by auscompgeek** [comment]
Ryan has reiterated this a number of times in the #talon-linux Slack channel already, but I'll state the main point again here:

If the state of accessibility on Wayland continues to move nowhere like it has for the past 15 years, and the major distros drop support for X11 out of the box (which seems imminent), then Talon will drop support for Linux.
