### ISSUE TITLE
Impossible to create Talon commands which also are Dragon vocab 'commands'

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#161]
This is a copy of https://github.com/talonvoice/beta/issues/34, which appears still to be an issue. It turned out to be part of the root cause of https://github.com/knausj85/knausj_talon/issues/284, preventing punctuation from working correctly in dictation mode with Dragon. I have copied the original text of https://github.com/talonvoice/beta/issues/34 below for reference:

> From the discussion in `beta` in Slack:
> 
> if I try to define a command `left bracket: "("` it doesn't work,
> 
> This is because to Dragon 'left bracket' is the phrase for '('
> 
> In a capture this appears as `(\left-parenthesis\left bracket`.
> 
> It doesn't seem to be possible to do this in a talon command, e.g. `\(: ` or `\left-parenthesis: `
> 
> Work around for now is:
> 
>     * You can delete "left bracket" from your dragon vocab
> 
>     * You can make a list from python that is ‘(‘: ‘(‘

**Comment by lunixbochs** [comment]
I just ported the other issue #162 to this repo, comment on it if you like
