### ISSUE TITLE
Impossible to create Talon commands which also are Dragon vocab 'commands'

### ISSUE THREAD

**Issue by stevegeek** [talonvoice/talon#162]
From the discussion in `beta` in Slack:

if I try to define a command `left bracket: "("` it doesn't work, 

This is because to Dragon 'left bracket' is the phrase for '(' 

In a capture this appears as `(\left-parenthesis\left bracket`. 

It doesn't seem to be possible to do this in a talon command, e.g. `\(: ` or `\left-parenthesis: ` 

Work around for now is:
* You can delete "left bracket" from your dragon vocab 
* You can make a list from python that is ‘(‘: ‘(‘

**Comment by lunixbochs** [comment]
I'm going to leave this open but provisionally mark it as wontfix for now. Basically the only obvious solution I know is to remove the words from the dragon vocab, which is kind of destructive.

**Comment by lunixbochs** [comment]
@knausj85 can you give your opinion on this?

**Comment by knausj85** [comment]
This wasn't something I was looking to do, but it looks we can do it now.

I believe we had some ability to do this before the recent Dragon parsing change, FWIW.

It seems that some things must be overridden using the hyphenated nonsense
```
new-paragraph: "test"
left-bracket: "test"
mouse-grid: "test"
left-brace: "test"
```

and with the Dragon parsing change, it looks like we can override things like `comma` now too

**Comment by lunixbochs** [comment]
Closing, then, as you should be able to use the `left-parenthesis` form in .talon (as requested in the original post)
