### ISSUE TITLE
Talon presses Ctrl-Alt instead of AltGr

### ISSUE THREAD

**Issue by gimpf** [talonvoice/talon#164]
I have a curious case of "insert uses wrong keys?":

* I am on Windows,
* using AltGr-DeadKeys US Intl Keyboard layout,
* inserting the phrase "Mit freundlichen Grüßen" (the ü and the ß need AltGr-y and AltGr-s respectively),
* and when doing this in Notepad or Code it works as intended,
* but in MS Outlook it ... does... something else (split the editor window horizontally),
* but I can type the phrase in Outlook without any issues.

After some trial and error I discovered that I can manually trigger similar behavior by pressing Ctrl-Alt instead of AltGr. Now, this is something: Ctrl-Alt is usually mapped to AltGr in Windows, many people think it is the same, and often is interpreted the same, but... it isn't. AFAIK AltGr really is RightAlt.

And it seems, Outlook is one of the few programs with shortcuts that depend on the difference. Also, this might show up in other places as well.

**Comment by gimpf** [comment]
For the benefit of others finding this: a workaround is to set the text to clipboard, and paste it.

**Comment by lunixbochs** [comment]
This is fixed in both my own tests and at least one user's tests in the latest beta. Please let me know if you run into additional issues.
