### ISSUE TITLE
Consider stripping dragon junk before parsing commands

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#165]
Dragon provides inconsistent results with a capture like the below, designed to allow punctuation via the 'say' command

```
@mod.capture(rule="({user.vocabulary} | {user.punctuation} | <phrase>)+")
def prose(m) -> str: return format_phrase(m)
```

This occurs whether or not e.g. "," and "." are in the _user.punctuation_ list.

(from [https://github.com/rntz/knausj_talon/blob/d746b7b2a7b2a88025a710113c1b789a16f00a11/code/vocabulary.py#L20](here) 

e.g., the below works as expected
`say this is a test comma so far it is working period` -> `this is a test, so far it is working.` where the punctuation is correctly captured.

on the other hand, the below is caught as a single `<phrase>` with the requisite dragon junk parsed by `actions.dictate.parse_words()`
`say so far comma it is working well period` -> `so far comma it is working well period`

It seems we have two potential options:
(1) a variant of _actions.dictate.parse_words_ with the old behavior (returning the symbol) that we can use as required; or
(2) Talon could potentially strip dragon junk before parsing commands

Option 2 seems like a potentially better solution.

**Comment by rntz** [comment]
has this been resolved? I assume it has based on discussion in slack, but I can't verify since I don't have dragon.

**Comment by lunixbochs** [comment]
@knausj85 please confirm if I should do anything more on this

**Comment by knausj85** [comment]
I think the only thing that's worth a quick look-see is backslash since we're not getting the alt.

`IO m = backslash, type = backslash, alt =`

... but that might be an exception too far. It comes in as below just to be difficult:
`\backslash\backslash`

Other than that, I believe this is working very well. I haven't encountered any other weirdness yet.
