### ISSUE TITLE
Show Camera window blank or canvas corruption after disabling debug overlay

### ISSUE THREAD

**Issue by beret** [talonvoice/talon#173]
To reproduce camera blanking:
Enable Show Camera
Enable Debug Overlay
Disable Debug Overlay
Camera overlay now white, no other noted changes in functionality of app. (eyetracking continues to work)

This issue does not occur when debug overlay is enabled first, then camera enabled, then debug overlay disabled. 

To reproduce canvas artifacts:
Enable help context
Enable Debug Overlay
Disable Debug Overlay
Help overlay now as pictured, no other noted changes in functionality of app. (eyetracking continues to work, this corruption remains even as help dynamically updates)

This issue does not occur when debug overlay is enabled first, then help enabled, then debug overlay disabled. 

Reproduced on:
Talon Beta v0.1.2-146-g6d47
Tobii 4c
macOS 11.0.1
MacMini M1 16GB
knausj_talon with lightweight modifications

![Screen Shot 2020-12-11 at 14 44 38](https://user-images.githubusercontent.com/69595/101958233-30989e00-3bc0-11eb-8a63-1d8fe5355cd8.png)

**Comment by lunixbochs** [comment]
This should be fixed in latest beta. Please reopen if I'm wrong.

**Comment by beret** [comment]
Yup, resolved! Thank you!
