### ISSUE TITLE
Unexpected(?) result with commandset

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#174]
With this set of commands defined in a .talon file:

```
<digits>: key("{digits}")
clear line: "something"
clear line <number>: "something else"
```

And this numbers implementation
https://github.com/knausj85/knausj_talon/blob/master/code/numbers.py

the command `clear line 2` will output `something2` -- rather than the anticipated `something else`

With just these commands below, each works fine.

```
clear line: "something"
clear line <number>: "something else"
```

**Comment by lunixbochs** [comment]
Does this repro for you on the latest beta?

**Comment by knausj85** [comment]
This does NOT repro on the latest beta. 🎉
