### ISSUE TITLE
Linux: lack of disk space on update corrupts install

### ISSUE THREAD

**Issue by jgarvin** [talonvoice/talon#175]
when upgrading, I got an OSError b/c I ran out of disk space, and now my talon install appears corrupt:

```
~$ ~/talon-beta/run.sh
Bus error (core dumped)
```

I suggested extracting to a separate directory before moving in place but that would require twice as much disk space. aegis suggested a disk space check (to be really pedantic such a check is racey -- something can fill up disk after the check) or possibly using apt for updates.

talon isn't super hard to reinstall, but this may require users to use their hands when they otherwise may have avoided it.

**Comment by lunixbochs** [comment]
To be equally as pedantic, my vastly preferred solution would be to use apt and other package managers. My fallback solution for distros with no package manager support would be to check for a pretty large buffer of disk space. I am perfectly aware it's a race condition, it's just less work to do that for what would be the now less used updater if I'm already going for full package manager support. I don't disagree that pivoting a directory is more robust, it's just also more work and requires different considerations I'd rather put off if I'm doing a much better solution anyway.

**Comment by lunixbochs** [comment]
This is mitigated in the latest beta, which will warn you gently on the Install Update dialog if you have less than 10x as much disk space as the Talon app takes up.

**Comment by lunixbochs** [comment]
As this is mitigated, I'm closing in favor of https://github.com/talonvoice/talon/issues/159
