### ISSUE TITLE
[Feature Request] Action that provides the active engine

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#178]
There's a few places where an action or another mechanism to get the active engine (wav2letter, dragon, etc) would be potentially useful to better support multiple engines in user scripts.

e.g.,https://github.com/knausj85/knausj_talon/issues/300
The "welcome back" command is intended to do a few things, including moving into the "Talon mode" equivalent. The "correct" behavior varies with the engine. 

```
    def talon_mode():
        """For windows and Mac, enables Talon commands and enables command mode or equivalent."""

        actions.speech.enable()
        if app.platform == "mac":
            actions.user.engine_sleep()
        elif app.platform == "windows":
            actions.user.engine_wake()

            # note: this may not do anything for all versions of Dragon. Requires Pro.
            actions.user.engine_mimic("switch to command mode")
```

**Comment by lunixbochs** [comment]
Two ways today:

speech_system.engine.name
scope.get("speech.engine")

**Comment by knausj85** [comment]
Thanks -`scope.get("speech.engine")` returns `None` on v0.1.2-159 FWIW, but `speech_system.engine.name` works well for this.

**Comment by lunixbochs** [comment]
I don't think we need a dedicated action for this yet.
