### ISSUE TITLE
Type Signature Requests

### ISSUE THREAD

**Issue by lunixbochs** [talonvoice/talon#182]
Please comment below to request improvements to the Talon `.pyi` type stub files. These files are autogenerated, so to improve them I need to improve the type signatures of the underlying Python files. Comment to request an annotation, and I'll reply once it's been pushed to beta.

**Comment by fmagin** [comment]
Requesting Annotations for  `EyeFrame` and `GazeFrame`. I know they aren't considered quite stable, but if the annotations change this would make it easier to quickly find any issues because the underlying types changed.

**Comment by lunixbochs** [comment]
EyeFrame and GazeFrame annotations, as well as the point/rect types should ship in v0.1.5

**Comment by lunixbochs** [comment]
Closing this issue as nobody's using it to request annotations.
