### ISSUE TITLE
Hotkey support for Windows

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#184]
I recently invested in some footpedals, and am interested in doing things via Talon's hotkey support someday. Figured I'd submit this after following the Linux discussion :-)

I'm exploring context-specific functionally based on the active app, mapped to unpossible key combos.
```key(ctrl-super-shift-f12-;): user.do_something()```

For my use case, global non-passive hotkey support would probably suffice. 

Separate on press & on release functionality would be handy for certain things: e.g. starting & stopping scrolling via a single pedal.

**Comment by lunixbochs** [comment]
To be clear you want the ability to press f12-semicolon? That's a pretty advanced hotkey

**Comment by knausj85** [comment]
Nah, just a bad example. Some combo of f-keys and modifiers for this.

`key(ctrl-super-shift-f12)`

**Comment by lunixbochs** [comment]
Done in beta 0.2.0-143
