### ISSUE TITLE
Opening an imgui on v183 may prevent continuous scroll

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#187]
Minimal repro scripts:
[bug.zip](https://github.com/talonvoice/talon/files/5737074/bug.zip)

**Details:**
 I've a little imgui that may be displayed to indicate continuous scrolling is underway. With the latest imgui enhancements, this seems to sometimes prevent the continuous scrolling functionality from working for reasons.

Steps:
- "Wheel Start"
- "Wheel Stop"
- "Wheel Start"

After the second "Wheel Start," it won't continuously scroll. Only the first command works as expected.

Removing the `gui.show()` call from line 47 seems to reliably "fix" this issue(?). 

FWIW, I've only tried this on Windows. This issue does not occur on v175, from what I can tell.

**Comment by lunixbochs** [comment]
Is it possible the imgui is being focused

**Comment by knausj85** [comment]
I don't believe it has focus. In theory, it probably shouldn't matter since scroll follows the cursor on Windows.

If I move the imgui a bit, the scroll starts working though.
