### ISSUE TITLE
imgui increases in size under certain circumstances

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#189]
Using these files:
https://github.com/talonvoice/talon/files/5737074/bug.zip

Issuing "wheel start" and "wheel stop" repeatedly seems to result in a non-visible vertical size increase each time -- as judged by dragging the imgui from below where it appears.

* Windows 10 v2004
* Talon v183

**Comment by lunixbochs** [comment]
I believe this duplicates #187
