### ISSUE TITLE
imgui weirdness on Ubuntu: small text, white flashes

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#190]
In vanilla knausj on Ubuntu 20.04 on my machine, imgui windows sometimes behave weirdly. I can't get a consistent repro, but if I try running commands such as `format help`, `format recent`, `help active`, etc. enough I eventually experience either one or both of the following:

- The text is displayed far too small to be readable. I don't think this is an `imgui.scale` issue.

- There is a brief white flash, I think on the whole screen, before the imgui window is displayed.

Here is a screenshot of the small text issue, in which there are two imgui windows of normal size displaying help search & recent formatters, and one tiny-unreadable-text one mid-screen, slightly above the "recent formatters" window, to the right of the word "fixed" in Slack chat:
![Screenshot from 2020-12-25 12-02-17](https://user-images.githubusercontent.com/16143/103134639-f5639800-46b2-11eb-9d98-3d37f623317b.png)

**Comment by rntz** [comment]
It might be worth noting that one imgui window that doesn't seem to be affected by this is my command history window, which I keep open all the time. That seems to consistently have text of the right size. But in vanilla knausj if I repeatedly open & close it sometimes it exhibits the problem too. Maybe it has something to do with opening the command history window during startup?

**Comment by knausj85** [comment]
For what it's worth, I see a flash reliably on Mac OS X 11.1, Macbook Pro 2019, when the first imgui is opened.

* Cold start talon
* "format help" command

Haven't seen this on Windows.

**Comment by lunixbochs** [comment]
fixed in v0.1.4
