### ISSUE TITLE
audio doesn't work after putting system to sleep

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#193]
When I put my computer to sleep, talon no longer recognizes popping noises. The only reliable way I can get it to work again is restarting talon. Is anything I can do to help debug and figure out what is going on? I put a print statement as the first line of a pop handler, and it isn't getting run.

**Comment by lunixbochs** [comment]
does it start working again if you manually switch mics in the talon menu?

**Comment by dwiel** [comment]
Yeah that does the trick. It is infact still working, its just using the wrong mic. The menu bar says it is using "System Default (Sennheiser DECT)" but it isn't. it is using the builtin mic.

**Comment by lunixbochs** [comment]
Need two things for this:
1. [x] Sleep/wake events on each OS.
   - [x] macOS
   - [x] Linux
   - [x] Windows
2. [x] Wire these events up to re-initialize the audio system.

Linux: we need the d-bus signal `PrepareForSleep`. Some examples here: https://serverfault.com/questions/573379/system-suspend-dbus-upower-signals-are-not-seen

Windows: we need to listen to `WM_POWERBROADCAST`. Example here: https://forum.qt.io/topic/69485/do-an-operation-when-computer-goes-to-sleep

**Comment by lunixbochs** [comment]
Should be fixed in beta `v0.1.5-367`, please confirm.

**Comment by lunixbochs** [comment]
confirmed by a few other folks, please reopen or file a new issue if you're still running into this
