### ISSUE TITLE
Alphabet help window should be independent of the main help window

### ISSUE THREAD

**Issue by garrettr** [talonvoice/talon#196]
# Description

As a new talon user, I find it helpful to keep the alphabet help and command history windows visible continuously. I keep them on the edge of my screen for quick reference at all times.

the only issue with this setup is the alphabet window is not independent of the main help window. if I use a help command, the alphabet help window disappears and is replaced by the main help window, which is also automatically centered. every time I finish using a help command, I need to switch back switch back to alphabet help and reposition the window.

# Steps to Reproduce

1. talon wake
2. help alphabet
3. reposition the alphabet help window.
4. help active
5. help alphabet

# Proposed Change

I suggest either:
1. make the alphabet help window independent of the main help window.
2. make the alphabet help window remember its position

**Comment by lunixbochs** [comment]
Talon doesn't define those windows itself. They're entirely controlled in your user scripts, so you could make this customization yourself, or file an issue with knausj_talon: https://github.com/knausj85/knausj_talon

I did file a separate issue #197 for remembering imgui position in general

**Comment by garrettr** [comment]
> They're entirely controlled in your user scripts

TIL, thanks!
