### ISSUE TITLE
malformed additional_words.csv breaks dictation mode

### ISSUE THREAD

**Issue by seabadger** [talonvoice/talon#199]
How to reproduce: in knausj, in additional_words.csv, put a space after the comma (i.e., the spoken form column starts with a space).

Effect:  dictation will get into a broken state,  dictation itself is no longer functional ( no output is being produced),  and it's impossible to get back into command mode.

**Comment by lunixbochs** [comment]
fixed in next beta

**Comment by seabadger** [comment]
thank you :)
