### ISSUE TITLE
Some numbers break <dgndictation> capture

### ISSUE THREAD

**Issue by tuomassalo** [talonvoice/talon#2]
(From https://talonvoice.slack.com/archives/C7ERD5Q5T/p1518440607000092)

I'm having a hard time trying to add a `spring` (jump to line) command. The <dgndictation> part seems to catch only a part of the numbers I say, depending on the numbers:
```
IO phrase ['spring', 'one\\number', 'two', 'three', 'four']
IO phrase ['spring', 'one\\number', 'two', 'three', '5']
```

In the latter example, i only get '123' to the spring command, and '5' is executed as its own command and thus prints '5'. (edited)

Also, `smash one two three four` prints "onetwothreefour", `smash one two three five` prints "onetwothree5".

Also also, `say one two three four` prints "one two three four", `say one two three five` prints "one two three5", and `say one two three five over` prints "one two three five".

**Comment by tuomassalo** [comment]
Using `spring (zero | oh | one | two | three | for | five | six | seven | eight | nine)+` did not help, but I found a workaround:

```spring (zero | oh | one | two | three | for | five | six | seven | eight | nine | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9)+```

**Comment by tuomassalo** [comment]
Also this works:  ```spring (oh | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9)+```

NB: `oh` is a synonym for zero.

**Comment by lunixbochs** [comment]
Should behave as well as can be expected in new parser.
