### ISSUE TITLE
Set DPI scale for imgui on Windows

### ISSUE THREAD

**Issue by lunixbochs** [talonvoice/talon#203]
See here: https://stackoverflow.com/a/29417620

Note: Windows will now change DPI scaling without restarting apps or logging out, so I'll need to handle that.

**Comment by chtenb** [comment]
The current workaround of upscaling the imgui.scale setting makes the help window go off screen if there are many help entries.

**Comment by lunixbochs** [comment]
You can drag the window around, also there's probably configuration in knausj to change the number of entries, which is hardcoded in the open source knausj code.

**Comment by lunixbochs** [comment]
Duping to #262
