### ISSUE TITLE
Trying to throttle pop noise to prevent it from triggering speech ends up disabling speech entirely

### ISSUE THREAD

**Issue by okonomichiyaki** [talonvoice/talon#204]
with my mic the pop noise often gets interpreted as speech so Talon will input one of `1`,`2`, `b`, `oh`, or sometimes other chars, at the same time as it handles the pop for mouse

i tried to fix it with this change to mouse.py: https://github.com/okonomichiyaki/knausj_talon/commit/07a9b82f2850d39a0ad727f0b6c6b72607e02099

this partially works for a while. i saw a significant reduction in the number of spurious chars (but not 100%)
when popping, i see Talon go from green to red and back to green

the bigger issue is that after a while, speech recognition ends up totally disabled. even though Talon is green and in the context menu it says speech rec enabled, but no commands work. they are in the logs (`EMIT`) just not doing anything

**Comment by lunixbochs** [comment]
Is pop still emitting speech for you with conformer?

**Comment by okonomichiyaki** [comment]
I hadn't noticed because I had workarounds for the few words it did emit, but you're right I think it's not an issue with conformer! based on not seeing any recordings of "pop" since I switched

**Comment by lunixbochs** [comment]
in d-series I'm additionally training the model to reject mouth noises, this should doubly not be a problem then
