### ISSUE TITLE
[Feature request] Add ability to restrict commands to a particular engine e.g. wav2letter

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#205]
e.g. to help prevent w2l from waking up 
```
engine: wav2letter
and mode: sleep
-
<phrase>: skip()
```

Use case: 
allows us to better support both Dragon and wav2letter in the community repository

**Comment by lunixbochs** [comment]
note that on top of this we can't currently tell the difference between sconv and gen2 models from python

**Comment by lunixbochs** [comment]
engine scope landing in next beta and v0.1.5, and as a bonus you can also match the microphone name:

```
>>> scope.get('speech')
{'engine': 'wav2letter', 'microphone': 'd:vice MMA-A'}
```
