### ISSUE TITLE
ui API: expose virtual desktops

### ISSUE THREAD

**Issue by timo** [talonvoice/talon#207]
From my talon config, i have an action `switch_desk`:

`os.system("wmctrl -s " + str(int(index) - 1))`

**Comment by lunixbochs** [comment]
Any idea what this is doing behind the scenes?

**Comment by mankoff** [comment]
@lunixbochs  `wmctrl` is a linux command to script window manager behavior. I have that same function scripted with `os.system("xdotool set_desktop " + str(int(index) - 1))`

Desktops are 0-based, hence the `-1`.

**Comment by mankoff** [comment]
Or, more technically, it's calling this function:

https://github.com/dancor/wmctrl/blob/0181e8e4a7ed98255f6ef930875e56560f19aa95/main.c#L584-L596

with I think the work being done by `if (XSendEvent(disp, DefaultRootWindow(disp), False, mask, &event)) {`

**Comment by lunixbochs** [comment]
This landed on Linux in a recent beta
