### ISSUE TITLE
Mouse cursor gets stuck for 20 to 30 second intervals

### ISSUE THREAD

**Issue by nicklives** [talonvoice/talon#208]
Toby five device, Windows 10 operating system, mouse cursor will frequently stop moving with my eyes for 20 to 30 second intervals. In debugmode the red line continues to track my eyes, while the circles remain stuck with the cursor.
![screenshot-20210116191413](https://user-images.githubusercontent.com/29785142/104829395-9667ed80-5830-11eb-89fc-b78fbd2eedea.png)

**Comment by lunixbochs** [comment]
@nicklives is this still a problem for you on v0.2.0?

**Comment by lunixbochs** [comment]
I'm closing as I fixed a lot of windows related issues and nobody else is running into this, please reopen and confirm the latest affected version if you're still hitting it
