### ISSUE TITLE
ui.screens() sometimes reports incorrect screen sizes

### ISSUE THREAD

**Issue by lucasluitjes** [talonvoice/talon#218]
This happens intermittently, please let me know what I can do to debug next time this happens.

Correct output when I have a 27 inch monitor connected to my laptop:

```
>>> ui.screens()
[Screen(x=0.0, y=0.0, size=(1920.0, 1080.0), mm=(597.0, 336.0)), Screen(x=0.0, y=0.0, size=(1920.0, 1080.0), mm=(309.0, 173.0))]
```

The most recent time this happened however, it reported both screens as having the same size, breaking eye tracking on external monitor:

```
>>> ui.screens()
[Screen(x=0.0, y=0.0, size=(1920.0, 1080.0), mm=(309.0, 173.0)), Screen(x=0.0, y=0.0, size=(1920.0, 1080.0), mm=(309.0, 173.0))]
```

Monitor: https://eu.aoc.com/en/monitors/q27p1
OS: pop!_os 20.04 (ubuntu with some extras)
Gpu: Mesa Intel® Xe Graphics (TGL GT2)
Cable type: hdmi
Window manager: GNOME (using x11, not wayland)

**Comment by lunixbochs** [comment]
this should be fixed in beta 0.2.0-85, please test and report any issues to the beta channel or #382
