### ISSUE TITLE
Auto sleep / timeout

### ISSUE THREAD

**Issue by mankoff** [talonvoice/talon#219]
It would be nice to have talon auto-sleep after a certain amount of time. This way if I walk away from my computer and come back, it doesn't start operating when I speak, without me saying `talon wake`.

**Comment by lunixbochs** [comment]
This seems to work for me:

```
from talon import actions, cron, speech_system

job = None
def on_phrase(j):
    global job
    if j.get('phrase'):
        cron.cancel(job)
        job = cron.after('15m', actions.speech.disable)

speech_system.register('post:phrase', on_phrase)
```

**Comment by mankoff** [comment]
Yes this works really well thank you.
