### ISSUE TITLE
Allow a canvas to to be on top of every other window

### ISSUE THREAD

**Issue by fmagin** [talonvoice/talon#222]
## Short Description

There can still be windows that get drawn above the Talon canvas, which means that any accessibility feature that uses canvas drawings will not work on those windows.

Some examples are `dmenu` or the Intellij toolbar windows.

## Bug Details
The exact configuration required for this isn't clear, because this involves the Window Manager and potentially the compositor.

The following is an example where there is no compositor, so transparency is not supported:
![image](https://user-images.githubusercontent.com/8415354/105837253-bc2e8880-5fce-11eb-920e-775a3e05d671.png)

The canvas with a black background and the eye tracking debug overlay masks nearly everything else, but if a popup like the PyCharm toolbar is opened, it will be on top of the debug overlay.

## Things I looked into and tried

According to the [Window Manager Spec Stacking Order](https://specifications.freedesktop.org/wm-spec/1.3/ar01s07.html#STACKINGORDER) the `_NET_WM_STATE` of `_NET_WM_STATE_ABOVE` that Talon sets should have been enough to be at the top of the hierarchy. It is unlikely that the PyCharm tooltip has set `_NET_WM_STATE_FULLSCREEN`.

But setting  `_NET_WM_STATE_FULLSCREEN` and focusing it  (via i3 config) on the Talon window is not enough either, and the PyCharm tooltip will still mask it.

## OS and related info

Currently this only seems to be an Issue on Linux with X11, specifically I am using i3.

**Comment by fidgetingbits** [comment]
I can also confirm on i3, for example when I use dmenu/rofi the window pops over the canvas. this is so rare (for me)that I just never even considered it a bug since those short lived windows are the only one I ever noticed. things like mouse grid, helpwindow, etc are hidden by the dmenu pop-up

**Comment by knausj85** [comment]
this is also an issue on windows and mac os x. would you prefer separate issue(s), or should we just track them all here?

**Comment by lunixbochs** [comment]
I think i3 has weird rules about always-on-top controlled by your i3 config, I don't think your i3 config can be solved by Talon. Happy to hear about any other cases where this is currently a problem.
