### ISSUE TITLE
On Ubuntu, focus switching fails after closing a window

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#223]
On Ubuntu 20.04.1, Talon beta 1532.

Problem: `focus SOME_APP` doesn't always focus SOME_APP.

To reproduce: Have an app, let's assume firefox, with more than one window open. Focus one of those windows and close it. Make sure that when you do this, none of the apps' other windows come into focus - eg. by focusing some non-firefox window before you focus the firefox window to be closed, or by putting the other firefox windows on a different workspace. Now, say `focus firefox`. Alternatively, using the Talon repl, grab firefox directly from `ui.apps()` and call `firefox.focus()`.

Expected behavior: some firefox window gets focused.
Actual behavior: nothing.

I don't *think* this is because of focus stealing blocking, as I have disabled that using a gnome extension: https://extensions.gnome.org/extension/1005/focus-my-window/. Happy to debug this further if there is more info that would help.

**Comment by lunixbochs** [comment]
should be fixed in latest beta, please reopen if you have another reproduction case

**Comment by rntz** [comment]
does not appear to be fixed for me? Same reproduction: have an app w/ more than one window open, close the window (arranging things so that another window of the same app does not get focus afterwards), run `focus APPNAME`. nothing happens.

on -393, ubuntu 20.04, default wm.

**Comment by rntz** [comment]
same underlying cause, too: an active_window which does not exist. after reproing, run:

```
>>> firefox = ui.apps()[WHATEVER]
>>> firefox.active_window in firefox.windows()
False
```
