### ISSUE TITLE
[OS X] When selecting one of the Talon submenus via Zoom Mouse, it closes Talon's menu

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#224]
10.15.6
v1488

This doesn't happen on Windows FWIW; I've also only encountered the issue with Talon's menu. I only noticed since my microphone switcher no longer works. Probably QT's fault :-) 

Repro: 
- Open Talon menu 
- Attempt to select one of the submenus via zoom mouse

**Comment by lunixbochs** [comment]
should be fixed in 0.1.5-256, please test

**Comment by knausj85** [comment]
The bug was no match for a little swizzle; fixed
