### ISSUE TITLE
Falls over on Dragon exit

### ISSUE THREAD

**Issue by anonfunc** [talonvoice/talon#229]
talon version: v0.0.8-1196-g2d07a86

full restart of talon, starting dragon after, it does go from w2l to dragon then
quitting dragon gave me a lost connection error and talon as a whole seems to be stuck
no logging output, no response to verbal commands
repl is responsive
>>> speech_system.engine
EngineProxy(DraconityEngine(dragon))
>>>

**Comment by lunixbochs** [comment]
have received no other reports, and Dragon users on both Windows and Mac can't repro this on current Talon, so closing
