### ISSUE TITLE
Long numerical phrases are not recognized when following a decimal

### ISSUE THREAD

**Issue by dwighthouse** [talonvoice/talon#23]
Entering float numbers only works to some set of digits after the dot, depending on unknown factors.

These are recognized:

* 3.1
* 3.14
* 3.141
* 3.1415
* 31.4159 - How many numbers before the dot seem to matter
* 31.41592
* 31.415926
* 314.1592
* 314.15926
* 314.5373652 - Some sequences seem to be handled better than others
* 3141592653589793238462643383279 - Sequences without a dot have no apparent limit

These are not recognized:

* 3.14159
* 31.4159265
* 314.159265

**Comment by lunixbochs** [comment]
Just tested and the beta engine can say all of these numbers, does Dragon still have an issue with this in latest 0.0.8?

**Comment by lunixbochs** [comment]
This is not a problem in newapi, which uses a new `<number>` capture that is reliable in all engines.
