### ISSUE TITLE
Talon system tray settings are unaccessible on vanilla gnome desktop environment

### ISSUE THREAD

**Issue by vimsos** [talonvoice/talon#232]
# Description
There are linux desktop environments (gnome and elementary that I know of) that don't implement a system tray out of the box. In these desktop environments when the user launches Talon he will be unable to access the settings provided by the current system tray icon.

# Possible Solutions
* Ubuntu distributes their version of gnome with an extension installed that re implements the system tray, perhaps gnome users from other distributions could be instructed to install the same extension https://extensions.gnome.org/extension/615/appindicator-support/
* There is a similar workaround for elementary OS https://github.com/mdh34/elementary-indicators
* Talon could detect that it is running in a desktop environment that does not support the system tray and fall back to drawing an on-screen display using the current drawing API

**Comment by lunixbochs** [comment]
Another user requested a CLI interface that replaces the menu.

**Comment by vvwvin** [comment]
Do you have plans to make Talon run as a systemd service?

**Comment by lunixbochs** [comment]
closing until wayland future is more certain.
