### ISSUE TITLE
[OS X] canvas for eye tracking calibration is incorrectly sized under certain circumstances

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#234]
I typically use my MacBook Pro with an external monitor with the laptop closed. My eye tracker is attached to the external monitor.

If I start talon with both monitors and then close the laptop monitor, the canvas for eye tracking calibration is incorrectly sized and it is not possible to calibrate. 

MacBookPro16,1
LG UltraFine:
  Resolution:	3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)

**Comment by knausj85** [comment]
FYI this also causes issues with e.g. window snapping positions

**Comment by lunixbochs** [comment]
just fixed as part of #382
