### ISSUE TITLE
App.background does not reflect current state on Mac

### ISSUE THREAD

**Issue by nriley** [talonvoice/talon#238]
Mac apps can be "transformed" ([TransformProcessType](https://developer.apple.com/documentation/applicationservices/1462420-transformprocesstype?language=objc) or [NSApp setApplicationPolicy:](https://developer.apple.com/documentation/appkit/nsapplication/1428621-setactivationpolicy?language=objc)) from background to foreground apps. It seems the `background` property of apps in Talon does not take this into account (perhaps it only looks at the `Info.plist` on disk), so it returns `True` for this app even though it has an icon in the Dock and can be activated.

You can examine the [NSApplicationActivationPolicy](https://developer.apple.com/documentation/appkit/nsrunningapplication/1533103-activationpolicy?language=objc) of a running application, which should reflect these changes.

The issue that prompted this was that I couldn't bring an app to the front because the knausj switcher was filtering apps where `background=True`. The app in question returns NSApplicationActivationPolicyRegular. For the purposes of the switcher, it might make sense to also consider NSApplicationActivationPolicyAccessory as non-"background".

**Comment by lunixbochs** [comment]
fixed by upcoming beta
