### ISSUE TITLE
Firmware update from Windows stops Talon from connecting with Eye Tracker

### ISSUE THREAD

**Issue by RustyMoyher** [talonvoice/talon#24]
At first Talon worked with the eye tracker (Tobii 4C) worked, but now when I run Talon it says “Error in eye. Eye Tracker failed to open”.  

The firmware was updated on the Tobii 4C when I was setting it up in Windows. Did this change the Product ID and Vendor ID?

From the mac system information:
 Product ID:    0x0127
 Vendor ID:    0x2104

**Comment by lunixbochs** [comment]
this is fixed
