### ISSUE TITLE
[Windows] uiautomation/accessibility integration

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#252]
this would mostly be for enabling "show numbers"-type functionality, and maybe some text area stuff, on Windows down the line. I was looking into doing it locally, but it seems to be kinda blocked by https://github.com/talonvoice/talon/issues/216; need to dig further  

I also think it makes sense as a fallback for when eyes are tired from eye tracking, or otherwise unusable/unavailable

**Comment by lunixbochs** [comment]
try again with latest beta

**Comment by lunixbochs** [comment]
There's a windows accessibility API in the Talon beta.

look at `ui.active_app().element`, and `ui.element*`
