### ISSUE TITLE
native clipboard clients

### ISSUE THREAD

**Issue by lunixbochs** [talonvoice/talon#258]
- [x] mac
- [x] linux
- [x] windows

Looks like Qt's clipboard implementation has enough quirks to be worth shipping my own cross platform clipboard client.
For example, there are complaints about Qt's clipboard sometimes stalling for several seconds on Linux during repeated access.

**Comment by lunixbochs** [comment]
I believe the Linux Qt clipboard issue is mitigated in the next beta, which delays the need for this work.

**Comment by knausj85** [comment]
I don't know if this merits a separate issue or not, but I keep running into this error on Windows:

```
OleSetClipboard: Failed to set mime data (text/plain) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (The parameter is incorrect.)
```

I can't find a consistent repro, though is seems to happen pretty consistently when using `user.paste` in the talon repl. Usually all subsequent paste actions fail; I've seen it randomly recover, but not sure how yet.

**Comment by lunixbochs** [comment]
Googling it suggests a Qt issue. I'll try to update qt on windows soon

**Comment by lunixbochs** [comment]
done in talon-rust
