### ISSUE TITLE
Feature Request: Semantics-Aware Hierarchy Navigation

### ISSUE THREAD

**Issue by dwighthouse** [talonvoice/talon#26]
This feature request is for a mode or method for allowing navigation within a text document (primarily within the context of code documents) wherein the user can quickly move the cursor into, out of, and increment around the different levels of a programming language's hierarchical structures.

A given language will, in a given file, have various things like namespaces, classes, methods, blocks, statements, and primitives. Each of these listed things flow from less precise to more precise. In this proposed mode, the user would be able to navigate up and down at the class level, until he wishes to get more specific: something inside that class. The user could then jump into the class, into the second method, into the third block, into the 5th statement, and into the beginning of the string declaration to put the cursor: `'|here'` at which point you can no longer go deeper. The user can easily go in and out of the different levels at any time.

Something like this has been implemented in the past to allow rapid code editor navigation using a game controller. A few voice commands and up/down (or eye tracking) could do the same or better. By allowing the user to think in terms of a hierarchy of ever more specific language structures, rather than lines, characters, and searches, the operation of getting to and from any particular part of the code becomes binary-search like, instead of linear. Additionally, operating in this mode could make code collapsing/expanding management more intuitive.

Further integration into editors would include some form of highlighting the portion of the hierarchy in question, so the user doesn't get confused about what level of operation he is at during his navigating.

Prior art and possible helpful information:

* https://github.com/tree-sitter/tree-sitter
* https://github.com/atom/atom/pull/16299
* https://github.com/scrooloose/nerdtree

With some exceptions, this kind of navigations will be language specific, so hooking into an existing language AST parser should allow the system to only specify what type of language objects constitute which types of levels, without having to implement these rules ourselves for each language.

**Comment by lunixbochs** [comment]
supported by cursorless: https://github.com/pokey/cursorless-talon
