### ISSUE TITLE
Automatic reloading doesn't catch python imports?

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#263]
If there are two python files, A and B, in my user directory, and B imports A, and I change A, talon does not appear to reload B. In my case, A is draft_ui.py and B is draft_talon_helpers.py from https://github.com/splondike/talon_draft_window.

The relevant import is
```
from .draft_ui import DraftManager
```

**Comment by lunixbochs** [comment]
Can you post the talon log from updating the A file?

**Comment by lunixbochs** [comment]
fixed in 0.1.4-213
