### ISSUE TITLE
Delta/diff updates for updater (save bandwidth)

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#265]
The Talon .xz distributions on Linux are currently about 133mb. Most of the contents of the .xz files are unchanged between beta releases. This means we have to download a bunch of files we already have.

It would be nice if the updater were able to just send the difference between the current version and what we're upgrading to, saving bandwidth. See for example the behaviour of the RPM and DEB packaging formats.

**Comment by lunixbochs** [comment]
I made the whole-app download significantly smaller
