### ISSUE TITLE
Autocompletion in REPL doesn't work on Windows.

### ISSUE THREAD

**Issue by tbertelsen** [talonvoice/talon#270]
### Steps to reproduce:

 * Open Talon REPL
 * Type `ui.` and press Tab

### Expected:

I would expect to see a list of methods I can call.

### Actual

Tab-character is inserted

### Context:

Talon: v0.1.5 (0)

https://talonvoice.slack.com/archives/C9MHQ4AGP/p1615559585093300

I found this guide: https://edwards.sdsu.edu/research/autocompletion-in-default-python-shell/ but `readline` can't be imported:

```
>>> import readline
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "app/resources/loader.py", line 359, in import_hook
ModuleNotFoundError: No module named 'readline'
```

**Comment by lunixbochs** [comment]
fixed in beta v0.1.5-433
