### ISSUE TITLE
integrate macOS facial expressions

### ISSUE THREAD

**Issue by jonaskindler93** [talonvoice/talon#275]
Apple supplies facial expressions to do  mouse clicks. To make these more flexible it would be great if the expressions could be integrated in talon (See screenshot for available expressions).
![Screenshot 2021-03-24 at 17 34 42](https://user-images.githubusercontent.com/13691822/112439060-f30fe900-8d48-11eb-8312-0799139ab05b.png)

**Comment by lunixbochs** [comment]
Looks like you can bind one to left click and another to right click then detect the device ID with talon tap to rebind the action in talon

**Comment by lunixbochs** [comment]
I just found an old CoreImage API for several of the expressions (macOS 10.7): https://developer.apple.com/documentation/coreimage/cifacefeature?language=objc

**Comment by lunixbochs** [comment]
this will be in the next beta
