### ISSUE TITLE
settings.get has wrong type annotation, can return None

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#276]
`settings.get` has the return type `Union[float, int, str, List[Any]]`, but if you ask for the value of a setting that is not set you get `None`, which is none of those

**Comment by lunixbochs** [comment]
hmm. should I throw an exception instead, if you don't provide a default value to `get()`?

**Comment by rntz** [comment]
I have no strong opinion either way.

**Comment by lunixbochs** [comment]
the annotation allows None now
