### ISSUE TITLE
Eye tracker mouse movement is choppy on Windows with Tobii 4C 

### ISSUE THREAD

**Issue by grantnathanielbrown** [talonvoice/talon#277]
When using a Tobii 4C eye tracker on a freshly installed version of Talon on Windows, the movements of the cursor derived from using only my eyes (as opposed to tilting or rotating my head) are somewhat choppy/laggy.

Eye Mouse Movement Windows: https://talonvoice.slack.com/files/UD1NZ0SLA/F01T1B97Q04/new_tab_-_google_chrome_2021-03-30_14-05-39.mp4
Head Mouse Movement Windows: https://talonvoice.slack.com/files/UD1NZ0SLA/F01SNEK7BB8/slack___vip___talon_-_google_chrome_2021-03-30_14-21-31.mp4
Eye/Head Movement Mac: https://talonvoice.slack.com/files/UD1NZ0SLA/F01SNF5NHC6/screen_recording_2021-03-30_at_2.25.51_pm.mov

Please let me know if you need any more clarification. Thank you.

**Comment by lunixbochs** [comment]
Can someone try running `lib.timeBeginPeriod(1)` in the Talon REPL on Windows with a 4C and see if it helps with the jitter?

**Comment by grantnathanielbrown** [comment]
Just tried that, didn't seem to have an effect. However, like we spoke about earlier, I've been having a similar issue when using my Mac (as well as someone else's Mac) so it is likely related to the Tobii hardware.

**Comment by lunixbochs** [comment]
I've fixed all known issues relating to timer jitter on windows.

If there's still a lack of smoothness, I've been working on a new algorithm that is completely smooth and will hopefully launch in the next Talon release version.
