### ISSUE TITLE
[macOS] ui.screens() returns incorrect coordinates on monitor disconnect / reconnect

### ISSUE THREAD

**Issue by ghost** [talonvoice/talon#278]
`ui.screens()` returns incorrect coordinates when I disconnect my external monitor and then when I reconnect it again. I have a 1440p external monitor (a Dell U2715H) and a MacBook Pro with a 1920x1200 display. I connect the monitor to my laptop with an HDMI cable through one of Apple's USB C multiport adapters.

Output before disconnecting:
`[Screen(x=0.0, y=0.0, size=(2560.0, 1440.0), mm=(596.5504497563073, 335.5596279879229)), Screen(x=2560.0, y=746.0, size=(1920.0, 1200.0), mm=(330.63050350900426, 207.34693566147163))]`

Output when I disconnect. I think this is wrong as x, y should be 0, 0:
`[Screen(x=2560.0, y=746.0, size=(1920.0, 1200.0), mm=(330.63050350900426, 207.34693566147163))]`

Output when I reconnect. Definitely wrong since it can't be that both displays have a 0,0 origin:
`[Screen(x=0.0, y=0.0, size=(2560.0, 1440.0), mm=(596.5504497563073, 335.5596279879229)), Screen(x=0.0, y=0.0, size=(1920.0, 1200.0), mm=(330.63050350900426, 207.34693566147163))]`

If I quit Talon completely and start it again, things are back to normal:
`[Screen(x=0.0, y=0.0, size=(2560.0, 1440.0), mm=(596.5504497563073, 335.5596279879229)), Screen(x=2560.0, y=746.0, size=(1920.0, 1200.0), mm=(330.63050350900426, 207.34693566147163))]`

Some more details:
Talon build 108-0.1.5-34-gc004
MacBook Pro (15-inch, 2018)
macOS Catalina (10.15.7)

**Comment by lunixbochs** [comment]
this should be fixed in beta 0.2.0-85, please test and report any issues to the beta channel or #382
