### ISSUE TITLE
Feature Request: Disable/Mirror an eye for tracking

### ISSUE THREAD

**Issue by riberajo** [talonvoice/talon#28]
It would be great to have a disable/mirror eye function for people with a lazy eye.

A quick fix is to navigate to:
/Applications/Talon.app/Contents/Resources/plugins/eye_mouse.py

Following the line
`        l, r = EyeFrame(b, 'Left'), EyeFrame(b, 'Right') `
you can override which ever eye you want to mirror the other, ie r = l or l = r

**Comment by lunixbochs** [comment]
The new Control Mouse mode in Talon 0.3 is more tolerant of lazy or missing eyes, please let me know if you get a chance to try that.

**Comment by lunixbochs** [comment]
Talon 0.4 has a left/right/both setting in the menu.
