### ISSUE TITLE
more helpful error message around  `ValueError: invalid modifier key: 'command'`

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#280]
I got the following error message: `ValueError: invalid modifier key: 'command'`. Something like `ValueError: invalid modifier key: 'command' did you mean 'cmd'?` would have saved me from having to look around for what i was supposed to us. Probably most helpful for new users.

**Comment by lunixbochs** [comment]
```
ValueError: Invalid modifier key: 'command'. Try one of these: cmd, win, super, ctrl, shift, alt, fn
```
