### ISSUE TITLE
Eye tracking: Cursor position update needs to happen sooner when changing gaze position on 27" 5k screen

### ISSUE THREAD

**Issue by dsc8x** [talonvoice/talon#281]
**Current behavior**
When I gaze at a new position that is around 2cm from the old gaze position, the cursor does not jump.

**Expected behavior**
The cursor should jump to the new gaze position as soon as it's around 1cm apart from the previous gaze position. Ideally, sensitivity should be configurable, as precision may vary for each person/setup.

**Additional Info**
I'm using the LG UltraFine 5k 27" monitor.

To make it work for me, I manually change the `zone1` multiplicator in `eye_mouse.py` from `200` to `25`. But of course that manual code change get's overwritten on each update.

I saw, that you added some TODO notes above that code area. I created this ticket to keep track of the issue.
As a quick fix, making this value configurable would be great :)

**Comment by lunixbochs** [comment]
no longer applies in control mouse 2
