### ISSUE TITLE
Unable to use Talon to input administrator password or interact with installation popup

### ISSUE THREAD

**Issue by tararoys** [talonvoice/talon#282]
I was attempting to install firefox on a windows 10 surface Pro while I was logged in to a guest account.  I was using Talon 0.1.5-51-g3121 

I could not use Talon to input the administrator password, and after I input the administrator password, when the installation screen popped up, I was unable to to use Talon to interact with the installation dialog.  Some of the talon commands worked, but none of the ones that involved acting like a mouse or acting like a keyboard worked.  

![image](https://user-images.githubusercontent.com/1163925/113511571-fa43ad80-9525-11eb-86cb-a2f64fece009.png)
Specifically, when this dialog popped up, most talon commands (and all of the useful talon commands that would have let me click on things or take the focus off the troublesome window) stopped working. 

You can see exactly what I tried starting at minute 3:19 in the [linked youtube video here](
https://www.youtube.com/watch?v=OR03sSXqOpc&feature=youtu.be)

More details: 

I have a macbook surface pro. I have one administrator account and two guest accounts.  I have different versions of Talon installed on each guest account.  I am unsure about how much programs are shared between accounts, since I can use programs I installed on my administrator account in my guest account.  So I am not entirely sure if I have different versions installed on different accounts or the same talon installation across different accounts.  On the two guest accounts below, I did reinstall Talon, assuming that they would install on the local account and not touch the other two accounts. However, I created a fourth new user account, and found out that I had access to Talon on it without installing anything, and I only had to accept a the Eula in order to use it.  Which implies to me that I'm using the same program with different script sets on different user accounts, as opposed to three different installations of the same program.  

Talon version on administrator account
   
![AdministratorTalonVersion](https://user-images.githubusercontent.com/1163925/113511060-91f3cc80-9523-11eb-9095-dc697223c987.png)

Talon version on guest account 1
![image](https://user-images.githubusercontent.com/1163925/113510614-46402380-9521-11eb-8f6a-ce02568e7a15.png)

Talon version on guest account 2
![ConformerTalonVersion](https://user-images.githubusercontent.com/1163925/113511079-acc64100-9523-11eb-82fa-4465c7e078fb.png)

**Comment by lunixbochs** [comment]
Talon installed to Program Files should be able to automate an administrator dialog, as well as the UAC prompt, as long as you have the secure desktop turned off (don't dim the desktop).

Talon installed outside Program Files will likely never be able to provide input to an administrator dialog.

It seems like here you were on a non-admin guest account, having installed Talon outside Program Files as the guest user. Windows simply does not give us the capability to type into admin dialogs in that case.
