### ISSUE TITLE
`w2lxpc` consuming CPU even when talon is disabled

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#283]
`w2lxpc` is taking something like 50%-90% of a CPU core on my `MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) - 2.7 GHz Intel Core i7` I have Microphone set to None and Speech Enable is unchecked. Is there something else I need to turn off to prevent this?

**Comment by lunixbochs** [comment]
can you provide a Sample Process for w2lxpc while this is happening?
which talon version?

**Comment by lunixbochs** [comment]
@dwiel is this still happening? can you provide additional debug information?

**Comment by dwiel** [comment]
I have not seen this again in a while
