### ISSUE TITLE
Declare Uniform Type Identifier for .talon files on macOS

### ISSUE THREAD

**Issue by beret** [talonvoice/talon#289]
Currently the Talon package on macOS does not describe a type for .talon files, so although they are plain text, they are not automatically visible in Finder previews or QuickLook.

A current workaround is to manually set attributes on each existing file: `find ~/.talon/user/ -type f -name '*.talon' -exec SetFile -t TEXT {} \+`

Indicating that `.talon` files conform to `public.plain-text` is probably the most practical choice and will enable previews, although other custom or [system types](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html) are available.

I'm not sure if that approach will require Talon.app to accept and open the files though.

**Comment by lunixbochs** [comment]
great idea, thanks! should land in next beta.
