### ISSUE TITLE
Remote Desktop Isn't Recognizing Shift/Ctrl Keys From Talon

### ISSUE THREAD

**Issue by morgankenyon** [talonvoice/talon#291]
I'm running Talon on my personal machine while using [Horizon](https://www.vmware.com/products/horizon.html) to remote in for work. 

The Shift/Ctrl keys aren't being applied when working through the remote. 

Talon is correctly hearing what I'm saying, as evidence by the following command history, but what is output to the remote is everything without the Shift/Ctrl keys.

![image](https://user-images.githubusercontent.com/4063086/115775692-cfa48200-a378-11eb-8af6-edbf5729a5bd.png)

"question mark" => /
"greater than" => .
"less than" => , (comma)
"ship air" => a
"copy that" => c

**Comment by blakewatson** [comment]
This happens to me using Mac's Screen Sharing app as well.

**Comment by awulkan** [comment]
The same happens for the Remote Desktop Connection application in Windows 10.
It only happens if I put the application into fullscreen mode though, so a workaround at the moment is to not use fullscreen.

**Comment by morgankenyon** [comment]
Taking the application out of fullscreen mode also allows this to work as expected for me, makes it less usable. But I might just need to play with settings in order to get it functioning correctly.

**Comment by morgankenyon** [comment]
It turns out that I had the ability to select different RDP protocols. I had been using Windows RDP, which wasn't working, but using VMWare Blast caused it to work as expected. So I'm going to be sticking on that for the time being.

**Comment by lunixbochs** [comment]
Please retest on the latest beta, I've improved Talon's heuristics here.

**Comment by lunixbochs** [comment]
the related modifier key improvements shipped in talon 0.4, please open a new issue if you run into further issues with rdp
