### ISSUE TITLE
[Mac] Disconnecting and reconnecting mic confuses Talon

### ISSUE THREAD

**Issue by lslunis** [talonvoice/talon#292]
When I disconnect my active mic, Talon switches to another mic, as expected. When I reconnect, Talon thinks it has switched back but actually hasn't.

Steps to reproduce:

1. My US-1x2 is connected and shows up as the System Default in both System Preferences and the Talon Microphone menu
2. When I say something, US-1x2 appears in the recording metadata
3. Physically disconnect US-1x2
4. Talon and System Preferences agree that my mic is now MacBook Pro Microphone
5. When I say something, MacBook Pro Microphone appears in the recording metadata
6. Physically reconnect US-1x2
7. Talon and System Preferences agree that my mic is now US-1x2
8. When I say something, US-1x2 appears in the recording metadata, **but I have to speak into the MacBook Pro Microphone**
9. Changing the active mic in the Talon Microphone menu is enough to fix whatever internal state is wrong

**Comment by lunixbochs** [comment]
Should be fixed in beta `v0.1.5-367`, please confirm.

**Comment by lslunis** [comment]
Confirmed
