### ISSUE TITLE
Laggy mouse cursor in Windows starting version 0.1.5-69

### ISSUE THREAD

**Issue by mathiasringhof** [talonvoice/talon#298]
My mouse cursor on Windows started misbehaving after version –51
Current assumption is that maybe the mouse tap events cause the delay as they were added in version -69.

Looking at the overall system performance CPU and memory should be fine. The system is a corporate device with lots of antivirus software installed. Reverting back to 0.1.5-51 fixes the problem.

More details:
https://talonvoice.slack.com/archives/G9YTMSZ2T/p1620048167445300

**Comment by lunixbochs** [comment]
Mitigating this issue in the next beta release by commenting out the Windows event tap.
