### ISSUE TITLE
press('cmd-/') sends cmd + numpad_divide

### ISSUE THREAD

**Issue by tuomassalo** [talonvoice/talon#3]
I'm trying to implement a basic 'trundle' command (toggle comment). The default editor hotkey is `cmd-/`.

I don't know how to send such keystroke, since `press('cmd-/')` sends `cmd` + `numpad_divide` (according to VSCode). Luckily, Atom takes the numpad slash just fine.

NB: if i'm using the Finnish keyboard layout, I can use `press('cmd-shift-7')`.

EDIT: An hour later, I don't seem to be able to reproduce the issue. Now VSCode reports the keypress correctly as `cmd-/`.

**Comment by tuomassalo** [comment]
Might be related:

I'm writing spectacle.py to control window sizes via Spectacle.app. I added `windy left` command that presses `alt-ctrl-left`. It works properly in other apps, but in Atom it changes to previous Atom tab. But if I manually press alt-ctrl-left, the window is resized. I wonder how Atom differentiates between the keypress I physically press and what Talon generates.

**Comment by lunixbochs** [comment]
fixed in 0.0.5.4
