### ISSUE TITLE
Talon using incorrect resolution for external monitor after laptop sleeps - M1 Mac running macOS Big Sur 

### ISSUE THREAD

**Issue by BrokenFlows** [talonvoice/talon#303]
When waking my Macbook Pro, connected to an external monitor via a dock, Talon will sometimes use the dimensions of my laptop monitor instead of the external monitor. This doesn't seem to happen each time the display sleeps, and is more common after a prolonged sleep. Restarting Talon seems to resolve the issue.

Talon seems to think that the monitor a smaller resolution than it does. This is, somewhat, illustrated by the following images.

This image shows where the command history shows up by default, while this is going on:
![command history](https://user-images.githubusercontent.com/21959941/117546149-f1f8f980-b020-11eb-8427-a4515ace4f46.png)
In this image I was looking at the very top right of the screen, and talon thought I was looking nearer the middle-centre:
![looking at top right](https://user-images.githubusercontent.com/21959941/117545780-25d31f80-b01f-11eb-91dc-40e0983d6f3c.png)
In this image I was looking at the very top left of the screen, and talon thought I was looking nearer the middle-left:
![Screenshot 2021-05-08 at 16 55 20](https://user-images.githubusercontent.com/21959941/117545882-924e1e80-b01f-11eb-9b09-09da4de13dca.png)

Taking a page out of nriley's book, on issue #248, using the REPL to ask talon about the screen size yields:
```
>>> ui.screen.screens()
[Screen(x=0.0, y=0.0, size=(1440.0, 900.0), mm=(286.8705839269302, 179.29411495433135))]
```
Those are the non-retina dimesions of my laptop monitor, while monitor I'm using is 1920×1080.

**Comment by lunixbochs** [comment]
this should be fixed in beta 0.2.0-85, please test and report any issues to the beta channel or #382
