### ISSUE TITLE
Map `AltGr` in linux?

### ISSUE THREAD

**Issue by jchwenger** [talonvoice/talon#304]
Hi,

 I couldn't find a way of mapping `AltGr` (right alt)  on linux,  which could be used to [compose keys](https://help.ubuntu.com/community/GtkComposeTable)? Just for reference, after our discussion on slack.

Thanks!

**Comment by lunixbochs** [comment]
The current Linux beta has the "compose" key, and has the "altgr" key (but not as a direct modifier)

**Comment by jchwenger** [comment]
Grand, thanks.
