### ISSUE TITLE
Missing log entries for some errors/events

### ISSUE THREAD

**Issue by codecat555** [talonvoice/talon#307]
In slack to day, you suggest that I fill an issue because a .talon syntax issue was not being flagged in the log.

```
                // TODO: surface these somewhere?
                // unknown_tokens.insert(token);
```
https://talonvoice.slack.com/archives/C7ENXA7C4/p1620766276498100?thread_ts=1620762273.463300&cid=C7ENXA7C4

**Comment by lunixbochs** [comment]
fixed in next beta
