### ISSUE TITLE
hiss/pop click takes last reasonable gaze when cursor disappears

### ISSUE THREAD

**Issue by taleena** [talonvoice/talon#31]
When eye-tracking and using hiss/pop to click, if you blink (or do other micro movements that occlude the eyes), the cursor disappears and the click isn't registered.

Can have hiss/pop click take last reasonable gaze. Unclear how this would play with multi-monitor setup when mouse snaps to non-eye-tracked monitor.

**Comment by lunixbochs** [comment]
I believe this has been fixed for a bit
