### ISSUE TITLE
feature request: remove/unregister/not-register commands

### ISSUE THREAD

**Issue by gpunktschmitz** [talonvoice/talon#310]
it would be great to have a feature (like a file "talon.dont") that would prevent every .talon file from registering the command/word specified.

why this would benefit me personally but also every other user: i want to keep using the knausj-repo but also would like to disable some commands. one solution would be to remove those commands/.talon-files but that would not make it update-friendly.
having "~/.talon/user/talon.dont" with the context "righty" should prevent any .talon-file from registering the command "righty"

**Comment by lunixbochs** [comment]
As a hack, this will probably work for any global commands:
```
os: mac
os: windows
os: linux
-
righty: skip()
```

I'm unlikely to support what you're asking, it's an anti-pattern to the long-term design of Talon. I'm against adding more global concepts that need to be understood to know which commands are defined and active. I generally expect you to be in full control of your user/ directory, so adding one file to user/ that disables another file in user/ is redundant and confusing with that in mind.

There's a recent discussion about this on Slack. https://talonvoice.slack.com/archives/C7ENXA7C4/p1621356861079600

----

As an alternative, you can likely delete an entire .talon file from git on your end, commit the removal of the file, then copy whatever parts of the file you want to a new file, and modify that file as you like. This will effectively replace the file in your repo without causing conflicts on merge.
