### ISSUE TITLE
Invalid window handle raised on 'focus firefox' after window close

### ISSUE THREAD

**Issue by codecat555** [talonvoice/talon#311]
See the following issue for details: https://github.com/knausj85/knausj_talon/issues/433

**Comment by lunixbochs** [comment]
Please note your talon version in this issue.

**Comment by codecat555** [comment]
Talon Version: 0.1.5-213-g72b6

**Comment by lunixbochs** [comment]
these are still other issues with focus on windows, but this particular one is fixed in beta v0.1.5-433
