### ISSUE TITLE
Key tap doesn't work when iTerm2 is focused

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#316]
From a Slack discussion:

- iTerm registers a `kCGHIDEventTap` here: https://github.com/gnachman/iTerm2/blob/c52136b7c0bae545436be8d1441449f19e21faa1/sources/iTermEventTap.m#L223
- This sometimes does not work with hotkeys registered by Talon, such as F16/F17/F18.
-  Other applications, like Rectangle.app, are able to bind these keys in conjunction with iTerm.

**Comment by phillco** [comment]
Follow-up: removing the `kCGHIDEventTap` block linked does not stop the bug, so it's something else

**Comment by phillco** [comment]
Update: it's the entire tap that doesn't work. If you define `tap.register(tap.KEY, print)`, it just doesn't print anything if iTerm is focused.

**Comment by lunixbochs** [comment]
As per another conversation, is this due to iTerm triggering Secure Input for some reason?

**Comment by phillco** [comment]
Update: yup. Turns out all you have to do is uncheck this. Thanks!

![Screen Shot 2021-09-25 at 12 10 04 PM](https://user-images.githubusercontent.com/536668/134783776-b1e20921-c074-4a4c-b6fc-ca7868ecd750.png)
