### ISSUE TITLE
Inconsistent pickup of 'word install' phrase

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#326]
On Talon 1.5.0 with gen2, and beta 1.5.331-g2805 with gen2, and Conformer I have trouble using the 'word install' command; more often than not it comes out as 'in*' when using knausj. Sconv seems to have a different problem (maps to 'store' a lot). This can be reproduced for me with the following being the only file in `user/` aside from engines.py:

```
settings():
    speech.record_all = 1

star: "*"
word <word>: insert(word)
```
I've attached a bunch of attempts, successful and not with the various engines and versions: [word-install-recordings.zip](https://github.com/talonvoice/talon/files/6635485/word-install-recordings.zip).

I seem to have reasonable success if I really ham up the 'll' sound at the end (see some of the recordings in conformer and beta+gen2).

Not sure if this is the right place to post these kinds of issues, so feel free to close if it isn't.

**Comment by lunixbochs** [comment]
Sconv will probably never see the light of day, and we can't squeeze more accuracy out of gen2, so the only model really worth reporting this kind of issue on is Conformer. There's a pinned thread about "conformer possible training bugs" in the beta channel you can post this sort of thing in.

**Comment by lunixbochs** [comment]
Note that I kind of see where it's coming from with your accent and the word `star`. You would probably have more luck either unmapping `star` or americanizing the A sound in your `stall`, here are some examples (it worked every time for me):

[word-install.zip](https://github.com/talonvoice/talon/files/6635520/word-install.zip)

You can also map a second variant of `word` that anchors on the right side to prevent commands from interfering.
