### ISSUE TITLE
imgui changing size can keep old image parts on top of new image

### ISSUE THREAD

**Issue by timo** [talonvoice/talon#327]
![image](https://user-images.githubusercontent.com/25167/122214784-c92f1400-ceaa-11eb-83f3-50ddcb995659.png)

switching pages in the help imgui gives me this artifact, clicking on it with my mouse fixes it, or dragging with "drag" voice command, "touch" alone doesn't help, though.

**Comment by lunixbochs** [comment]
I believe this is fixed in beta 171, can you confirm?

**Comment by lunixbochs** [comment]
I believe this is fixed, please reopen if you're still encountering it on the latest beta.
