### ISSUE TITLE
`eye_mon_snap.py` example stops working after a period of time due to event handler no longer firing

### ISSUE THREAD

**Issue by eliteramen** [talonvoice/talon#33]
`eye_mon_snap.py` from the examples repo works on initial load, but then ceases to work after a short period of time has passed.

Adding `print` statements indicates that the `on_move` method registered with the event tap begins firing as soon as the py file is loaded, but stops firing altogether at some point.

@lunixbochs muses:

> have you tried restarting talon it's possible the macos event handlers are unregistering talon sometimes and I don't handle that event yet

**Comment by lunixbochs** [comment]
fixed in 0.0.7
