### ISSUE TITLE
Key/Str combined with time.sleep results in garbaled results

### ISSUE THREAD

**Issue by dylan-chong** [talonvoice/talon#339]
```python
"""
Propietary commands for my workflow for notes app
"""

from talon.voice import Context, Key, Str
from talon import tap
from talon import ui
import datetime
import time


def on_key(typ, e):
    #  print(ui.active_app().bundle, e)
    if e != 'ctrl-shift-cmd-c':
        return
    if not e.up:
        return

    e.block()

    #  time.sleep(0.3)
    notes_complete_line(None)


def key_with_delay(key_string):
    print('- keying', key_string)
    Key(key_string)(None)
    time.sleep(0.1) ############################ Comment this out to fix it


def notes_complete_line(_):
    print('running *********')
    Str('FIRST')(None)
    key_with_delay('a')
    key_with_delay('a')
    key_with_delay('a')
    Str('SECOND')(None)
    key_with_delay('b')
    key_with_delay('b')
    key_with_delay('b')
    Str('THIRD')(None)


ctx = Context('notes', bundle='com.apple.Notes')
ctx.keymap({
    'notes complete line': notes_complete_line,
})

tap.register(tap.KEY | tap.HOOK, on_key)
```

`Pressing 'ctrl-shift-cmd-c'` should result in `FIRSTaaaSECONDbbbTHIRD` being typed out. However this only happens when you disable the sleep.

If you keep the sleep then only `RD` gets typed out

---

More generally ive noticed that when my cpu is under high load, sequences of keys like the above will not complete in order (some keys are skipped, some wrong modifiers are pressed) - instead of the synthetic `time.sleep` load

**Comment by lunixbochs** [comment]
This issue seems to be for the legacy Talon v0.0.8.42, can you try to reproduce on Talon v0.1.5? There's a hotkey system there, so you can just, in a .talon file, do something like this:

```
key(ctrl-shift-cmd-c:up):
    insert("FIRST")
    key(a)
    sleep(100ms)
    key(a)
    sleep(100ms)
    key(a)
    sleep(100ms)
    insert("SECOND")
    key(a)
    sleep(100ms)
    key(a)
    sleep(100ms)
    key(a)
    sleep(100ms)
    insert("THIRD")
```

Also, it looks like you're sleeping in the middle of a _hook_ event tap. That's very bad - it will prevent keystrokes from being delivered entirely until the OS times us out and removes the tap. The keys you're trying to press need to be processed by the tap event loop, but you're blocking it with a sleep.

**Comment by dylan-chong** [comment]
Ah thanks! it looks like it works perfectly as your suggested version! Thanks!

**Comment by dylan-chong** [comment]
G
