### ISSUE TITLE
Expose position on window object

### ISSUE THREAD

**Issue by eliteramen** [talonvoice/talon#34]
There is currently no way of getting the position of the window (x, y, width, height). Can we expose position on the `window` object?

*Use case:* I am trying to have the mouse cursor automatically "jump" to the active window. To do this, I need to know the window's position and dimensions so I can move the cursor to, for instance, the dead center of the window.

**Comment by eliteramen** [comment]
@lunixbochs suggested as a workaround for now:
> you could probably do it right now with applescript
like get frame of frontmost window and return the center point
python gets the return value
when you call applescript.run

**Comment by lunixbochs** [comment]
`win.frame` is exposed now
