### ISSUE TITLE
Function 'app.window_next()' doesn't work with Mac Spaces

### ISSUE THREAD

**Issue by xavier630** [talonvoice/talon#341]
For example if I make Chrome window fullscreen as a Mac Space (see [spaces](https://support.apple.com/en-ae/guide/mac-help/mh14112/mac)), it's no longer possible to cycle to it from another Chrome window using `app.window_next()`

Note: this affects both `app.window_next()` and `app.window_previous()`

**Comment by lunixbochs** [comment]
app.window_next() is implemented for Mac in knausj here: https://github.com/knausj85/knausj_talon/blob/dded1d6e83c9cedad12ce7928e5c317b25f8306f/code/platforms/mac/app.py#L29-L30

At this level, it isn't a Talon bug. Moving the discussion back to the knausj_talon issue for now.

**Comment by xavier630** [comment]
Apologies, thought it was talon-internal 👍
