### ISSUE TITLE
feature request: api for resetting eye tracker

### ISSUE THREAD

**Issue by codecat555** [talonvoice/talon#343]
I'd like to be able to reset my eye tracker by voice whenever it stops responding. Currently, I do this manually by pulling the cable. I don't usually have to do this too often, although it is a regular occurrence. For some reason, it's happened several times already just today and I can't point to any specific changes that might have triggered the change (except perhaps for yesterday's talon upgrade).

Anyways, since restarting talon seems to fix the problem, I'd like to be able to invoke the eye tracking initialization code on demand without actually restarting talon itself. This would be a convenient work around until there's a better solution for this problem.

Is there perhaps already an api call I could use for this?

**Comment by lunixbochs** [comment]
talon already attempts to reinitialize the eye tracker itself when it fails, I just need to completely tear down the USB stack for it to reinit harder, at which point manual reinit still won't be necessary.
