### ISSUE TITLE
Clicking pop up windows with mouse is not always reliable

### ISSUE THREAD

**Issue by fidgetingbits** [talonvoice/talon#344]
OS: Linux
Distro: Arch
WM: i3wm
Talon version: v0.1.5-478-ga553

In certain pop up windows like command history, etc the ability to click on the window and drag it out is not always reliable. is by not reliable i mean sometimes you have to click like six or seven times before it actually registers, although from my experience it's not deterministic when this will happen or how many clicks you need to use. This happens both on clicking and holding to move the window and also went releasing the mouse to stop moving the window, but sometimes it happens with one and not the other, etc.

On slack you noted that this also sometimes happens on Mac iirc, doesn't seem to be a linux bug.

**Comment by lunixbochs** [comment]
I believe this is fixed in latest beta, please reopen if you're still hitting it.
