### ISSUE TITLE
Make the "About Talon" text selectable

### ISSUE THREAD

**Issue by fidgetingbits** [talonvoice/talon#345]
even though if we want to write the talon version somewhere we could just right -478, i think it's natural to want to copy the entire version from somewhere, but saying the entire thing is somewhat annoying. the default place i tend to find myself trying to grab it from is in the about talon menu because i know it's in there, an i don't always want to dig through my log. currently the about talon window on linux doesn't let you copy and paste the version number, but it would be convenient. i'm sure there's some sort of way to just do this in a command too, but just suggesting this because i assume some new people would naturally go here to find it as well.

**Comment by lunixbochs** [comment]
Done in v0.2.1
