### ISSUE TITLE
Title doesn't update for Emacs on MacOS

### ISSUE THREAD

**Issue by wenkokke** [talonvoice/talon#349]
Neither `ui.active_window().title` nor `actions.window.title()` is able to get the updated window title for Emacs on MacOS.

I am running Emacs version 27.2 on MacOS. The bug was independently reproduced:
https://talonvoice.slack.com/archives/C9MHQ4AGP/p1625933436168200

**Comment by wenkokke** [comment]
Temporary workaround on MacOS available here:
https://talonvoice.slack.com/archives/C9MHQ4AGP/p1625935709170100?thread_ts=1625933436.168200&cid=C9MHQ4AGP

**Comment by lunixbochs** [comment]
was this fixed alongside #502?

**Comment by wenkokke** [comment]
I can't confirm this, since I moved away from emacs.

**Comment by rntz** [comment]
As of talon-0.3.1-673-gcf9d I cannot reproduce this. However, I never explicitly tried to reproduce this on prior versions of Talon, and I'm using a different emacs version (28.2).

**Comment by lunixbochs** [comment]
alright, closing as it's probably fixed. we can reopen if someone finds a new repro in emacs.
