### ISSUE TITLE
`app.windows()` empty when application has a window open

### ISSUE THREAD

**Issue by eliteramen** [talonvoice/talon#35]
I have been having intermittent trouble with `switcher.py` for certain applications (Chrome, and maybe Terminal).

Debugging with Chrome indicates `app.windows()` is empty (where `app` is one of the `ui.apps()`) even when there is a window open. Because of this, it is not added to `switcher.apps`.

Restarting Talon does not appear to fix this. Restarting Chrome may IIRC.

**Comment by eliteramen** [comment]
Update: It started working again with Chrome after a Talon restart. Seems intermittent, not sure yet. I will try to look for any patterns.

**Comment by eliteramen** [comment]
Update: It seems that restarting a application that is not currently being recognized helps. It also seems that an application that is already running when Talon is started is more likely to not be recognized.

**Comment by lunixbochs** [comment]
This should be fixed.
