### ISSUE TITLE
Media playback keys don't work on Windows 10

### ISSUE THREAD

**Issue by SCdF** [talonvoice/talon#351]
Media keys such as volume up and volume down work fine. However play, pause, next and previous track do not work. Specifically setting the volume doesn't work either, but that might just be a Windows API thing.

I have these bound on my keyboard and they work there fine. 

I am using the knausj repository, which defines them as below. I have rearranged them to split them between the ones that work and the ones that don't:
```
# Working
volume up: key(volup)
volume down: key(voldown)
(volume|media) mute: key(mute)

# Broken
set volume <number>: user.media_set_volume(number)
[media] play next: key(next)
[media] play previous: key(prev)
media (play | pause): key(play)
```

**Comment by lunixbochs** [comment]
I think the `play` you want is `play_pause`. There is also a key called play, I don't know what it's for.

`prev` and `next` are wired up to VK_MEDIA_PREV_TRACK and VK_MEDIA_NEXT_TRACK. Can anyone else on Windows confirm these aren't working?

`user.media_set_volume` looks like a knausj feature, so not a Talon bug.

**Comment by AndreasArvidsson** [comment]
play_pause, next and prev all work for me on windows 10. play does not.

**Comment by lunixbochs** [comment]
I assume play presses the play key. I don't know what the play key does.

**Comment by SCdF** [comment]
Thanks everyone. Next and prev do actually work for me, sorry. `play_pause` also works for me on windows.

I'll raise a PR with knausj to get play pause working on Windows, and look into `user.media_set_volume` and where it went.
