### ISSUE TITLE
Improve warning message about unknown tokens

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#352]
`WARNING Skipped unknown tokens: ['-']`

It would be nice if the warning message contained the name of the list or the capture so we more easy can do something about it.

**Comment by lunixbochs** [comment]
we have per-list warnings now:
```
WARNING list 'user.punctuation' skipped unknown tokens: [',', '`']
WARNING list 'user.symbol_key' skipped unknown tokens: [',', '`']
```
