### ISSUE TITLE
Talon should implement join in scripts

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#353]
The ability to join lists into strings in talon files would prevent the need for extra captures to get multiple versions of already existing singular captures.

Today: 
`<user.letter>+: "{letter_list}"` => `['a', 'b']`

With join:
`<user.letter>+: "{letter_list.join()}"` => `'ab'`

**Comment by lunixbochs** [comment]
You can implement that as an action.

**Comment by AndreasArvidsson** [comment]
Yes I know but I think that the above solution looks cleaner and better.  You can think of this as a request if it's not too much work.

**Comment by lunixbochs** [comment]
```
<user.letter>+: "{user.join(letter_list)}" => 'ab'
```

It's a lot of work to think about how I would want to do that properly in the core.

**Comment by AndreasArvidsson** [comment]
Totally understand it was just a thought.

**Comment by lunixbochs** [comment]
I don't think it's cleaner to implement as a method, because TalonScript doesn't currently have methods at all. Just actions. So if I did it I would probably put it in an action namespace exactly as my example above.

**Comment by AndreasArvidsson** [comment]
Ah never reflected over that but you're completely right. Then maybe a core action join could work?
`<user.letter>+: "{join(letter_list)}" => 'ab'`
`<user.letter>+: "{join(letter_list, '_')}" => 'a_b'`

**Comment by lunixbochs** [comment]
I would likely namespace it as either a list or string action.

**Comment by AndreasArvidsson** [comment]
Got it

**Comment by lunixbochs** [comment]
in latest beta:
```
string.join("_", letter_list)
```
