### ISSUE TITLE
key mapping involving cmd-alt-shift-ctrl-space does not work 

### ISSUE THREAD

**Issue by hirendra** [talonvoice/talon#354]
Here is how to reproduce - 
change the mapping for spotlight to say cmd-ctrl-alt-shift-space
map spotlight:key(cmd-ctrl-alt-shift-space)
the keyboard combo will work, while if you dictate it in talon, it will recognize the command but spotlight won't be triggered

the issue persists even if you map spotlight  - ctrl-alt-shift-space

**Comment by lunixbochs** [comment]
this is fixed in the latest beta
