### ISSUE TITLE
Upper case in paths should be ignored on windows

### ISSUE THREAD

**Issue by timo95** [talonvoice/talon#355]
Since windows (NTFS) is case insensitive, case should be ignored when comparing `app.exe`. The same executable can be executed using different cases. This can lead to mismatches in cases like these: https://github.com/knausj85/knausj_talon/issues/437

It shouldn't hurt to implement this for all file systems, instead of only windows.

**Comment by lunixbochs** [comment]
As an awkward looking workaround for now I think you can `app.exe: /^explorer.exe$/i`

**Comment by lunixbochs** [comment]
I'm going to lowercase app.exe on windows.
