### ISSUE TITLE
Closing the window of a multi-window app doesn't trigger context reevaluation

### ISSUE THREAD

**Issue by RichardHladik** [talonvoice/talon#361]
Setup: Linux + i3 (irrelevant?) + probably any app capable of opening multiple windows (tested with Anki, Firefox, Gimp, Libreoffice at least).

When I focus the app, a line in events.tail appears, e.g.:
```
main | win.focus app=firefox exe=/usr/lib/firefox/firefox title='New Issue · talonvoice/talon — Mozilla Firefox'
```
Opening a new window (i.e. Ctrl+N in Firefox for me) produces another line:
```
main | win.focus app=firefox exe=/usr/lib/firefox/firefox title='Mozilla Firefox'
```
But closing it does nothing, even though I'd expect the first line to repeat. And experiments suggest the context reevaluation indeed doesn't get triggered.

I noticed (and discarded) this about a month ago (my TODO list says 2021-06-21); before that, it worked fine, so the regression may have been introduced some time around that point.

**Comment by lunixbochs** [comment]
Can anyone reproduce this on a WM besides i3?

**Comment by RichardHladik** [comment]
I've finally got around to test this with different WMs. The results are… kind of confusing.

WMs that have this bug (= when e.g. opening and closing a new window many times in Firefox, only the "focus the new window" events get registered):

* i3
* openbox (LXDE/LXQT)
* xfwm4 (XFCE)
* metacity (GNOME 2)

WMs that don't have this bug:

* mutter (GNOME 3)
* iceWM
* KWin (KDE)

Also with some WMs, when I opened and closed the window fast enough, I actually got the old window in the output, but I guess that's a race condition between the "focus changed" event firing and getting the info about the currently focused window.

Soo… it mostly seems like the more "old-school" WMs have this bug but the more modern ones do not? I don't know what to make of this.

**Comment by lunixbochs** [comment]
is this actually still happening?

**Comment by RichardHladik** [comment]
Can confirm this still happens as of Talon 0.3.1-744-g08ea + i3-4.22, on Linux, X11. Did the same test and got the same behaviour as in the first comment.

**Comment by lunixbochs** [comment]
how is firefox installed?

**Comment by RichardHladik** [comment]
Using `pacman`, i.e. no funky business with containers. Also rechecked this happens with other programs (gimp, pcmanfm, libreoffice).

Also if after closing the second window, the focus goes to a different application (i.e. a terminal), then the line in events.tail appears. It's only when the focus stays on the same application (but different window) after closing that this bug seems to occur.

**Comment by lunixbochs** [comment]
fixed in beta 751

**Comment by lunixbochs** [comment]
@RichardHladik 751 beta is out, retest if you don't mind

**Comment by RichardHladik** [comment]
Indeed, now it works. Thanks!
