### ISSUE TITLE
[Windows] can't focus explorer window opened by menu.open_talon_home

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#367]
Version: 0.2.0-11-g8007, Branch: beta, OS: Windows-10-10.0.19043

1. Close any explorer windows 
2. use menu.open_talon_home
3. Switch to another app
4. attempt "focus explorer" 

The relevant code seems to be hit, but the window isn't focused. It does appear in the app's window list per the repl.

**Comment by lunixbochs** [comment]
is this still the case?

**Comment by knausj85** [comment]
I can no longer reproduce. I suspect there's something else going on. I'll dig into it if it happens again and open a new bug.
