### ISSUE TITLE
Graceful handling of eye tracker disconnects/reconnects

### ISSUE THREAD

**Issue by eliteramen** [talonvoice/talon#37]
Currently, if Talon starts up without a connected eye tracker, it must be restarted in order to for Talon to recognize it and enable eye tracking options. The same goes for if the eye tracker is disconnected during operation.

If the computer is stationary, this isn't much of an issue unless USB hubs etc are powered down /up separately. However, if the computer is mobile, this issue occurs with greater frequency because the likelihood of different configurations (e.g., desktop hub versus direct connect or smaller mobile hub) and, consequently, number of connections/disconnections increases.

Ideally, Talon is able to detect when an eye tracker is connected and then subsequently enable eye tracking options. Similarly, Talon is able to warn the user if the eye tracker has been disconnected, possibly resuming any running modes (e.g., Control Mouse/Show Camera Overlay) when the device is reconnected.

**Comment by eliteramen** [comment]
Apparently already being worked on:

> @lunixbochs: to detect multiple tobiis, I'm implementing a usb hotplug stream (that will just also generate "device inserted" events for all connected devices when talon starts up)

**Comment by eliteramen** [comment]
> @lunixbochs: that will be fixed by multimon

**Comment by lunixbochs** [comment]
Hotplug is working in 0.0.7.7.
