### ISSUE TITLE
actions.insert() can't insert struckthrough text

### ISSUE THREAD

**Issue by xavier630** [talonvoice/talon#370]
Example of text that can't be inserted:
`t̶e̶s̶t̶`

This is struckthrough text that was created with the unicode character  `\u0336` while making a strikethrough formatter [here](https://github.com/knausj85/knausj_talon/compare/master...xavier630:xdowns/strikethrough?expand=1)

From the error it looks like Talon perhaps can't handle these unicode chars: `talon.mac.ctrl.InvalidKeyErr: ̶`

![image](https://user-images.githubusercontent.com/9077250/127836699-6a8ca155-da29-483a-b398-c60dc99c8a10.png)

Trace:
```
2021-08-02 13:09:15 ERROR    13:      talon/scripting/talon_script.py:590| 
   12:      talon/scripting/talon_script.py:297| 
   11:      talon/scripting/talon_script.py:557| 
   10:           talon/scripting/actions.py:75 | 
    9:             talon/scripting/types.py:366| 
    8: user/knausj_talon/code/formatters.py:296| actions.insert(string)
    7:           talon/scripting/actions.py:75 | 
    6:             talon/scripting/types.py:366| 
    5:                talon/plugins/main.py:32 | 
    4:           talon/scripting/actions.py:75 | 
    3:             talon/scripting/types.py:366| 
    2:                talon/plugins/main.py:69 | 
    1:                    talon/mac/ctrl.py:108| 
talon.mac.ctrl.InvalidKeyErr: ̶

[The below error was raised while handling the above exception(s)]
2021-08-02 13:09:15 ERROR cb error topic="phrase" cb=<bound method SpeechSystem.engine_event of <talon.scripting.speech_system.SpeechSystem object at 0x1097e6c20>>
   30:       lib/python3.9/threading.py:912* # cron thread
   29:       lib/python3.9/threading.py:954* 
   28:       lib/python3.9/threading.py:892* 
   27:                    talon/cron.py:155| 
   26:                    talon/cron.py:106| 
   25:                     talon/vad.py:21 | 
   24: talon/scripting/speech_system.py:331| 
   23:             talon/engines/w2l.py:931| 
   22:      talon/scripting/dispatch.py:105| 
   21:      talon/scripting/dispatch.py:144| 
   20:      talon/scripting/dispatch.py:133| 
   19:          talon/scripting/rctx.py:233| # 'phrase' main:_redispatch()
   18: talon/scripting/speech_system.py:61 | 
   17:      talon/scripting/dispatch.py:105| 
   16:      talon/scripting/dispatch.py:144| 
   15:      talon/scripting/dispatch.py:133| 
   14: ------------------------------------# cron thread
   13:          talon/scripting/rctx.py:233| # 'phrase' main:engine_event()
   12: talon/scripting/speech_system.py:382| 
   11:       talon/scripting/actions.py:75 | 
   10:         talon/scripting/types.py:366| 
    9:     talon/scripting/core/core.py:100| 
    8:       talon/scripting/actions.py:75 | 
    7:         talon/scripting/types.py:366| 
    6:     talon/scripting/core/core.py:131| 
    5:       talon/scripting/actions.py:75 | 
    4:         talon/scripting/types.py:366| 
    3:     talon/scripting/core/core.py:136| 
    2:  talon/scripting/talon_script.py:691| 
    1:  talon/scripting/talon_script.py:594| 
talon.scripting.talon_script.TalonScriptError: 
 in script at /Users/{user}/.talon/user/knausj_talon/misc/formatters.talon:6:
 > user.insert_many(format_text_list)
 InvalidKeyErr: ̶

```

**Comment by xavier630** [comment]
Talon Version: ![image](https://user-images.githubusercontent.com/9077250/127855154-86bc0c4c-9910-4739-a4f4-f87493dd37f3.png)

**Comment by lunixbochs** [comment]
On Mac, our primary method of text insertion is pressing keys on a virtual keyboard. We can't insert characters that your keyboard layout can't also represent. You should use `user.paste()` for gnarly unicode text on Mac for now.

**Comment by xavier630** [comment]
Okay, makes sense, I'll try that, thanks. 

It could be worth it to catch the exception and throw it again with this explanation for others encountering this issue.

**Comment by xavier630** [comment]
It works with `user.paste()` but this has the side effect of polluting one's clipboard history pretty heavily with terms that haven't been copied. As such I'd say that we should probably aim to swap to a better insertion method in the long run.

**Comment by lunixbochs** [comment]
user.paste reverts your text clipboard after pasting

**Comment by xavier630** [comment]
To be clearer about what I meant: it adds a lot of terms to one's clipboard history (when using a clipboard manager like Alfred).

**Comment by xavier630** [comment]
^ I can paste some screenshots tomorrow if helpful

**Comment by lunixbochs** [comment]
I know what you mean. There's just not a convenient and reliable way to insert Unicode without the clipboard on Mac.

We can attach Unicode characters to key events, but those events are less reliable and go through a different simulation layer than the ideal one. Using a different sim layer means we need to send the entire sequence with that layer so the events are correctly ordered. Not every app will accept those events correctly, and not every app accepts the Unicode annotation on those events.

We can use an IME, which is very powerful (it can directly manipulate text without keystrokes) but it's not supported in every app, and requires a lot of Mac specific work.

We can use accessibility, which has even worse support than IMEs, and even when it is supported, the ability to non destructively insert text is app specific.

**Comment by lunixbochs** [comment]
this is fixed in the latest beta
