### ISSUE TITLE
windows - alternate screen taskbar icon does not show sleep/wake mode changes

### ISSUE THREAD

**Issue by codecat555** [talonvoice/talon#373]
On a windows system with multiple screens:
1. Open the talon console, verify talon is listening and the taskbar icon shows the correct status.
2. Move the console window to an alternate screen and observe the talon icon in the task bar on that screen.
3. Put talon to sleep.
4. Observe the talon icon on the main screen changes to reflect the new status.
5. Observe the talon icon on the alternate screen does NOT reflect a new status (but it should).

**Comment by lunixbochs** [comment]
talon console is deprecated, it's slower than normal talon
as far as I know there is no system tray on alternate monitors on windows
