### ISSUE TITLE
[Mac] Eyetracking control mouse and zoom mouse are not checked by voice command in UI

### ISSUE THREAD

**Issue by ViacheslavKudinov** [talonvoice/talon#378]
When control mouse and zoom mouse are set via voice commands there is no checked sign in menu that it is activated.
When to set it by mouse all is fine. 
**MacOS Catalina
Talon 0.2.0 (free version)**

**Comment by lunixbochs** [comment]
This is fixed in 0.3.x, but you should also migrate to the new tracking actions (either update to latest knausj_talon, or `actions.list("tracking")` and port commands on your own)
