### ISSUE TITLE
Control "usable" region of a large (>27") monitor with a single eye tracker

### ISSUE THREAD

**Issue by nickvisut** [talonvoice/talon#38]
### Background
According to Tobii, their 4C tracker does not support "large" monitors. Details below:

> Q: What is the maximum screen size it works with?
> A: For Tobii Eye Tracker 4C, the maximum screen sizes are:
>
> 27 inches with a 16:9 Aspect Ratio
> 30 inches with a 21:9 Aspect Ratio

Anecdotal evidence seems to indicate that a 24" monitor works fine, but that accuracy in the corners of the screen begin to become hit or miss above that.

### Feature request/suggestion
One possible solution is to use multiple eye trackers, but this would require nontrivial complexity, not to mention additional hardware cost. This other approach is discussed in #39.

Another (interim?) solution, and the topic of this feature request,  is to use a *single eye tracker*, but limit Talon's eye calibration and mouse cursor control to a (presumably rectangular?) "usable" portion of the screen. For example, the calibration could be limited to the bottom (and centered) two thirds of a 40" monitor. This could either be user-specified and/or ascertained through the calibration wizard*.

*Note from author:
> @lunixbochs: I can probably make it possible to calibrate "only the usable area"
by making a slowly expanding calibration area starting at the sensor

**Comment by lunixbochs** [comment]
In Talon 0.3 with the new Control Mouse mode, and the new 27" subset calibration, I've successfully calibrated and used an entire 38" Ultrawide monitor with a Tobii 5 with 21clicks (the whole monitor was moderately usable, not just the 27" subset). I'm going to call this issue complete.
