### ISSUE TITLE
[mac] repositioning the dock causes issues with window positioning

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#381]
Version: 0.2.0-45-ge13e, Branch: pro, OS: macOS-11.5.2-x86_64-i386-64bit

The easiest repro:

dock on bottom of main monitor
Start Talon
repl => print(str(ui.screens()[0].visible_rect))
Move the dock menu to the left, right, or top of the screen
repl => print(str(ui.screens()[0].visible_rect)). Note the visible_rect is the same as in step 3.

causes issues with window snapping etc.

**Comment by knausj85** [comment]
It appears that adjusting the size of the dock also exhibits the same behavior

**Comment by lunixbochs** [comment]
Restarting talon fixes this right? Probably yet another issue with Qt screen tracking

**Comment by knausj85** [comment]
Yes, restarting talon fixes this issue

**Comment by lunixbochs** [comment]
this should be fixed in beta 0.2.0-85, please test and report any issues to the beta channel or #382
