### ISSUE TITLE
Control large (>27") monitor with multiple eye trackers

### ISSUE THREAD

**Issue by nickvisut** [talonvoice/talon#39]
### Background
According to Tobii, their 4C tracker does not support "large" monitors. Details below:

> Q: What is the maximum screen size it works with?
> A: For Tobii Eye Tracker 4C, the maximum screen sizes are:
>
> 27 inches with a 16:9 Aspect Ratio
> 30 inches with a 21:9 Aspect Ratio

Anecdotal evidence seems to indicate that a 24" monitor works fine, but that accuracy in the corners of the screen begin to become hit or miss above that.

### Feature request/suggestion
One possible solution is to use multiple eye trackers in a nonstandard configuration (e.g., one tracker placed vertically on each side of the monitor = 2 trackers, or one tracker placed horizontally at each corner = 4 trackers ... etc), and use the collective data from them to accurately ascertain where the user is looking. Potential approaches have been previously discussed in Slack chat.

**Comment by nickvisut** [comment]
> @zdwiel [7:10 AM]
@aegis has talked about using multiple devices stitched together to make I tracking on a large monitor possible

**Comment by lunixbochs** [comment]
Talon 0.3.x supports larger monitors with a single eye tracker
