### ISSUE TITLE
eye-tracker on Mac shows desktop background during mouse zoom, not foreground application

### ISSUE THREAD

**Issue by mddelk** [talonvoice/talon#391]
## issue

When using zoom mode and the config from the `knausj_talon` repo, I'm encountering an error where the focused area of a zoom is showing my desktop background, _not_ the foreground application. (**note**: my background is almost the same shade as the navbar). 

![img](https://user-images.githubusercontent.com/24943868/136597453-1991ef21-59a6-483c-816b-594917d634c6.png)

Curiously enough, the only thing I _can_ see in the zoom besides the desktop is the Talon navbar icon.

### details

OS: macOS Big Sur, v11.6
Processor:  2.6 GHz 6-Core Intel Core i7
Graphics: AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630 1536 MB

Let me know if you need more information.

### unrelated

Thanks for Talon, btw.

**Comment by lunixbochs** [comment]
This is a macOS bug, macOS doesn't always prompt the user for screen recording permissions and doesn't give Talon any indication that the permission was not granted. Instead, Talon receives a screenshot of the desktop background.

You need to go into System Preferences -> Security & Privacy -> Privacy -> Screen Recording and allow Talon to capture the screen.
