### ISSUE TITLE
libdraconity.dll fails to update if Dragon is running

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#394]
This is likely no surprise, but the failure mode is nasty for new users. I was setting up Talon on a new computer with Dragon already open. After running it for the first time, before I had configured anything, it prompted for an update. This update then failed to update libdraconity.dll but otherwise completed. 

Although this is likely unavoidable, a better failure mode would be to prompt the user to quit Dragon first before continuing (currently it retries several times and then gives up).

**Comment by lunixbochs** [comment]
Known issue, I just have a policy to not do any breaking updates to libdraconity, if there's ever a reason to update it I tell users how to do that.
