### ISSUE TITLE
Problem with fonts

### ISSUE THREAD

**Issue by alvitawa** [talonvoice/talon#395]
I can't fix this without knowing what is in textarea.py, am I missing some fonts?
  
    2021-10-16 13:12:02 ERROR user.knausj_talon.talon_draft_window.draft_talon_helpers (/home/ook/.talon/user/knausj_talon/talon_draft_window/draft_talon_helpers.py) import failed
       18:                                  lib/python3.9/threading.py:930* # loader thread
       17:                                  lib/python3.9/threading.py:973* 
       16:                                  lib/python3.9/threading.py:910* 
       15:                                     app/resources/loader.py:787| 
       14:                                     app/resources/loader.py:723| 
       13:                                     app/resources/loader.py:551| 
       12:                                     app/resources/loader.py:587| 
       11:                                     app/resources/loader.py:639| 
       10:                                     app/resources/loader.py:413| # [stack splice]
        9:                         lib/python3.9/importlib/__init__.py:127| 
        8:                                     app/resources/loader.py:243| 
        7:                                     app/resources/loader.py:238| 
        6: user/knausj_talon/talon_draft_window/draft_talon_helpers.py:48 | draft_manager = DraftManager()
        5:            user/knausj_talon/talon_draft_window/draft_ui.py:70 | self.area = TextArea()
        4:                              talon/experimental/textarea.py:748| 
        3:                              talon/experimental/textarea.py:479| 
        2:                                          talon/skia/font.py:79 | 
        1:                                      talon/skia/typeface.py:46 | 
    RuntimeError: Failed to load typeface

The help dialogues from knausj_talon are very small and don't have any text on them, rendering then useless.

I'm on arch with i3

**Comment by lunixbochs** [comment]
This is coming from Skia, it's trying to load a generic monospace font.

`strace -ff -eopenat,stat ./run.sh` and see what path Talon tries to access when you open one of those windows.

Chances are I should ship permissively licensed fallback fonts on Linux.

**Comment by alvitawa** [comment]
Here are the relevant traces (note: the error happens once at startup, not every time I open a window):

https://pastebin.com/R54DVrZW

Installing another random font (noto-fonts) doesn't fix it

**Comment by lunixbochs** [comment]
If I'm reading that right, Skia is possibly choosing a mathjax font? Is it any different if you open command history first vs opening draft window first?

Can you try running tracing Chromium in a similar way and see which fonts it reads / uses? Talon's rendering library in question is Skia, the same thing as Chrome.

I know we have users using Arch just fine, so I also asked on Slack to see if they can chime in.

**Comment by alvitawa** [comment]
Thanks for the help, for chrome it's pretty much the same: https://pastebin.com/DskpXydW

(chrome works fine)

**Comment by alvitawa** [comment]
*I mean chromium

**Comment by lunixbochs** [comment]
can you also post a trace of the non-textarea case? e.g. command history

**Comment by lunixbochs** [comment]
Here's a trace of ubuntu working, in the command history sense: https://gist.github.com/lunixbochs/a72e9ddb240987f2ab2eb5e348fe8522

So we clearly find and load a ttf font. My guess is Chromium has some kind of fallback font embedded in the app.

What does `find /usr/share/fonts` look like for you?

**Comment by lunixbochs** [comment]
Might be worth checking which font chrome actually ends up using:

https://www.businessinsider.com/how-to-change-font-in-google-chrome

https://unix.stackexchange.com/q/279342

**Comment by alvitawa** [comment]
All right, I fixed it. That trace you provided appeared to be loading the dejavu font, so I installed `ttf-dejavu` and it all works fine now. I thought maybe skia only knows how to load fonts stored as ttf, but apparently I also have the 'liberation' font as ttf, which doesn't get loaded.

```

ook@archT7:/usr/share/fonts$ find . -name "*.ttf"
./TTF/DejaVuSansCondensed-BoldOblique.ttf
./TTF/DejaVuSans-ExtraLight.ttf
./TTF/DejaVuSansCondensed-Bold.ttf
./TTF/DejaVuSerif.ttf
./TTF/DejaVuSansMono.ttf
./TTF/DejaVuSerifCondensed.ttf
./TTF/DejaVuSansCondensed-Oblique.ttf
./TTF/DejaVuSansMono-BoldOblique.ttf
./TTF/DejaVuSerifCondensed-Bold.ttf
./TTF/DejaVuSans-Bold.ttf
./TTF/DejaVuSerif-BoldItalic.ttf
./TTF/DejaVuSerifCondensed-BoldItalic.ttf
./TTF/DejaVuSerif-Italic.ttf
./TTF/DejaVuSansMono-Bold.ttf
./TTF/DejaVuSans-BoldOblique.ttf
./TTF/DejaVuSans-Oblique.ttf
./TTF/DejaVuSans.ttf
./TTF/DejaVuMathTeXGyre.ttf
./TTF/DejaVuSansCondensed.ttf
./TTF/DejaVuSansMono-Oblique.ttf
./TTF/DejaVuSerifCondensed-Italic.ttf
./TTF/DejaVuSerif-Bold.ttf
./liberation/LiberationSans-Italic.ttf
./liberation/LiberationMono-Bold.ttf
./liberation/LiberationMono-Italic.ttf
./liberation/LiberationSans-Regular.ttf
./liberation/LiberationMono-BoldItalic.ttf
./liberation/LiberationSerif-BoldItalic.ttf
./liberation/LiberationSerif-Italic.ttf
./liberation/LiberationSans-Bold.ttf
./liberation/LiberationMono-Regular.ttf
./liberation/LiberationSerif-Regular.ttf
./liberation/LiberationSerif-Bold.ttf
./liberation/LiberationSans-BoldItalic.ttf
```
Thanks!

**Comment by lunixbochs** [comment]
Can you help me see which font Chrome is falling back to on your system without DejaVu so I can look into how they fix this in the general sense?

**Comment by alvitawa** [comment]
Chrome and firefox both seem to load all of my fonts without issue: https://i.imgur.com/ckHwcQx.png

**Comment by alvitawa** [comment]
I guess they have an alternative method to try and load fonts after skia failed. The default selection is 'Custom'. I am not sure what that is, and once I select something else I cannot set tit back to 'Custom'. https://i.imgur.com/MH4XvR3.png

**Comment by lunixbochs** [comment]
Alright. I'll leave this open until I figure out how Chrome's fallback works.

**Comment by alvitawa** [comment]
Note that the error happens only once at startup, not every time I open a window. The trace for command history (in the broken state) is the same as for other windows and shows no issues: https://pastebin.com/eKTREDRw

**Comment by lunixbochs** [comment]
Duplicating to #404
