### ISSUE TITLE
Talon update will fail on windows if permissions are changed on the talon directory but not the files inside

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#396]
I saw this manifest as an update that failed to copy files. The update window contained:
```
[+] Extracting files...
 C:\Program Files\Talon\EULA.txt
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
 [?] retry...
```

... and then ultimately failed to copy all files. We aren't sure exactly why my permissions were wrong, or why they were fixed in my third (and successful) update attempt, but it may have been associated with my early copying of a custom DLL into the Talon Program Files directory.

**Comment by lunixbochs** [comment]
Fixed for the common case in next beta, by always invoking UAC if Talon is installed under Program Files.
