### ISSUE TITLE
Scripting -> View Log, or Scripting -> Console opens the bin/repl or bin/tail.log

### ISSUE THREAD

**Issue by michaelpog** [talonvoice/talon#398]
When navigating to Scripting and clicking on either View Log or Console, the bin/repl or bin/tail.log files open for edit instead of running in a terminal.
Version: v0.2.0-107-g1a2e (107)
MacOS BigSure 11.6

When running the files manually in the terminal they run just fine.

**Comment by lunixbochs** [comment]
In the rust beta, View Log is provided natively by Talon. I plan to do the same for the REPL, at which point I'll close this.

**Comment by lunixbochs** [comment]
this should be fixed in latest beta
