### ISSUE TITLE
Feature request: make word timing information available for all captures

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#401]
My use case is to support a command like `select <onscreen_phrase> through <onscreen_phrase>`  using eye tracking and OCR  to find the provided words. To do this accurately, I need to know the timing (preferably the start times) of start_phrase and end_phrase.  This is doable today using `<phrase>`, but I'd like to define a custom capture (specifically: `<user.word> | <number>`) so I can include custom vocabulary and numbers without having to parse them myself (or redefine all the captures this depends on to returns tuples with timing info). This seems like a generally useful feature: preserve and forward capture timing metadata (and maybe other metadata later, e.g. volume) for use in actions.

I'm open to whatever API makes the most sense and is easiest to implement, but here are some ideas:
* Using `<number>` as an example:  could add m.number_meta variant to expose this sort of information, with subfields like start_time and end_time. This aligns with the current *_list style variants available.
* In addition to exposing information about nested captures, it would also help to have information about the current capture. That way, if I'm creating a @mod.capture for `select <onscreen_phrase> through <onscreen_phrase>`, I could access the start time of the overall phrase (of "select" in this case) if needed without having to define yet another capture to wrap this. Perhaps this could be done with m.meta (acknowledging the potential for conflicts).
* Consider exposing this information to the talon files as well so that one need not return the metadata from a @mod.capture to make use of it. That way, in my talon file I could do something like `user.select_words(onscreen_phrase1, onscreen_phrase1_meta.start, ...)`  instead of having to bundle this information into the return value of the onscreen_phrase capture. This feature could potentially also be combined with the previous bullet, so that someone could have a simple command like "click word" in their .talon file and use the start time of "click", all without needing to define a new capture.
* We may not need any numerically indexed metadata if the above is done. Suppose the user had a command "click on this word" and wanted to know the timing of "this". They could simply define "this" as a capture and they'd now have start/end data available for that word, without reliance on brittle indexing techniques (i.e. `words[2]`).

**Comment by wolfmanstout** [comment]
Is it expected that in a capture with `rule="literal {user.punctuation}"` I can get `m._words[0].start` but not `m._words[1].start`? The latter fails due with `AttributeError: 'str' object has no attribute 'start'`. The problem isn't index 0 vs. 1 but rather literal vs. list. I was looking to see if I could manually forward start/end times through my captures where needed, but since lists are a basic building block of captures, this seems to prevent me from doing that. The only workaround I'm aware of is to manually expand the list into alternatives, e.g. `(element1|element2|...)` and perform manual lookups to get the dict values, which I'm hoping to avoid. 

I'm hoping this is a simpler request than the above, but maybe it's the same thing under the hood.

**Comment by lunixbochs** [comment]
The problem with lists here is they're all implemented as key/value internally, and commands only see the value, which does not have timing information.

**Comment by wolfmanstout** [comment]
Got it. And just to be clear it would help even if this is only available in a custom capture that uses a list (vs a command), via the match object. In my example in the previous comment I'm going through m._words, not m.list.

**Comment by pokey** [comment]
From 

```python
def on_phrase(j):
    ...


speech_system.register("pre:phrase", on_phrase)
```

I'd like to be able to get timing info for the captures and subcaptures of `j["parsed"]`, eg something like `j["parsed"][0][0].start` and `j["parsed"][0][0].end`, as well as timing information for subcaptures of these captures.

I'd like to use this information for demo videos.  I want to automatically highlight cursorless hats as I say them in the video

**Comment by lunixbochs** [comment]
update on this, lists propagate timing now, for captures you still need to propagate timing yourself

**Comment by wolfmanstout** [comment]
Per our conversation, I want to clarify the minimal requirements that would enable me to dramatically improve how I deal with timing in talon-gaze-ocr. All I actually need is to be able to request the start and end time of the entire capture within a mod.capture definition. If I had that, I could easily create a timestamped_prose capture with `rule="<user.prose>"` and then return this via my own wrapper type for use in talon-gaze-ocr. As it stands, I already have such a wrapper type already (TimestampedText with start/end times), but my timestamped_prose capture is created by rebuilding the <user.prose> hierarchy from the bottom up -- or more accurately, a subset of it (I wish it were complete).

You mentioned that one way to achieve this would be if Talon automatically wrapped/unwrapped this information such that user-facing APIs are unchanged (with the exception of this additional bit of metadata that's explicitly set).
