### ISSUE TITLE
feature request: allow mimic() to work with momentary commands & word timings

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#410]
It's currently impossible to use `speech_system._on_audio_frame` or word-timing together with mimic()ed voice commands. This means, for example, it isn't possible to use mimic() to run momentary commands or similar. I ran into this while trying to debug something with talon in sleep mode; I used mimic() to run a momentary command but of course it failed.

Two solutions here:

1. Produce fake `current_phrase["samples"]` and fake word timings on mimic()ed commands. The data here obviously couldn't be real audio data or times, but it could be fake: eg, the samples could simply be a list of words, and the timings could be indices into this list. This would complicate `_on_audio_frame` because it would need to tell whether its input was a list of audio samples or of words, but would otherwise be transparent to most existing code, I imagine.

2. Have a more direct API for the use-case of rerunning part of a phrase. This seems desirable long-term.

**Comment by lunixbochs** [comment]
I don't think I'm going to do either of these directly, the closest thing will be allowing a context, mode, or switch mid-phrase.
