### ISSUE TITLE
"modifier-key" behaves differently from "modifier:down key modifier:up" in Chrome

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#420]
In Chrome, the default "alt-left" for back will move keyboard focus out of the main window and onto the toolbar (specifically, the three dots menu). Consequently, keyboard shortcuts that act within the active page will no longer work until focus is moved back. This problem does not occur if "alt:down left alt:up" is used. With a physical keyboard, these are equivalent, so it seems that they ought to work the same for simulated key presses.

**Comment by lunixbochs** [comment]
Is this on Windows?

**Comment by wolfmanstout** [comment]
Correct, sorry should've specified. Windows 11, specifically.

**Comment by wolfmanstout** [comment]
Correction, I've also observed it in Windows 10.

**Comment by timo95** [comment]
I have the same problem in Element Chat (electron app) on Windows 10. `alt-down` works to switch between channels, but also activates the menu bar. `alt:down down alt:up` does not show the menu bar. On Linux it works with both.

**Comment by wolfmanstout** [comment]
Seeing this also in Chrome using Google Docs. Ctrl-alt-m to add comment doesn't work except with the above workaround (even though I don't see focus moving to the toolbar).

**Comment by lunixbochs** [comment]
I think this is fixed in beta 0.2.0-201, can you confirm whether the docs hotkey works there? I might need to go one step further with the fix if not.

**Comment by wolfmanstout** [comment]
Looks like everything is working for me, thank you!
