### ISSUE TITLE
Feature request: Add more browser url scopes

### ISSUE THREAD

**Issue by timo95** [talonvoice/talon#424]
I often have to edit the query part of the url. Currently I have to do something like this to get the current query:
```
query = scope.get("browser.url").partition("?")[2].partition("#")[0]
```

`query` and `fragment` would also be useful in context matching to limit commands to specific parts of websites.

**Comment by lunixbochs** [comment]
I've been generally recommending folks don't use `scope.get()` besides debugging. Try this:

```
from urllib.parse import urlparse
urlparse(actions.browser.address())
```

**Comment by lunixbochs** [comment]
added query/fragment to browser scope in rust beta
