### ISSUE TITLE
Talon Log Viewer frequently reloads the log

### ISSUE THREAD

**Issue by codecat555** [talonvoice/talon#430]
I recently switched from the Talon Console to the Talon Log Viewer, keeping a window open on one screen all the time. I've found that, for some reason, the log viewer window spontaneously reloads the log file - the window content briefly clears and then starts scrolling like mad as it reads through the stored log. This has been happening multiple times per hour.

Running on windows 10.
My log file is currently 43mb.
Talon version v0.2.0-160-g6bfd (160)

Note that I am writing debug statements to the log while debugging - running commands, modifying and saving talon user directory files. The overall volume of debug output is not particularly large, I don't think...but I suppose it could have something to do with this behavior.

**Comment by lunixbochs** [comment]
the latest beta has a native log viewer which loads instantly and never needs to reload the log
