### ISSUE TITLE
Talon can't be used with UAC

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#437]
Neither key presses nor zoom mouse works to pass "User Account Control" on windows 10.

**Comment by lunixbochs** [comment]
Disable the secure desktop (UAC dims the screen) and it should work if Talon is in program files.

For Talon to type into the secure desktop directly, I would need to ship a service running as SYSTEM.

**Comment by AndreasArvidsson** [comment]
Thank you! This was driving me nuts. 
This together with that double space for period on mac should really be in a "operating system quirks for talon" :D
