### ISSUE TITLE
insert() handles backtick and other diacritic incorrect with Swedish keyboard

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#441]
On a Swedish keyboard when you press the backtick key nothing happens, then when you press the second key that symbol will get the accent. Space is used to get the single backtick character.
\`+ a => à
\`+ space => \`
This is of course really irritating and I have taken steps in my talon code to insert these symbols correctly. The larger problem is if you want to insert an actual text containing a backtick. Then talon will get the result incorrect.

test: "aà`a" => aàà

This is my solution right now
```
@ctx.action_class("main")
class MainActions:
    def key(key: str):
        actions.next(key)
        if key in requires_space:
            actions.next(" ")
```

**Comment by lunixbochs** [comment]
Which OS?

**Comment by AndreasArvidsson** [comment]
windows 10

**Comment by lunixbochs** [comment]
fixed in latest beta
