### ISSUE TITLE
Error in `Action.__doc__` for some actions

### ISSUE THREAD

**Issue by wenkokke** [talonvoice/talon#443]
The following code, together with knausj master...
```python
from talon import Module, actions

mod = Module()

@mod.action_class
class BugReport:
  def trigger_bug():
    """Trigger a bug"""
    print(actions.edit.line_swap_down.__doc__)
```

... triggers the following error...

> NotImplementedError: Action 'edit.line_swap_down' exists but the Module method is empty and no Context reimplements it

...rather than returning the documentation.

**Comment by lunixbochs** [comment]
fixed in 0.2.0-232
