### ISSUE TITLE
Allow lists in .talon files

### ISSUE THREAD

**Issue by xavier630** [talonvoice/talon#449]
This is a feature request to allow arrays/lists in `.talon` files, for example, as a parameter to an action.

Current workarounds involve using strings to represent lists and converting those to lists within Python files. While this works, it would probably make more sense to me to be able to pass lists straight into actions.

**Comment by lunixbochs** [comment]
Can you provide some specific example use cases for this and the corresponding actions / TalonScript code?

**Comment by xavier630** [comment]
One example I had recently was:
```
open tabs:
    user.open_list_of_sites([
        'xyz',
        'abc'
    ])
```

With `open_list_of_sites` being an action that takes a list of sites to open and opens them. Let me know if more details would be helpful.

**Comment by xavier630** [comment]
Another workaround is to put the lists/constants into Python files

**Comment by lunixbochs** [comment]
What are you using right now?

Here's an exploration of possible options. I think my preferred option (as I mentioned in slack) is still "string split".

### Syntax comparisons:

individual calls:
```
open tabs:
    user.open_site("http://example.com")
    user.open_site("http://google.com")
```

named setting:
```
settings():
    user.sites = ["..."]

open tabs:
    user.open_list_of_sites(settings.user.sites)
```

named list:
```
# user/sites.talon-list
http://example.com
http://google.com

# user/sites.talon
open tabs:
    user.open_list_of_sites(lists.user.sites)
```

multiline string:
```
open tabs:
    user.open_list_of_sites("""
        http://example.com
        http://google.com
    """)
```

string split:
```
open tabs:
    sites = strings.splitlines("""
        http://example.com
        http://google.com
    """)
    user.open_list_of_sites(sites)
```

list:
```
open tabs:
    user.open_list_of_sites([
        "http://example.com",
        "http://google.com",
    ])
```

varargs:
```
open tabs:
    user.open_list_of_sites(
        "http://example.com",
        "http://google.com",
    )
```

out of line list:
```
open tabs:
    sites = [
        "http://example.com",
        "http://google.com",
    ]
    user.open_list_of_sites(sites)
```

out of line JSON:
```
open tabs:
    sites = user.json_parse("""
        ["http://example.com", "http://google.com"]
    """)
    user.open_list_of_sites(sites)
```

out of line YAML:
```
open tabs:
    sites = user.yaml_parse("""
    - http://example.com
    - http://google.com
    """)
    user.open_list_of_sites(sites)
```

**Comment by xavier630** [comment]
I'm using the "multiline string" right now. I think an actual list would be cleaner since it saves a conversion step by passing in the actual type the function needs.

If a list will not come in the near future, I might switch to the "string split" approach so I can decouple my list handling from my implementation.

Thanks for providing all of the options/potential options.

**Comment by lunixbochs** [comment]
My biggest consideration with .talon files is reducing the overall syntax, and when we do add syntax, limiting the number of new failure points. That's why I'm reluctant to add more primitive types.

List of strings strikes me as something with complex syntax and a lot of failure points: `[]` (2) to start, `"",` (+3) for each item

**Comment by rntz** [comment]
Syntax sketch from knausj grooming session:

```
list: user.git_arguments # complain if not at top? only one possible.
language: en
os: linux
-
abort: --abort
all: --all
two options: --two --options
leading whitespace: " --leading-whitespace"
trailing whitespace: "--trailing-whitespace "

foo:bar:baz:quux
# same as:
foo: "bar:baz:quux"

no escapes sans quotes: hello\n\texample
# same as:
no escapes sans quotes: "hello\\n\\texample"

newlines okay:
    "newlines are okay"

block o stuff:
    # block strings same semantics as talonscript, same as python (but no interpolation)
    """
    block
    o
    stuff
    """

# bare block strings yes or no?
bare block strings:
    hello
    # comment
    more
    stuff
# --> "hello\n# comment\nmore\nstuff"

bare block strings with varying indentation do what:
    hello
        more

    stuff
# --> "hello\n    more\n\nstuff"

escapes: "are\nokay"
"foo:bar": --asdf

# no.
#gamepad(foo): "whee"

# comments allowed
# bare lines ok
HEAD
# same as:
HEAD: "HEAD"
main
master
mine
origin
upstream

weird example:
    foo
# unindented comment
    baz

# .talon-capture???? NOT YET.
numeral <user.number_string>: "{number_string}"
[numeral] <user.number_string> (dot | point) <digit_string>: "{number_string}.{digit_string}"
numeral <user.number_string> colon <user.number_string>: "{number_string_1}:{number_string_2}"

<user.prose_simple_number>: "{prose_simple_number}"
<user.prose_number_with_dot>: "{prose_number_with_dot}"
<prose_number_with_colon>: "{user.prose_number_with_colon}"
<user.prose_simple_number> | <user.prose_number_with_dot> | <user.prose_number_with_colon>:
    "{prose_simple_number or prose_number_with_dot or prose_number_with_colon}" # ???
```

**Comment by lunixbochs** [comment]
Just released this to the Talon Rust beta.

**Comment by AndreasArvidsson** [comment]
@lunixbochs When I try to add a talon list I get this warning in the log. 
`2023-03-05 10:26:27 WARNING Skipping unknown tag in list "extra"`
Looks like this only happens if the first line after the dash is empty and for the record the list name is not "extra".

**Comment by rntz** [comment]
I've just realised this is not the issue i thought it was when i added my comment. Oops! Is there a way to transfer comments from one issue to another?

**Comment by lunixbochs** [comment]
this is in the beta, shipping in 0.4
