### ISSUE TITLE
Clean up and document 'tap' API

### ISSUE THREAD

**Issue by lkjh654** [talonvoice/talon#45]
The tap documentation API is missing

Moreover please consider the following improvements discussed on [slack](https://talonvoice.slack.com/archives/C9MHQ4AGP/p1528359937000041)

- API to trap key events - `ctrl:down:prevent` syntax when binding a hotkey
- Clear the modifier flags before doing this action `with ctrl.modifiers(None || 'alt' || 'ctrl-shift'): ...`

**Comment by lunixbochs** [comment]
tap can't be supported cross-platform or without input stalls
