### ISSUE TITLE
Utterances may be dropped after a context switch

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#450]
After using voice to alt-tab between apps, I've noticed that the first command I speak may be dropped if I don't wait a moment. I'm only able to reproduce this on my slower work computer, although it's pretty consistent there. I'm not sure whether this is something that is fixable or not, although I never noticed this before with NatLink, so I figured it was worth logging. After testing this many times (in Dragon's command mode) and looking at Dragon's recognition history, there are few different failure modes:
- Dragon correctly recognizes the command, hands off to Talon, which then logs "talon.engines.EngineError: failed to parse phrase"
- Dragon parses the command as something similar within Dragon's own grammar, e.g. "tab nine" instead of "tab new". Talon is not notified.
- Dragon fails to parse the command (shows as "<???>"). Talon is not notified.

**Comment by lunixbochs** [comment]
fixed in 0.2.0-257
