### ISSUE TITLE
user.paste silently fails on Windows

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#452]
Version: 0.2.0-232-gf0fa, Branch: beta, OS: Windows-10-10.0.19043

Unfortunately, I don't know when this popped up. I think it's probably worth reporting though.
https://github.com/knausj85/knausj_talon/blob/master/code/edit.py#L24

I used to see these sorts of errors (from QT https://github.com/talonvoice/talon/issues/258#issuecomment-883916527) when it stopped working:
`OleSetClipboard: Failed to set mime data (text/plain) on clipboard: COM error 0xffffffff800401d0  (Unknown error 0x0800401d0) (The parameter is incorrect.)`

**Comment by lunixbochs** [comment]
can you try -206? I changed the platform builds a bit in the release after that.

**Comment by knausj85** [comment]
The error appears on version 206

**Comment by lunixbochs** [comment]
can you clarify "silently fails", do you mean you get "Failed to set mime data" on version 206 and no error on 232, but it fails in both cases?

**Comment by knausj85** [comment]
There’s no error on 232 on my end; the mime data error appears on 206
