### ISSUE TITLE
Talon sometimes prefers old Conformer despite my selection

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#453]
I've observed this on my work computer, where I default to Dragon. I have chosen the newest Conformer few times, but I have seen it switch to the old Conformer, e.g. when Dragon is not available.

I'll try to remember to update this next time it happens so I can provide more detailed report.

**Comment by lunixbochs** [comment]
I don't think this will happen unless you've manually added a conformer model, I also have fixed a couple of engine loading issues since this was filed.
