### ISSUE TITLE
Commands with capital letters don't work in Dragon

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#460]
Here is a simple grammar to reproduce this:
```
I can: insert("success")
```

This works in Conformer but not Dragon (on Windows, DPI 15). If the "I" is changed to "i" it works in both. From a little debugging I did, this appears to be a Talon issue, not a Draconity issue. Draconity is reporting a match either way, with the only difference that the phrase reported is "I can" vs. "i can", depending on which variant is used.

**Comment by wolfmanstout** [comment]
The matching priority inconsistency I mentioned today is related to Dragon capitalization handling, so it's plausible that it could also be fixed by your fix. Hence I'm reporting here, but let me know and I can create a new issue:

Consider this grammar:
```
test priority i move: insert("literal")
test priority <phrase> move: insert("phrase")
```

Note that I'm using lowercase "i" instead of "I" as a workaround to the bug reported here.

What I see is that Conformer consistently prefers the literal variant when speaking "test priority I move". Dragon is inconsistent: at home it behaves the same as Conformer, but on my work computer with Dragon, it prefers the phrase variant. Notably, if I check the command history, preference for the phrase variant coincides with "test priority I move" instead of "test priority i move". In other words, Dragon responds differently on my two computers (in one case returning "i", the other "I"), and when it returns "I" then Talon prefers the match to phrase instead of the literal "i". Seems like this preference should be case-insensitive?

All the above is unchanged even if this grammar is the only thing in my user folder.

**Comment by lunixbochs** [comment]
I believe the fix for this already went out in beta

**Comment by wolfmanstout** [comment]
I'm using Conformer these days, but I went ahead and tested this with Dragon with the simple grammar in my first post and it still doesn't work with Dragon unless I change "I" to "i". This is on version 437, and I checked the timestamp on libdraconity.dll and it looks up to date.

**Comment by lunixbochs** [comment]
with Dragon, what happens if you `mimic()` vs `speech_system.engine_mimic()` vs say each of the test phrases?

**Comment by wolfmanstout** [comment]
Both of those work.

**Comment by lunixbochs** [comment]
Ok, that's weird, I sent you something on Slack to try.

**Comment by wolfmanstout** [comment]
Based on your suggested logging, it looks like Dragon isn't sending the phrase over to Talon, so there's nothing Talon can do here. Not sure why that would have changed from my initial report, but I suppose this is now a "Can't fix" bug.

**Comment by lunixbochs** [comment]
I think this is a Dragon bug, use Conformer
