### ISSUE TITLE
Feature request: expose action to control Dragon microphone

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#461]
Draconity already responds to a "mic.set_state" cmd, but (as far as I know) this is not exposed as an action through Talon. I'm guessing it would be cleaner to do so via Talon's connection versus sending a bson message through an independent TCP connection via a user action.

My use case is fully disabling the Dragon microphone via Talon commands and keybindings. Currently knausj only does mic sleep and it does so via mimic.

**Comment by lunixbochs** [comment]
I haven't found that api particularly reliable, I believe it can even crash Dragon. Probably just use the dragon microphone toggle hotkey, or find another way.
