### ISSUE TITLE
Linux cv2 downloader not triggered when using updater

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#469]
Around -293 the `cv2` package was removed from the default Talon distribution. To provide backward compatibility the system would automatically download and install the `cv2` package to ~/.talon/.venv/ when it was first imported. This automatic download function breaks under the following conditions on Fedora Linux:

1. Stop Talon.
2. Remove or just move your ~/.talon/ folder. This is to reset the .venv directory to what a user upgrading from -259 would have.
3. Download -259 and run it. When the updater popup appears start the download.
4. After Talon downloads and updates itself open the REPL and run the following: `import cv2;dir(cv2)`. You won't see the expected list of functions and will just get the basic module methods. This means your cv2 module is registered, but doesn't have the right contents.

Manually downloading and running a later version of the beta fixes the issue.

**Comment by lunixbochs** [comment]
fix will be released in next beta, note that it's an updater issue so (for now) anyone affected will either need to update twice or manually reinstall
