### ISSUE TITLE
Intermittent failures in 'win_move' callback after rect assignment

### ISSUE THREAD

**Issue by codecat555** [talonvoice/talon#470]
Talon sometimes fails to call registered 'win_move' callback after rect assignment.

Windows 10.

Talon version v0.2.0-305-g968a (305).

I reproduced the problem while running stock knausj @4a34cf0b2c8d8c39a2ed2b3369be65e1cd5bc0aa, and nothing else in my user folder.

It's not clear exactly what triggers this problem, but I found running events.tail() helps to reproduce it. In some test runs, I found that only the very first events.tail() run after starting talon was effective.

No apparent errors in talon log or event log.

**Comment by codecat555** [comment]
Note: the 'win_resize' callback is also affected.

**Comment by lunixbochs** [comment]
Can you remind me of some details, as I don't remember the slack conversation perfectly and it seems like not all of the info made it here?

1. The window does move, the callback just isn't called?
2. Does moving the window manually (e.g. with your mouse) also not trigger the callback when this happens?
3. Does it only affect one app at a time, or all windows on your system stop emitting move/resize callbacks at once?

**Comment by codecat555** [comment]
I kept a copy of the conversation and I think it contains the answers to your questions...the formatting might not be so good though.

> ardent
> 
>   1:12 PM
> I have new information. I'll try to keep this concise while still providing complete information.Problem: talon sometimes fails to call registered 'win_move' callback after rect assignment.I reproduced the problem while running stock knausj @4a34cf0b2c8d8c39a2ed2b3369be65e1cd5bc0aa, and nothing else in my user folder.Talon version v0.2.0-305-g968a (305).I ran the windows-fun--mod.py code included below to independently monitor the EVENT_OBJECT_LOCATIONCHANGE system event. Here is the captured output (note the timestamps in the last field of each line) -
> C:\WINDOWS\system32>python C:\Users\me\Documents\Projects\Talon\win-move-timeout-debug\windows-fun--mod.py
> ((32779, 'Untitled - Notepad', 0, 0, 36676, 593843328, '2022-01-19 12:25:30'),)
> ((32779, 'Untitled - Notepad', 0, 0, 36676, 593884906, '2022-01-19 12:26:12'),)
> ((32779, 'Untitled - Notepad', 0, 0, 36676, 593902468, '2022-01-19 12:26:29'),)
> ((32779, 'Untitled - Notepad', 0, 0, 36676, 593907671, '2022-01-19 12:26:34'),)
> Talon did invoke my callback for the first instance. Then, I ran events.tail() and it did not invoke the callback within the timeout period of 0.2s for the following three instances. I also had the log viewer running, as usual.To be clear, I have seen this same behavior when not running events.tail(). I just discovered that it's a convenient way to increase the chances of catching the problem. At one point while trying to repro the problem yesterday I had three different instances of events.tail() running at the same time but could not trigger the problem at that time.Also, during these failues my cpu load was never more than 10-15% and memory usage steady at 33%.
> 3 files 
> windows-fun--mod.py
> Python
> Click to view details
> talon-debug.log
> Plain Text
> Click to view details
> 20220119122623-events.log
> Binary
> Download Binary
> aegis
> 
>   1:59 PM
> To be clear, the window moved?
> 2:00
> Are there perhaps any errors in the talon log that are unaccounted for?
> ardent
> 
>   2:03 PM
> Yes, the problem is with the callback, not the move. Happens with win_resize too.
> ardent
> 
>   2:27 PM
> The only error in the log is from run_wslpath() and it's unrelated. It's happening because stock knausj_talon does not like my wsl window title format.
> aegis
> 
>   2:44 PM
> Do other windows get updates at this point? Do you see updates in talon for that window if you move the window manually with your mouse?
> ardent
> 
>   3:18 PM
> I haven't seen anything that indicates it's specific to the window/app. That is, I have seen it happen with many different windows/apps over the few months I've been testing rect assignment.I would have to change my code and repro the problem again to answer your second question. I guess what I would do is comment out the line that unregisters the callback so I would have time to try a manual move.Are you suggesting that perhaps windows fails to deliver the EVENT_OBJECT_LOCATIONCHANGE event in some cases? I think that's something that someone would have noticed/fixed by now. If that was the case, I would expect to see occasional failures when running the windows-fun--mod.py test code but I have seen none; I was actually running the test in a loop for a while yesterday.
> aegis
> 
>   3:27 PM
> I'm wondering if the issue is
> 	1. time based (all windows now fail to deliver the message once it happens)
> 	2. window based (that window now fails to deliver the message, but other windows are fine)
> 	3. even further, once it's happened, whether talon still sees updates caused by dragging the window manually
> ardent
> 
>   4:43 PM
> Suppose I write code to continuously move two windows using talon, one after the other, until I catch a series of timeouts. Does it matter what kind of windows I use, will two notepad.exe sessions suffice?
> aegis
> 
>   4:44 PM
> No idea 
> ardent
> 
>   5:29 PM
> Sorry, that was the wrong question.I'm willing to put some more time into this and I think that the test I proposed will help answer the questions you raised. I can't easily test 'all windows' and it seems to me that two windows should be sufficient.
> aegis
> 
>   5:32 PM
> I would suggest triggering it with only one window, then once it's triggered, at that point testing another window that hasn't been "in play"
> ardent
> 
>   5:45 PM
> Okay, working...
> aegis
> 
>   5:46 PM
> That will tell us whether we have 1 or 2 from my list
> 5:46
> At that point you can test 3
> ardent
> 
>   10:51 PM
> 	1. In a separate .py file, I registered a new test callback for 'win_move', it just prints the arg.
> 	2. Verified the new callback was working.
> 	3. Restarted talon.
> 	4. This time my move timeout was set to 0.8s, so the failures triggered the watchdog.
> 	5. Started my loop with 10 second interval between moves.
> 	6. The callback failed for the very first move this time, but that was a fluke and it succeeded in the retry.
> 	7. Let it continue to run for several more iterations and saw the callback was invoked each time.
> 	8. Started events.tail().
> 	9. The callbacks stopped working - both the "normal" callback registered by my rect assignment code AND the new 'test' callback.
> 	10. After each failure, the code moved the second window and the callback failed for these also.
> 	11. Let this run for several iterations and saw consistent results.
> 	12. After these failures, the 'new' test callback also failed when I moved the target window manually.
> 	13. My non-talon event catcher code was continuously logging events for all this activity.
> 	14. Stopped my events.tail() run and things started working again, including when manually moving the window.
> 	15. Started events.tail() up again and this time the callbacks continued to work.
> 	16. Stopped the test.
> 	17. Restarted talon.
> 	18. Restarted the test.
> 	19. Saw the same behavior with this run.
> 	20. Did it all again (steps 1-18) with similar results.
> Not sure why just the first events.tail() session after starting talon triggers the problem, but maybe it's a clue to what's going on. (edited) 
> aegis
> 
>   10:54 PM
> so, it's case 1+3? all windows fail to produce events, and manual dragging fails? (edited) 
> ardent
> 
>   11:00 PM
> Yes.
> aegis
> 
>   11:00 PM
> thanks, I think I get it. can you file an issue?
> ardent
> 
>   11:01 PM
> Yes.
> 11:02
> Do you want my test code in the issue? Logs?
> aegis
> 
>   11:02 PM
> I'll probably try to repro from the description, then ask for more info if I can't repro
> 11:07
> also please make sure to include the talon version in the issue
>

**Comment by lunixbochs** [comment]
this should be fixed in 0.4
