### ISSUE TITLE
ui.active_window().doc returns URL-encoded spaces

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#473]
When viewing a file that has spaces in it, `ui.active_window().doc` returns a path with URL-encoded spaces even though it's not a `file://` URL:

```
>>> ui.active_window().doc
'/Users/pcohen/Desktop/Test%20File.txt'
>>> ui.active_window().element.AXDocument
'file:///Users/pcohen/Desktop/Test%20File.txt'
```

<img width="870" alt="Screen Shot 2022-01-23 at 3 35 04 PM" src="https://user-images.githubusercontent.com/536668/150702771-efb65a60-6275-46a0-bc19-d1c230aca42a.png">

@nriley suggested this may be a bug.

**Comment by lunixbochs** [comment]
should be fixed in next beta

**Comment by phillco** [comment]
I noticed that `window.doc` decodes but the accessibility property doesn't. Is that intentional?

```
>>> ui.apps(bundle='com.apple.ScreenSharing')[0].windows()[0].doc
'/Users/phillco/Library/Containers/com.apple.ScreenSharing/Data/Library/Application Support/Screen Sharing/Mac Studio (phillco).vncloc'
>>> ui.apps(bundle='com.apple.ScreenSharing')[0].active_window.element.AXDocument
'file:///Users/phillco/Library/Containers/com.apple.ScreenSharing/Data/Library/Application%20Support/Screen%20Sharing/Mac%20Studio%20(phillco).vncloc'
```

**Comment by lunixbochs** [comment]
it's a CFURL/NSURL behind the scenes, this seems like correct handling of the raw attribute to me
