### ISSUE TITLE
API Method of Enabling/Disabling/Toggling Talon Features

### ISSUE THREAD

**Issue by dwighthouse** [talonvoice/talon#48]
Requesting the ability to enable, disable, and toggle each major toggleable function of Talon through scripting, so as to attach commands to them. Enabling/Disabling/Toggling each function should also update the menu items with check marks as appropriate.

Major functions include:

* Eye Tracking >> Calibrate Mouse (activate and cancel only)
* Eye Tracking >> Control Mouse
* Eye Tracking >> Show Camera Overlay
* Eye Tracking >> Show Debug Overlay

**Comment by lunixbochs** [comment]
See the new methods used by eye_control.py in 0.0.8: https://github.com/talonvoice/examples/blob/master/eye_control.py
