### ISSUE TITLE
`ui.focused_element()` sometimes returns `<NoElement>`

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#480]
Occasionally `ui.focused_element()` returns `<NoElement>`, but `ui.active_app().element.AXFocusedUIElement` does return the correct element.

This happens to me in Xcode 13.2.1 on Monterey 12.2. It also happens frequently in Messages.app, Notes.app, and TextEdit.app after restarting Talon. Generally, restarting the application, and/or cycling through several of its views (i.e. focusing different notes in Notes.app) can fix it.

Generally when this happens, `element_focused` events are also not fired.

I can work around most of this for now by implementing a general action to get the focused element, with the fallback. Although I don't think I can work around the lack of focused events.

**Comment by lunixbochs** [comment]
should be fixed in next beta, let me know if you still run into issues
