### ISSUE TITLE
Dragon should be automatically selected on load if it was your last selected engine

### ISSUE THREAD

**Issue by zmcgohan2** [talonvoice/talon#481]
Currently, Conformer is always automatically selected when Talon loads. Migrating from Dragon to Talon, this causes a user to click through the Talon menus to select Dragon if they have migrated their menu selection commands.

If Dragon was your last used speech engine, it should automatically be selected when Talon loads.

**Comment by lunixbochs** [comment]
What's the Talon version you tested this on?

**Comment by zmcgohan2** [comment]
v0.2.3

Just upgraded to beta, selected Start on Login, seems to work now (albeit with a ~15 second delay after Dragon was green). Not sure if there is an easy way to decrease the delay, but that would be my only complaint now.

Closing issue. Sorry for the miscommunication, this is not explicitly in the beta release notes but I should have upgraded first.
