### ISSUE TITLE
feature request: add filter and search to help

### ISSUE THREAD

**Issue by ykuksenko** [talonvoice/talon#484]
I would like to be able to search the help menu more easily.
Would it be possible to add a search bar to the help menus and maybe some clickable filters.

Example:
When I say `help context ` I get 7 pages of 20 items. Only some of these items are active.
1. A filter button called `active` and maybe a `not` button would be a useful to clean up the list to the active or inactive items only.
2. A search bar would also be nice to input what I am looking for instead of going through all the pages.

Thank you.

**Comment by lunixbochs** [comment]
Hi, thanks for the request! That's not a feature of the Talon app itself, it's implemented in the open-source knausj_talon repo, which has its own issue tracker here: https://github.com/knausj85/knausj_talon/issues
