### ISSUE TITLE
macOS accessibility attributes are sometimes '' instead of None

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#485]
Properties that are shown as "None" in the Accessibility Inspector are frequently reported to Python as empty strings, instead of `None`s.

For example, this is a screenshot of the inspector pointing to the iTerm console. The "selected text" properties, as well as "help" are all "None":

<img width="570" alt="Screen Shot 2022-02-14 at 7 19 55 PM" src="https://user-images.githubusercontent.com/536668/153986503-5049be23-6710-4d5a-8094-34dab9df473f.png">

But in Talon, when we print the `attrs` of that element, they are returned as `''`:

<img width="534" alt="Screen Shot 2022-02-14 at 7 20 12 PM" src="https://user-images.githubusercontent.com/536668/153986925-b9e6c97f-f02a-426c-b837-2bf91fdcc76f.png">

cc @nriley

**Comment by lunixbochs** [comment]
fixed in next beta
