### ISSUE TITLE
accessibility: extra querying options for large trees

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#486]
Some applications have massive accessibility trees (like Notes.app, which exposes every note ever created).

This can make general integrations that do things like "search for AXButtons" time out and hit watchdogs. A few extra parameters to `find()` would allow them to avoid searching too deeply. This can save us from having to write custom logic for each app.

Allow for `find()` / `find_one()` to:

- [x] Only query for elements that should be visible, based on their position.
- [x] Set a maximum search time (in seconds) and/or a maximum number of elements to visit

**Comment by lunixbochs** [comment]
done :+1:
