### ISSUE TITLE
Linux not alligning second monitor at Y=0

### ISSUE THREAD

**Issue by C-Loftus** [talonvoice/talon#488]
The screen size of both displays seem to be correct, but the alignment itself seems to be  off on the first screen.
```
can = canvas.Canvas(x=1930, y=000, width=100, height=100)
```
Although my monitor is 1920  in width,  displaying the following canvas does not show any image on either the first or second monitor.

That code goes right beyond the edge of my monitor but anything beyond that just makes it disappear and doesn't show up on the other monitor due to the y difference

Fix: Potentially show a warning on an invisible window?

```
Talon REPL | Python 3.9.9 (main, Jan 13 2022, 06:45:15) [GCC 7.5.0] on linux)
>>> ui.screens()
[Screen(x=1920, y=77, size=(1920, 1080), mm=(527.000, 296.000)), Screen(x=0, y=0, size=(1920, 1080), mm=(309.000, 173.000))]
```

OS:  Ubuntu 20.04.3 LTS
XDG_CURRENT_DESKTOP : ubuntu:GNOME
DE: GNOME 
WM: Mutter
GPU: AMD ATI 05:00.0 Picasso 

Other relevant info:  I am using the following extension for gnome  which is used to tile windows automatically https://github.com/pop-os/shell

**Comment by timo** [comment]
check the output of `xrandr` to see if the coordinates are perhaps just correct.

**Comment by C-Loftus** [comment]
I believe the coordinates are correct.  I was told by aegis in slack to log this as an issue just since he was thinking that
 if the window is totally invisible, talon could possibly move it onto the monitor, or log a warning.

xrandr output seems fine
```
HDMI-A-0 connected primary 1920x1080+1920+77 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
```

**Comment by timo** [comment]
in the xrandr output you can see that the primary screen lives at x=1920 y=77, so talon is getting the correct result, you were just expecting your screen setup to be different
