### ISSUE TITLE
edit.selected_text() in Emacs on Linux produces Emacs error: "Selection owner couldn't convert: MULTIPLE"

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#490]
With this `edit.selected_text()` implementation:

```python
@ctx.action_class("edit")
class EditActions:
    def selected_text() -> str:
        with clip.capture() as s:
            actions.edit.copy()
        try:
            return s.text()
        except clip.NoChange:
            return ""
```

And with `edit.copy()` in emacs implemented as `key("alt-w")` (the keybinding for copying), running `edit.selected_text()` yields an empty string and produces an emacs error message, `Selection owner couldn't convert: MULTIPLE`. I'm not sure what the root cause here is. This used to work just fine, not sure when it broke, probably in the last month or two? My guess is something is going wrong with MIME types?

Ubuntu 21.10, GNU Emacs 27.1, Talon v0.2.0-347-gab2a

**Comment by rntz** [comment]
This seems to be fixed as of Talon v0.2.0-352.

**Comment by rntz** [comment]
This error message still occurs and has been occurring for a while. However, most (all?) of the time edit.selected_text() nonetheless correctly produces the actual selected text. 

However, this error _seems_ to be causing occasional failures of context-sensitive dictation. I'm not sure why, since the behavior on the Talon side appears to be correct? But if I replace `selected_text` with an implementation that shells out to `xsel` instead of calling `clip.get_text` or `clip.capture` the error message goes away and context-sensitive dictation seems to work consistently. I need to debug further.

For now I've worked around this by changing my selected_text implementation. I'd be interested if anybody knows what might be causing the error message.

**Comment by lunixbochs** [comment]
Does adding a small sleep after `actions.edit.copy()` improve it?

**Comment by rntz** [comment]
I added a 150ms sleep. The emacs error message still occurs. I'll try it out for a while to see whether it improves the context-sensitive dictation flakiness.

**Comment by lunixbochs** [comment]
can you retest on latest talon-rust?

(I'm going to preemptively close this though, because I know we don't query the MULTIPLE target anymore)
