### ISSUE TITLE
Mac accessibility: allow slicing children

### ISSUE THREAD

**Issue by nriley** [talonvoice/talon#496]
With some accessibility objects (e.g., tables) it takes time to fetch the entire list of children when only some may be required.

AXUIElementCopyAttributeValues exposes an index and maximum values; it'd be convenient and hopefully improve performance if this were mapped to Python's array slicing syntax.

My specific use case is navigating relative to the current table selection, e.g. to the next/previous row.

* Mail - https://github.com/nriley/knausj_talon/blob/nriley/apps/platforms/mac/mail/mail.py#L41
* OneNote - https://github.com/nriley/knausj_talon/blob/nriley/apps/platforms/mac/onenote/onenote.py#L134

**Comment by lunixbochs** [comment]
This has been mitigated for a bit in the beta. Let me know if the current solution ends up being too slow for some app.
