### ISSUE TITLE
.py files behind symlinks are not watched for changes

### ISSUE THREAD

**Issue by tuomassalo** [talonvoice/talon#5]
I have a symlink `~/.talon/user/atom.py` that points to `.../somewhere/else/atom.py`. If the actual file behind the symlink changes, Talon doesn't notice that, so the changes are not picked up until Talon is restarted. This makes it harder to e.g. clone https://github.com/tabrat/talon_user somewhere and hand-pick what you need by symlinking. Also contributing to such repo requires more work without symlink support.

**Comment by tuomassalo** [comment]
Reply via Slack:
> looks like I need to manually add symlink targets to the watch list
> actually I'm not sure I want to fix this. I'd rather add file or context toggling
> so you'd always clone the whole dir and only turn on some of them
> also remember repos will be more like sublime plugins where you opt into one app at a time or whatever

It also seems that `~/.talon/user` cannot be a symlink. If it is, the contents of the link destination are ignored.

This makes it hard to keep grammar files in e.g. ownCloud or Dropbox.

**Comment by lunixbochs** [comment]
You should be able to symlink `~/.talon/user` now (should at least be in beta, not sure if it's in public yet).
