### ISSUE TITLE
ui.windows(hidden=False) sometimes returns recently-minimized windows on macOS

### ISSUE THREAD

**Issue by bobthecow** [talonvoice/talon#501]
I'm running the current beta.

I can most easily reproduce the issue in Safari by minimizing a window while another app has focus (so focus doesn't return to the next Safari window). It seems to happen up to half of the time, and only recently minimized windows have this issue. Refocusing the app will sometimes (often?) clean up the windows which were erroring before.

The recently minimized windows error with `UIErr: Could not get window rect.` when trying to read or set `Window.rect`, e.g.

```
        windows = [win for win in ui.windows(hidden=False) if win.app.name == "Safari"]
        for win in windows:
            try:
                win.rect
            except:
                print(win)

```

**Comment by lunixbochs** [comment]
Can you retest on -468?

**Comment by bobthecow** [comment]
Seems to be cleared up with ~468. Thanks!
