### ISSUE TITLE
`ui.active_window()` sometimes returns the wrong windows

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#502]
I'm on beta 454, but I've noticed this for a while, most commonly (exclusively?) on JetBrains IDEs. After pushing ctrl-\` to rotate windows, `ui.active_window()` will sometimes return the wrong (old), one. I notice this most frequently when using keyboard shortcuts to snap windows.

In testing, I noticed `ui.focused_element().AXWindow` _does_ return the right one, so for now I can work around by writing an action that will compare the `AXTitle` of those two, and if they differ searching through `ui.active_app().windows()` to find the right one.

**Comment by phillco** [comment]
Correction: haven't tried this on 460 yet, will report back if it still happens there.

**Comment by lunixbochs** [comment]
Can you retest on -468?

**Comment by phillco** [comment]
Just for clarity, still seeing this on 496, in JetBrains. I've also noticed `ui.active_window().title` can also be stale even if the active window is correct. I've added some overrides for JetBrains specifically to work around this for now.

**Comment by phillco** [comment]
I unfortunately do continue to see this on recent betas, although it's less common than before your ~46x fixes.

I'll retest on the newly released 2022.2 though, as that version brings in a large JVM upgrade which I imagine brings in a lot of new Swing behavior.

**Comment by rntz** [comment]
I believe I have observed this on mac ventura, in my case with firefox.

**Comment by rntz** [comment]
I now observe behavior that I *believe* to be due to this regularly. It's pretty annoying, a lot of my window management stuff now doesn't work reliably. Mac Ventura, talon 0.3.1-57, multiple apps (firefox, emacs, apple terminal). I'll let you know if I figure out a consistent repro.

symptoms possibly due to this:
- snap left/etc snapping the wrong window
- I have a command that opens an emacs window and tries to focus it by looking for a new window; sometimes fails to focus it (maybe this is a separate issue? maybe #513?)

**Comment by lunixbochs** [comment]
still just firefox?

**Comment by rntz** [comment]
No, multiple apps. Firefox, Apple Terminal, Emacs are the ones I think I've seen it on.

**Comment by rntz** [comment]
I made a little script that watches for `ui.active_window()` not agreeing with `ui.focused_element()` to see if I can catch it in the act and figure out how to repro consistently, but no hits yet: https://gist.github.com/f5771b6d2b303c4f1287379b27a9be9b

**Comment by lunixbochs** [comment]
Don't check it in the win_focus event, call this wherever you're triggering your window management code.

**Comment by rntz** [comment]
The script had way too many false positives so I turned it off a while ago. I think this was because terminal tabs are actually treated as windows somehow? Ugh. Bug is still occurring frequently and very frustrating. I've mostly been mixing keyboard/mouse use with talon use, maybe that has something to do with it. Gonna try instrumenting just the `snap` commands again.

**Comment by rntz** [comment]
Ok, I managed to actually catch an occurrence with the instrumentation on. I'm not sure what triggered it, but once it happened, switching between two different firefox windows on the same virtual desktop by clicking with the mouse did not update `ui.active_window()` (so it became incorrect whenever I clicked on the other window) but did update `ui.focused_element().window` correctly. Switching to another desktop, however, fixed the problem.

**Comment by lunixbochs** [comment]
firefox is kind of bad at accessibility events, talon already has several firefox specific workarounds in place

**Comment by rntz** [comment]
I've now observed similar behavior in Emacs. Emacs was focused but `ui.active_window().title` reported a title that I think didn't exist on any window, and consistent with this, "snap right" failed with `UIErr: Could not get window rect`.

Meanwhile, `ui.focused_element().window.title` reported the correct title, but `ui.focused_element()` had no `AXWindow` attribute (this seems to be standard for Emacs).

If I switched away from Emacs by clicking on an Apple Terminal window, then re-focused the Emacs window by clicking, the problem persisted. But, there was no problem with the Terminal window focused.

Does Talon's ability to determine which window is active depend on that application doing the right thing? That would be a bummer. This all worked quite reliably for me in Linux.

**Comment by david-tejada** [comment]
Is there any hope for this in Firefox? Any time I want to snap a recently focused window I have to first switch to another app and then switch back. `win.title` also doesn't update as you switch tabs. I have also observed this behavior in Windows.

**Comment by lunixbochs** [comment]
please retest on latest beta

**Comment by david-tejada** [comment]
The issue with Firefox is indeed fixed, at least for me. Thanks!

**Comment by nriley** [comment]
My issues are fixed too and I am joyfully removing a whole bunch of workarounds.

Thanks!

**Comment by phillco** [comment]
I can confirm:

- This reproduces on the old version 100%, with the realization that the problem is launching the bad app (IntelliJ/PyCharm for me) _after_ Talon (thanks @david-tejada for the insight; can't believe I never noticed that before)
- This looks to be fixed for me (for those two apps; presumably, everything else as well) in the latest beta.
