### ISSUE TITLE
Support disabling Alternative Pointer Actions notifications

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#503]
When using Alternative Pointer Actions Notifications to enable face mode, macOS shows a lot of annoying notifications in the middle of the primary screen that cannot be disabled.

<img width="341" alt="Screen Shot 2022-04-29 at 12 03 32 PM" src="https://user-images.githubusercontent.com/536668/166009646-a67b0e91-b6ea-49c9-b125-b9e20fb88837.png">

They pop up whenever tracking starts and stops, and whenever APA is enabled and disabled. This makes using face mode as an additive mode more annoying than necessary.

With investigation, it looks like these notifications are showed by a process called `AccessibilityVisualsAgent`. If we kill that process quickly enough, the notification won't show up. The process will restart but as long as we can kill it in time, no notification will be shown.

In my testing attempting to kill it every `0.1s` in a tight loop is sufficient to prevent the notifications from appearing.

**Comment by phillco** [comment]
Also, there some weirdness with windows events. `AccessibilityVisualsAgent` will send talon `win_open` and `win_close` events _unless_ it's killed while Talon is running, at which point there are no future window events and `ui.apps(name="AccessibilityVisualsAgent")[0].windows()`will incorrectly be an empty list. The application launch/close events do continue to be delivered. This is on 0.2.0-454-g49b0.

**Comment by lunixbochs** [comment]
just going to ship my own cross-platform model that doesn't have the overlays.
