### ISSUE TITLE
Ubuntu: when talon restarts after updating I get two icons in the dock

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#508]
Whenever talon updates and auto-restarts, I end up with two talon icons in my dock. Ubuntu 21.10, default wm, talon 480 post-update. Only one of them seems to be functional, e.g. only one updates when I put talon into sleep mode:

![Screenshot from 2022-05-09 17-12-24](https://user-images.githubusercontent.com/16143/167452388-21da4a2a-ceaf-4c0b-b164-48aeef307e03.png)

**Comment by lunixbochs** [comment]
we have a new tray implementation and I added a workaround for this. let me know if it comes up again.
