### ISSUE TITLE
talon resets Dragon pause required before commands setting on launch

### ISSUE THREAD

**Issue by Shashank066** [talonvoice/talon#509]
Every time talon is launched it resets Dragon pause required before commands to 0.1. The setting is located under 
Dragon options->Commands-> Pause required before commands

Talon shouldn't interfere with that setting. Any workaround?

**Comment by lunixbochs** [comment]
In the Talon Home directory, there is a file called draconity.toml, which allows you to change the Dragon timeout values Talon applies.

Talon messes with this setting for two reasons:
- On Mac, there's no UI for changing the setting, so draconity.toml is the only way to do that. Some Dragon for Windows versions also don't let you change the timeout yourself without Talon's help.
- draconity.toml allows you to change the setting in a wider range, and with much more precision than Dragon's own UI.
