### ISSUE TITLE
sequential manipulation of window.rect loses previous changes

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#510]
Ubuntu 22.04, talon -492

If I run two actions which manipulate `ui.active_window().rect` in succession, only the last one applies, seemingly because the second one doesn't see the first one's changes. Examples follow. Expected behavior of "magic magic" or "magic magic magic": align window at top-left of screen. Actual behavior: aligns to left of screen but not top.

**window_manipulation.talon**
```
magic magic:
  user.send_top()
  user.send_left()

magic magic magic:
  user.send_top_left()
```

**window_manipulation.py**
```
from talon import ui, Module, Context, actions

mod = Module()

@mod.action_class
class ModuleActions:
    def send_top():
        """"""
        w = ui.active_window()
        r = w.rect
        r.y = w.screen.y
        w.rect = r

    def send_left():
        """"""
        w = ui.active_window()
        r = w.rect
        r.x = w.screen.x
        w.rect = r

    def send_top_left():
        """"""
        w = ui.active_window()
        r = w.rect
        r.y = w.screen.y
        w.rect = r
        r = w.rect              # if we remove this line it works, of course
        r.x = w.screen.x
        w.rect = r
```

**Comment by lunixbochs** [comment]
On Linux it's up to your window manager to actually place the window after our request, and that's a completely async process - they can take as long as they want to do that, or simply choose to not do anything. If you want the rect to be consistent across calls, after changing it you'll probably need to block until it changes (with a timeout in case the wm ignores your request, and you'll probably want to handle the case where the wm chooses a different rect than you gave it).

Alternatively, you could build a slightly stateful window placement layer on top of talon specific to these commands that remembers recent window placement attempts and tries to rewrite your requests to be self consistent (or at least caches the rect for a moment).

I don't know that it's particularly reasonable for Talon to solve this for you, the only thing I can really think of is to latch/cache window rect writes that happen during a command and don't actually move the window until after the command, but that introduces new problems with multi-step automation commands.

**Comment by lunixbochs** [comment]
I don't think there's really a good way for Talon to hide this behavior from you. You'll need to account for the delay of the Linux window manager in actually moving your window.
