### ISSUE TITLE
`ui.apps()` sometimes loses track of applications

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#513]
I don't yet know what causes this, but sometimes Talon loses track of certain applications, and they no longer show up in `ui.apps()`. For example, you can't look them up by PID, even though that process exists in `ps aux`:

```
>>> ui.apps(pid=54053)
[]
$ ps aux  | grep 54053
phillco          54053   6.5  3.3 417758432 2186816   ??  S     9:44AM  65:20.89 /Applications/PyCharm 2021.3.app/Contents/MacOS/pycharm
>>> ui.apps(name="PyCharm")
[]
```

I've noticed this in a variety of applications:

- PyCharm
- Spotify
- mpv

It can cause strange behavior like:
- `ui.active_window()` returns `Window(None)`, so window-title-based features like language detection stop working
- windows snapping stops working
- the experimental media API raise an exception on returning the media app (they know the right PID, but then they can't look up that app)

Filing this for tracking purposes, don't have a good reproduction yet.

Restarting Talon fixes it, but is obviously undesirable. This has popped up occasionally for at least several months now on the beta release, but possibly longer.

**Comment by lunixbochs** [comment]
is this still happening?

**Comment by phillco** [comment]
Hm, I don't think I've seen it recently but I haven't been looking for it super closely either.

If you want you can close it and I can comment if I see it again.
