### ISSUE TITLE
add `close()` and `minimize()` to `Window`

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#514]
This was quick request that came up during some of the #axkit discussion, as our [current method](https://github.com/phillco/talon-axkit/blob/main/window_action.py#L15-L39) involves invoking the actual buttons via accessibility, which can be block if the application is slow to respond and make mass window changes sluggish.

aegis mentioned in Slack that he could do it faster inside Talon, and they also just seem like nice utility functions to have.

**Comment by lunixbochs** [comment]
We already have `window.close()`

In the rust beta, I just added get/set properties for:
```
win.minimized
win.maximized
win.fullscreen
```

e.g.

```
print(win.minimized)
win.minimized = False
```
