### ISSUE TITLE
app.windows() ordering no longer returns windows in focus order

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#515]
This is the only regression (?) that I've noticed after the windowing logic rework that landed in early May (the set of changes which fixed fixed the issue with `""` titles -- ~109-0.2.0-480-gb94e?).

In previous builds (e.g. I can reproduce on `0.2.0-462-g20b0`), `ui.apps(name="...").windows()` always returns windows in a sorted list from most recently focused to least recently. If I focus window A, then B, then C, I get `[C, B, A]`. 

After the refactor, there doesn't seem to be a sort order.

I can write an action that returns them in the previous order by doing this:

```
        windows_order_ids = talon.mac.ui._window_order()
        windows = [w for w in app_.windows() if w.id in windows_order_ids]
        return sorted(windows, key=lambda w: windows_order_ids.index(w.id))
```

but I found the previous behavior to be quite convenient, especially when writing actions that did basic window management, so unsure if this is expected or not.

I can reproduce this in Finder as well as JetBrains.

Relatedly, sometimes it looks like the window titles returned in the list are a little bit stale.

**Comment by lunixbochs** [comment]
That's weird, I'm definitely still calling the sort function on app.windows(). Is ui.windows() still in sorted order for you?

**Comment by phillco** [comment]
The sort order of `ui.windows()` is also wrong for me.

**Comment by lunixbochs** [comment]
thanks for the report! this regression is fixed in -509
