### ISSUE TITLE
window.hidden attribute not kept up to date

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#539]
To reproduce: On Talon 0.3.1-57, on Mac Ventura, open a Terminal window. Open multiple tabs. Now, close one of the terminal tabs and switch focus (eg via cmd-tab) to another app on the same desktop. Without focusing Terminal, run in Talon:

```python
term = actions.user.get_running_app('Terminal')
# ^this uses knausj; alternatively, grab the terminal ui.App some other way
assert [w for w in term.windows() if not w.hidden]
```

and observe the assertion failure. There is a visible terminal window/tab, but it is listed as hidden. Note that Terminal tabs are treated as separate windows for some reason.

I ran into this trying to create a command that would focus a terminal window on the current desktop if one exists and otherwise create one - it kept thinking there was no terminal window on the current desktop (because they all had `w.hidden`). More generally, I have an action for finding the "active" windows (those visible on the current desktop) of an app, but this issue makes it sometimes produce wrong results:

```python
    def active_windows(app: Optional[ui.App] = None) -> List[ui.Window]:
        """Finds all windows of the given app (default all apps) which are
        currently on-screen."""
        try: workspace = ui.active_workspace()
        except AttributeError: workspace = None
        return [w
                for w in (app.windows() if app is not None else ui.windows())
                if not w.hidden and (workspace is None or w.workspace == workspace)]
```

**Comment by lunixbochs** [comment]
is this still an issue after the #502 fix?

**Comment by lunixbochs** [comment]
bump @rntz

**Comment by lunixbochs** [comment]
please reopen this if you still encounter it, there have been many fixes to the mac ui backend
