### ISSUE TITLE
Logging back in to MacOS after putting computer to sleep overnight makes microphone undetected

### ISSUE THREAD

**Issue by xavier630** [talonvoice/talon#542]
OS: MacOS Monterey 12.6
Microphone: Blue Yeti
Talon: v0.3.1

**Context**
1. After the computer has been asleep all night, upon logging in in the morning, Talon is still running but doesn't detect my yeti microphone. This happens every day.
2. The microphone seems to be connected properly as it's visible within the sound input settings of the computer. This makes me believe that this is a Talon issue.
3. Currently to fix this, every morning I need to unplug my microphone and plug it back in.

**Proposed Solution**
1. Talon can still detect and any plugged in microphones even after a long period of sleep.

**Comment by lunixbochs** [comment]
When you say doesn't detect, do you mean it's not even in Talon's microphone list?

**Comment by xavier630** [comment]
It shows up in the Talon microphone list:
![image](https://user-images.githubusercontent.com/9077250/214481729-c85a116b-82fc-4b9d-a01d-70094576fb08.png)

**Comment by xavier630** [comment]
I have one more idea that perhaps it's a MacOS issue and it doesn't even work on Mac when it's in this state despite showing up in the Mac sound input list. 

I'll try to test this theory later this week.

**Comment by xavier630** [comment]
Okay, upon further testing, I think this is MacOS issue and not a Talon issue.

I tried a few recording apps and the Yeti doesn't work there either after having been asleep (even though it's selectable). 

Apologies for the trouble.
