### ISSUE TITLE
`platformdirs` import

### ISSUE THREAD

**Issue by pokey** [talonvoice/talon#545]
It appears that `platformdirs` is available for import in Talon beta, but not public.  Should we be relying on the ability to import `platformdirs` and expect it to appear in the next public release, or is that just available by happenstance?

**Comment by lunixbochs** [comment]
I don't see platformdirs on the latest beta, perhaps you installed it yourself?

In general, Talon's transient Python dependencies should not be relied upon.

Just out of curiosity, which Talon version / OS are you on? What's the output in the repl for the following?
```
import platformdirs
platformdirs
```

**Comment by pokey** [comment]
Talon version: `v0.3.1-17-geb94 (17)`
OS: MacOS Ventura 13.2 (22D49)

```
>>> import platformdirs
>>> platformdirs
<module 'platformdirs' from '/Users/pokey/.talon/.venv/lib/python3.9/site-packages/platformdirs/__init__.py'>
```

Fwiw @AndreasArvidsson was able to import `platformdirs` from the REPL as well

But long story short it sounds like the answer is that we shouldn't rely on `platformdirs` being available, which is reasonable, just wanted to check

I'm ok with closing this issue; my question is answered

**Comment by lunixbochs** [comment]
That's importing from your venv, so you appear to have installed it yourself as a transient dependency of something else.
