### ISSUE TITLE
Talon-Rust: screenshot fails with error on Windows

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#547]
Trace:
2023-02-19 13:24:16 ERROR     8:                         talon\scripting\talon_script.py:604| 
    7:                         talon\scripting\talon_script.py:307| 
    6:                              talon\scripting\actions.py:88 | 
    5: user\wolfmanstout_talon\plugin\screenshot\screenshot.py:30 | screenshot_rect(screen.rect)
    4: user\wolfmanstout_talon\plugin\screenshot\screenshot.py:63 | img = screen.capture_rect(rect)
    3:                                         talon\screen.py:346| 
    2:                                         talon\screen.py:352| 
    1:                                         talon\screen.py:340| 
AttributeError: 'Library' object has no attribute 'screen_capture'

[The below error was raised while handling the above exception(s)]
2023-02-19 13:24:16 ERROR cb error topic="phrase" cb=SpeechSystem.engine_event
   16:             talon\lib\_thread.py:19 * # cron thread
   15:                     threading.py:937* 
   14:                     threading.py:980* 
   13:                     threading.py:917* 
   12:                    talon\cron.py:151| 
   11:                     talon\vad.py:21 | 
   10: talon\scripting\speech_system.py:362| 
    9:             talon\engines\w2l.py:722| 
    8:      talon\scripting\dispatch.py:134| # 'phrase' main:EngineProxy._redispatch()
    7: talon\scripting\speech_system.py:64 | 
    6: ------------------------------------# [stack splice]
    5:      talon\scripting\dispatch.py:134| # 'phrase' main:SpeechSystem.engine_event()
    4: talon\scripting\speech_system.py:415| 
    3:      talon\scripting\executor.py:110| 
    2:  talon\scripting\talon_script.py:705| 
    1:  talon\scripting\talon_script.py:608| 
talon.scripting.talon_script.TalonScriptError: 
 in script at C:\Users\james\AppData\Roaming\talon\user\wolfmanstout_talon\plugin\screenshot\screenshot.talon:1:
 > user.screenshot()
AttributeError: 'Library' object has no attribute 'screen_capture'

**Comment by lunixbochs** [comment]
fixed in latest talon-rust
