### ISSUE TITLE
Talon-Rust on Windows: overlays turn white on lock screen and persist after unlock

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#548]
See attached video. I have talon-hud enabled and any active canvases (even if transparent) become opaque white when I lock the screen, and remain that way until I do something which triggers a redraw.

https://user-images.githubusercontent.com/1121562/219976859-aded8954-38e1-452c-8162-f971f4e9c013.MOV

**Comment by lunixbochs** [comment]
please retest this behavior in the current rust beta

**Comment by wolfmanstout** [comment]
Fix confirmed!
