### ISSUE TITLE
Talon-Rust overlay rendering slower than Talon-Legacy on Windows

### ISSUE THREAD

**Issue by wolfmanstout** [talonvoice/talon#550]
See attached videos. There is a delay on the Rust version as a white frame shows up for about a half second. Based on other interactions where rendering occurs within a sequence of actions, this rendering delay appears to be blocking.

Talon-Legacy: 
https://user-images.githubusercontent.com/1121562/219977321-35a80354-5d17-4612-bf2b-9bbacc2d6c5f.MOV

Talon-Rust: 
https://user-images.githubusercontent.com/1121562/219977340-6f32ca96-44e5-4641-9e25-2ec692388d26.MOV

**Comment by AndreasArvidsson** [comment]
This(Flashing white opaque rectangle) happens for me on all canvasses. Including the Talon built in subtitles.
Windows 10

**Comment by lunixbochs** [comment]
should be fixed in new rust beta
