### ISSUE TITLE
Type system errors when `list[dict]` is passed from Talonscript

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#553]
I get the following error message in the log
```
2023-02-24 16:05:56 ERROR Line 14: user.cursorless_multiple_target_command(action: str, targets: list[dict], arg1: Any = <class 'user.cursorless-talon.src.command.NotSet'>, arg2: Any = <class 'user.cursorless-talon.src.command.NotSet'>, arg3: Any = <class 'user.cursorless-talon.src.command.NotSet'>)
2023-02-24 16:05:56 ERROR Line 14:   parameter 2 (targets) expects type list[dict], got list[typing.Any]
```

That Talon script looks like this: https://github.com/pokey/cursorless-vscode/blob/1b18e38efe87904b918faf88c7d16c0ffa1b0e1f/cursorless-talon/src/cursorless.talon#L13-L14
```
{user.cursorless_move_bring_action} <user.cursorless_move_bring_targets>:
    user.cursorless_multiple_target_command(cursorless_move_bring_action, cursorless_move_bring_targets)
```

The action is defined here: https://github.com/pokey/cursorless-vscode/blob/1b18e38efe87904b918faf88c7d16c0ffa1b0e1f/cursorless-talon/src/command.py#L96-L111
The problem is that if I add print statements for the type getting passed in is `list[dict]`
```
def cursorless_multiple_target_command(
        action: str,
        targets: list[dict],
        arg1: Any = NotSet,
        arg2: Any = NotSet,
        arg3: Any = NotSet,
    ):
        """Execute multi-target cursorless command"""
        print(type(targets))
        for t in targets:
            print(type(t))
```
Output:
```
2023-02-24 16:05:56    IO <class 'list'>
2023-02-24 16:05:56    IO <class 'dict'>
2023-02-24 16:05:56    IO <class 'dict'>
```

**Comment by pokey** [comment]
here's the definition of `cursorless_move_bring_targets` fwiw; see that return type is `list[dict]` https://github.com/cursorless-dev/cursorless/blob/1fcb776a44487e72badf36ea7dfeafd8d3549bf3/cursorless-talon/src/actions/move_bring.py#L12

**Comment by lunixbochs** [comment]
Failed to repro with the following code, can you produce a minimal example? What's the actual value returned by `cursorless_move_bring_targets` when it fails?

```python
from talon import Module

mod = Module()
@mod.action_class
class Actions:
    def test1() -> list[dict]:
        "returns a list[dict]"
        return [{"a": "b"}]

    def test2(value: list[dict]) -> None:
        "takes in a list[dict]"
        print(value)

@mod.capture(rule='test one')
def test1(m) -> list[dict]:
    return [{"a": "b"}]
```

```talon
action test one: user.test2(user.test1())
capture <user.test1>: user.test2(test1)
```

**Comment by AndreasArvidsson** [comment]
This is the return value from the capture
`[{'type': 'primitive', 'mark': {'type': 'decoratedSymbol', 'symbolColor': 'default', 'character': 't'}}, {'type': 'implicit'}]`

**Comment by AndreasArvidsson** [comment]
When using the above return value in your example code I get the same error

**Comment by AndreasArvidsson** [comment]
Gives error
```
[
        {"a": "b"},
        {"c": { }},
]
```

No error
```
[
        {"a": "b"},
        {"c": "d"},
]
```

**Comment by lunixbochs** [comment]
implemented nested container type inference in next rust beta, we correctly infer this as `list[dict[Any]]` now

**Comment by lunixbochs** [comment]
just released this fix to the rust beta
