### ISSUE TITLE
[Mac] Talon-Rust CPU usage quite high after triggering zoom mouse

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#556]
Talon rust’s CPU usage when idle (no eye tracking, voice, mic = none) seems far higher on OS X. This occurs reliably after triggering zoom mouse once.

QT talon seems to chill at ~2%, while talon rust claims ~102% per activity monitor. This is on a 8 core i9 MacBook.

Version: 0.3.1-382-g4a86, Branch: rust, OS: macOS-13.2-x86_64-i386-64bit

**Comment by lunixbochs** [comment]
should be fixed in latest rust beta
