### ISSUE TITLE
[Windows] fs.watch does not work on folders or files

### ISSUE THREAD

**Issue by Python1320** [talonvoice/talon#558]
**Target:** Windows 10, both standalone and installed version.

Cleared `C:\Users\user\AppData\Roaming\talon\user` 
... and created file
`C:\Users\user\AppData\Roaming\talon\user\testwatch.py`:
```python
print("fs.watch test loaded")
from talon import fs
def testwatch(name, flags):
	print("hi",name)
print("fs.watch",fs.watch(r"y:\dl\talon-windows\test", testwatch))
print("fs.watch",fs.watch(r"y:\dl\talon-windows\test\test.txt", testwatch))
```

Also modifying testwatch.py **DOES** trigger the updating mechanism for the python file itself.

**Comment by lunixbochs** [comment]
What kind of device / filesystem is y:\?

**Comment by Python1320** [comment]
just a normal spinning hard drive. I also tested with `c:\test` and got the same result. 
If someone can prove that it works for them I will continue searching what could possibly be making my setup misbehave.

**Comment by lunixbochs** [comment]
Is this talon 0.3.1 public?

Talon uses fs.watch internally to handle the python reloads fwiw. So if your python code reloads on save then fs.watch works.

**Comment by Python1320** [comment]
Sorry, yes, `DEBUG Talon Version: 0.3.1`

~~Upon further testing I just got it to work from `C:\Users\user\AppData\Roaming\talon\test\test.txt` but nowhere else. I am running without UAC and as admininistrator but that does not seem to help.~~

While writing this... it's a stupid thing, `C:\test` works but `c:\test` does not. Testing further, but seems the problem is solved 😅

**Comment by lunixbochs** [comment]
> C:\test works but c:\test does not 

weird, leave this issue open so I will remember to test that specifically

> running without UAC and as admininistrator

Please don't explicitly run Talon as an Administrator, that can cause problems. Talon itself already has accessibility entitlements to control Administrator owned processes as long as you install it to Program Files.

**Comment by lunixbochs** [comment]
this should be fixed in the next beta
