### ISSUE TITLE
[windows rust] Not consistently rendering over the full screen

### ISSUE THREAD

**Issue by alexander-clarke** [talonvoice/talon#559]
When using the knausj mouse grid or the dense grid

It is working correctly on my main monitor, rendering over the entire screen
(1440p 100% scaling)

It is not working correctly on my off monitor, and will only render over roughly the right quarter of the screen
(2160p 225% scaling)
![image](https://user-images.githubusercontent.com/9615373/222836091-f786a2d2-dbd2-4fe5-909e-1fed11c31a60.png)

legacy (expected behavior)
![image](https://user-images.githubusercontent.com/9615373/222839639-48ee7777-4741-4a8e-8b75-f59793df18cb.png)

On windows, rust beta

**Comment by lunixbochs** [comment]
what does it look like when it's working? does it work properly if you only have the 225% scale screen and not the other one?

**Comment by alexander-clarke** [comment]
updated the post with what happens on normal beta, did seem to be more consistent when it was my only screen

**Comment by lunixbochs** [comment]
is this still happening?

**Comment by alexander-clarke** [comment]
Hey, just checked today and doesn't seem to be happening anymore on latest beta
