### ISSUE TITLE
Talon-Rust: Talon doesn't start after update

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#561]
Using talon rust windows portable. After talon has updated I'm just left at the prompt "press enter to continue", but talon isn't actually running and I can't press anything.

**Comment by lunixbochs** [comment]
Which version number did you update from?

**Comment by AndreasArvidsson** [comment]
I don't have that stored sorry. Next time I get an update I will get back to you about if the problem persists.

**Comment by lunixbochs** [comment]
The version is printed to your log

**Comment by AndreasArvidsson** [comment]
Gotcha
Looks like I went from `0.3.1-355-g560d` to `0.3.1-409-g78ef` in my latest update

**Comment by lunixbochs** [comment]
Can you revert back to the one in slack and update again, then look for errors in the updater output if it doesn't start talon?

**Comment by AndreasArvidsson** [comment]
Nothing in the Talon log and the update window looks like this
![image](https://user-images.githubusercontent.com/3511326/222972976-598f6ec2-5d6a-4de8-865c-67b7a3ee6829.png)

This is also pretty
![image](https://user-images.githubusercontent.com/3511326/222972747-7466a786-a240-4a5e-a24e-da8835a677b9.png)

**Comment by lunixbochs** [comment]
should be fixed in next rust beta
