### ISSUE TITLE
Rust beta change log shows the html tags

### ISSUE THREAD

**Issue by Leeft** [talonvoice/talon#563]
As per the image, the rust beta change log doesn't show styled text, but raw html tags. Windows 10.

![image](https://user-images.githubusercontent.com/651704/222955782-4a766b2e-c794-41a0-b202-e33019a138a0.png)

**Comment by lunixbochs** [comment]
Fixed on latest. (You won't see the new UI until your second update, though, as the first update will be from an older Talon version)

<img width="745" src="https://user-images.githubusercontent.com/117642/226261272-92558655-dbc5-44e6-b6f3-167de26e24c1.png">
