### ISSUE TITLE
Talon-Rust: Windows UAC disables eye tracker

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#567]
Went to install geekbench and when the UAC prompt came up my eye tracker died. This works find on Talon-qt.
```
2023-03-06 09:16:49 ERROR cron interval error <bound method BaseControlMouse.tick of <talon.plugins.eye_mouse_2.ControlMouse2 object at 0x0000000004E8D970>>
   10:                 threading.py:937* # cron thread
    9:                 threading.py:980*
    8:                 threading.py:917*
    7:                talon\cron.py:148|
    6:      talon\scripting\rctx.py:235| # 'cron' tracking:Cron.interval.<locals>.call()
    5:                talon\cron.py:176| # [stack splice]
    4:                contextlib.py:79 |
    3: talon\plugins\eye_mouse_2.py:138|
    2: talon\plugins\eye_mouse_2.py:404|
    1:        talon\windows\ctrl.py:141|
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')
```

**Comment by lunixbochs** [comment]
is Talon installed to Program Files? we don't get full accessibility permissions unless you install to Program Files.
do you have "dim the desktop" enabled for UAC? you need to disable that, I'm not planning on writing a SYSTEM service that can control the mouse on the alternate desktop.

**Comment by AndreasArvidsson** [comment]
That was it. I temporally had a rust installation in my download directory. Moving it to program files solved the problem. Btw once I closed the uac the eye tracker didn't come back up.

Already disabled.

**Comment by lunixbochs** [comment]
once you closed uac, the focused window would have been elevated by uac, so it would still probably prevent eye tracking

**Comment by AndreasArvidsson** [comment]
Got it
