### ISSUE TITLE
[rust] pink subtitles, followed by black background

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#569]
After some random point, I'll get one flash of the subtitles where the entire bounding box is pink:

<img width="611" alt="Screen Shot 2023-03-06 at 10 51 38 AM" src="https://user-images.githubusercontent.com/536668/223335597-9ca3b4d0-8d22-485e-986e-14ced0485833.png">

Thereafter, subtitles will render with a black background, instead of a transparent one:

<img width="714" alt="Screen Shot 2023-03-06 at 10 52 04 AM" src="https://user-images.githubusercontent.com/536668/223335607-629bedb8-9a4c-49e7-9074-bd117b6c89c5.png">

This seems to happen after the Rust beta has been running for a while, and is fixed by a restart.

**Comment by lunixbochs** [comment]
can you confirm the newest talon version you've seen this on? + macos version and hardware?

**Comment by phillco** [comment]
0.3.1-419-g7ed2

Monterey, M1 Max

**Comment by phillco** [comment]
Easily reproduced with @lunixbochs's stress script

**Comment by lunixbochs** [comment]
fixed in latest rust beta
