### ISSUE TITLE
Talon-Rust: Can't close update dialog/window with keyboard

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#572]
Neither enter, space or tab does anything. Only way I can close the update dialogue window is using a mouse click

windows 10

**Comment by lunixbochs** [comment]
I added default button focus, so after 0.3.1-512 you should just be able to press enter to advance the dialog.
Tab does work for me, but some of the tab elements appear to be invisible, so you might need to press tab more times than you expect.
