### ISSUE TITLE
Talon-rust: talon cannot see its own window titles on windows

### ISSUE THREAD

**Issue by mirober** [talonvoice/talon#573]
original slack thread: https://talonvoice.slack.com/archives/G9YTMSZ2T/p1678288549172359

When (for example) the talon log viewer is in focus, `ui.active_window().title` gives an empty string whereas `GetWindowText(ui.active_window().id)` gives "Talon Log Viewer". Same thing happens for the "about talon" window and other canvases.

This isn't a problem in talon qt for the about talon and update windows.

**Comment by lunixbochs** [comment]
this is fixed in latest beta
