### ISSUE TITLE
Give imgui/canvas windows more descriptive window titles

### ISSUE THREAD

**Issue by mirober** [talonvoice/talon#574]
Original slack thread: https://talonvoice.slack.com/archives/G9YTMSZ2T/p1678288549172359

Currently imgui/canvas windows have a generic title of "Talon Canvas". An enhancement would be to allow the user to set the title, or make up a descriptive title based on the imgui callback name or the name of the context.

**Comment by lunixbochs** [comment]
fixed in next beta: canvas windows now have their context name in the title in parens

<img width="439" alt="Screenshot 2024-01-03 at 1 26 46 AM" src="https://github.com/talonvoice/talon/assets/117642/36237c84-414e-4da3-8d15-b5111e2da3b6">
