### ISSUE TITLE
Talon-rust: imgui windows are focusable on windows

### ISSUE THREAD

**Issue by mirober** [talonvoice/talon#575]
Original slack thread: https://talonvoice.slack.com/archives/G9YTMSZ2T/p1678288549172359

In talon-qt, clicking on an imgui window de-focuses the previously focused window but does not switch focus to the imgui window (GetForegroundWindow returns 0). In talon-rust, clicking the imgui window switches focus to it and GetForegroundWindow returns the talon canvas window id.

**Comment by lunixbochs** [comment]
can you see if this is fixed on latest talon-rust?

**Comment by mirober** [comment]
Yep, seems to be 👍
