### ISSUE TITLE
[Mac] talon-rust:  log viewer will pop up above the active application with imgui

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#578]
Version: 0.3.1-437-g8fea, Branch: rust, OS: macOS-13.2.1-x86_64-i386-64bit

1. open the Talon Log Viewer 
2. focus another application
3. open an imgui  (e.g., homophones or help)
4. note the log viewer will pop up above the active application; it does not steal focus though

**Comment by lunixbochs** [comment]
fixed in 0.3.1-512
