### ISSUE TITLE
[windows] talon-rust zoom mouse only works ~properly in upper left hand corner

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#579]
Version: 0.3.1-471-gf120, Branch: rust, OS: Windows-10-10.0.19045

- when triggering the zoom mouse in the upper left hand corner, it behaves as expected
- the further you move from the upper left hand corner, the smaller the region grabbed by the screenshot when zoom mouse is triggered
- eventually, no screenshot is seemingly displayed; this can be reliably reproduced by triggering the zoom mouse in the center of the screen

>>> ui.screens()
[Screen(x=0.0, y=0.0, size=(3840.0, 2160.0), mm=(525.000, 295.000))]

**Comment by lunixbochs** [comment]
should be fixed in 475
