### ISSUE TITLE
command, text input, and keystroke events/hooks

### ISSUE THREAD

**Issue by justin-roche** [talonvoice/talon#58]
there should be a central intercept point before input is passed to the mappings. this will allow for modifications to the undo/redo functionality.  it should capture things that are mapped and things that are not.

**Comment by lunixbochs** [comment]
new use case:

2shea:
> I want to have a command that means 'hit enter after the following command', so for example `get status` just spits out `git status`, but `run get status` will actually run the command... but i'm not sure how to do this.
getting sick of having to say `enter` after stuff all the time

me:
> I think the 'optimal' way of doing this would be to intercept phrase insertion, and modify the next phrase to have a newline
so what I'm hearing is a +1 for "hook the input system" and a new request for "pre/during/post command execution" event

**Comment by lunixbochs** [comment]
this is possible as of talon 0.1.x
