### ISSUE TITLE
[windows] talon-rust: stuck in waiting for scripts state

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#580]
Version: 0.3.1-471-gf120, Branch: rust, OS: Windows-10-10.0.19045

I'm not quite how to debug this, but  doesn't get past "Starting: Waiting for scripts"

Possibly worthless info:
- testing with multi-monitors seemed to cause a hard crash on start
- to eliminate variables, I removed all scripts from user
- now talon-rust doesn't get past "Starting: Waiting for scripts"
- re-adding user scripts didn't help
- I attempted to reinstall, but the issue persists. There's nothing in the talon log.
- Talon-QT starts without issue.

**Comment by lunixbochs** [comment]
is there anything in talon console?

**Comment by lunixbochs** [comment]
I think I reproed this, something to do with monitor enumeration.

**Comment by lunixbochs** [comment]
Should be fixed in 475
