### ISSUE TITLE
Talon-Rust: Detect that clipboard has changed

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#581]
On both qt and rust `clip.serial()` always returns `-1` on windows
On qt you have been able to do:
```
def update():
    global last_mime
    mime = clip.mime()

    if mime == last_mime:
        return
```

But this doesn't work anymore on Talon rust. I need at least one way to detect if the clipboard has changed.

**Comment by lunixbochs** [comment]
fixed in latest talon-rust, in both ways:

1. you can now compare mime() objects with `==` and `!=`
2. the serial works. however, you probably shouldn't trust the clipboard serials.

**Comment by AndreasArvidsson** [comment]
Both tested and are working on windows 11 :)
