### ISSUE TITLE
[windows] talon-rust: screenshots on secondary monitor only captures small portion of screen

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#583]
Version: 0.3.1-475-g97dd, Branch: rust, OS: Windows-10-10.0.19045

- [ ] "grab screen  < number > clip" does not work properly on non-primary monitors; it adds a screenshot of the requested screen to the clipboard.
https://github.com/knausj85/knausj_talon/blob/b11b773a46f4f299ddcce4f9f84a566e78d0bb14/plugin/screenshot/screenshot.py#L49

- [ ] "grab window clip" does not work properly on non-primary monitors; it adds a screenshot of the focused window to the clipboard.
https://github.com/knausj85/knausj_talon/blob/b11b773a46f4f299ddcce4f9f84a566e78d0bb14/plugin/screenshot/screenshot.py#L55

- [ ] "grab window clip" does not work properly when the active window spans multiple monitors

On the primary monitor, both commands behave correctly.

On the secondary monitor:

- the commands grab a tiny portion of the screen or window
- ![image](https://user-images.githubusercontent.com/15005956/226194880-871084c1-0b06-41cd-910b-5ad5d4911a3f.png)
- ![image](https://user-images.githubusercontent.com/15005956/226195201-529892f7-c5d1-4a1a-89e9-48099270e932.png)

when the window spans multiple monitors, grab window clip does something like this
![image](https://user-images.githubusercontent.com/15005956/226196192-4f808890-bacf-4199-a569-e28721a8bec7.png)

>>> ui.screens()
[Screen(x=0.0, y=0.0, size=(3072.0, 1920.0), mm=(345.000, 215.000)), Screen(x=3072.0, y=-465.0, size=(3840.0, 2160.0), mm=(525.000, 295.000))]

**Comment by lunixbochs** [comment]
should be fixed in latest talon-rust, please confirm
