### ISSUE TITLE
[windows] talon-rust: start on login does not appear to function

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#584]
Version: 0.3.1-475-g97dd, Branch: rust, OS: Windows-10-10.0.19045

as far as I can tell, checking the "start on login" option does nothing at the moment on windows

**Comment by lunixbochs** [comment]
I think it works, the checkbox just wasn't toggling. fixed in latest.

**Comment by knausj85** [comment]
This appears to be an issue for me as of -531.

I suspect this is overridden by whatever's in Settings -> Startup? Toggling Talon works there, but the state of the option doesn't match Talon's checkbox.

**Comment by lunixbochs** [comment]
I don't think there's a way for me to override the startup options once you set it there.
