### ISSUE TITLE
Unable to open REPL on MacOS in new Rust beta

### ISSUE THREAD

**Issue by pokey** [talonvoice/talon#590]
When I say "talon open repl", I get an error pop-up

```
“repl” can’t be opened because (null) is not allowed to open documents in Terminal.
```

<img width="263" alt="image" src="https://user-images.githubusercontent.com/755842/226968162-dfd32257-e757-4865-974f-43206a6a5ad4.png">

Environment info: `Version: 0.3.1-495-ge431, Branch: rust, OS: macOS-13.2-arm64-arm-64bit`

**Comment by lunixbochs** [comment]
fixed in -512
