### ISSUE TITLE
Talon pressing key behaves differently from keyboard (e.g. when OBS is not focused)

### ISSUE THREAD

**Issue by saidelike** [talonvoice/talon#591]
So I noticed that the hotkey for OBS on Windows works fine if it comes from my keyboard even if no focus on OBS. 

However when triggered from a voice command with talon, it only works when focus is on the OBS app, and otherwise nothing happen! This is a huge limitation. 

To replicate this, in OBS Settings > Hotkeys and e.g. set Start Recording to "F13". 

1) With a programmable keyboard, when hitting a key bound to F13, it starts the recording even if OBS is in the background.

2) Now creating a .talon file. This does not work without a focus on OBS and nothing happens (not even an error in the log window):

```
^(start|stop) recording$:
    key(f13)
```

3) This works but is far from ideal:

```
^(start|stop) recording$:
    user.switcher_focus("OBS Studio")
    key(f13)
    key(alt-tab)
```

**Comment by lunixbochs** [comment]
Does this work?
```
key(f13:down)
sleep(100ms)
key(f13:up)
```

I think it's an OBS bug, OBS won't respond to global hotkeys unless they're held down for longer.

**Comment by saidelike** [comment]
Indeed, it works. :D So closing this.
