### ISSUE TITLE
warning without associated location ("WARNING actions: skipped because they have no matching declaration")

### ISSUE THREAD

**Issue by rntz** [talonvoice/talon#601]
I've experienced warnings which occur after a context switch that have no corresponding location supplied:

```
2023-04-02 16:01:21 WARNING actions: skipped because they have no matching declaration: (user.emacs_command)
```

There is no line above this indicating which file caused it. It occurs when I switch focus to emacs, presumably because it brings something into context.

talon v0.3.1-63-g48c8 (63)
Mac Ventura

**Comment by lunixbochs** [comment]
implemented in next beta, for everything but apps/tags:
```
2024-01-03 01:19:30.000 WARNING lists skipped because they have no matching declaration:
    Context(user.ctx): user.foo
```
