### ISSUE TITLE
Canvas mouse events do not work on Linux

### ISSUE THREAD

**Issue by fatalerrorx** [talonvoice/talon#602]
I use the following code https://raw.githubusercontent.com/AndreasArvidsson/andreas-talon/master/imgui.py to display various  user interface elements in talon and after upgrading to the rust beta buttons are no longer clickable. On windows it seems to work fine. I am running manjaro Linux using KDE desktop.

**Comment by lunixbochs** [comment]
seems related to https://github.com/talonvoice/talon/issues/607
please comment if this is still an issue for you on the latest beta

**Comment by fatalerrorx** [comment]
Can confirm this still doesn't work.
