### ISSUE TITLE
[linux] talon-rust: canvas.focused = True does not work

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#607]
The [talon_ui_helper](https://github.com/splondike/talon_ui_helper) package uses key press events on a canvas instance to perform certain actions. To receive those key events I would set up an event handler, then focus the canvas using `talon.canvas.Canvas.focused = True`.

On the Rust beta 0.3.1-569-gc9a8 on Linux (i3 or GNOME3 DEs on Fedora 37) setting `focused` does not focus the canvas (so I can't receive key press events). It does work correctly on the same Talon version on OSX 13.3.1.

This can be seen (I think) in the 1st party Textarea window/widget; when shown (using e.g. `draft show` in knausj_talon) it does not show the input cursor or receive key input on Linux, but does on OSX. I've also made the following demonstration script:

```python
from talon import canvas
from talon.types import Rect

def events(type, *args):
    if type in ("draw", "mouse"):
        return
    print(type, args)

def _draw(can):
    can.clear("ffffffff")

talon_canvas = canvas.Canvas.from_rect(Rect(0, 0, 100, 100))
talon_canvas.register("draw", _draw)
talon_canvas.blocks_mouse = True
talon_canvas.register("", events)

# This focused setter works on OSX, but not Linux.
# I can use xdotool on Linux to emulate the setter, and then I get key events as expected:
# os.system("xdotool windowfocus $(xwininfo -root -children | grep Talon | awk '{print $1}')")
talon_canvas.focused = True
```

The canvas in this script receives focus on OSX and prints out key events. On Linux it does not.

**Comment by lunixbochs** [comment]
is this a panel canvas?

**Comment by splondike** [comment]
The code in the talon_ui_helper package should be equivalent to the example script. I tried setting `talon_canvas.panel = True/False` on the above and it didn't seem to make a difference in i3.

**Comment by lunixbochs** [comment]
can you try again on beta 574? you might need to set canvas.panel = True

**Comment by splondike** [comment]
It's a bit better, but not working yet. Observations:

* Can only successfully use .focused=True to focus the canvas under GNOME3, not under i3.
* Only consistent way to get it to focus is to reboot Talon and have focused = True and panel = True set. I sometimes get it to focus after Talon has been running (retriggering an attempt by saving my test file and letting the Talon autoloader retry things). I can't work out a consistent method to achieve this however.
* Focus gets set if and only if I get a move event prior to the (focus, True) event (using the above demo code).
* If I use the xdotool code to focus the canvas under i3, then I get the (focus, True) event, but not the mouse event. I can then receive key press events.
* Sometimes I get the stack trace below, but I don't get it most of the time. Not sure it's related.

```
2023-04-26 22:12:28 ERROR failed to get window info (update_windows)
   12:                     lib/python3.9/threading.py:937| 
   11:                     lib/python3.9/threading.py:980| 
   10:                     lib/python3.9/threading.py:917| 
    9:                         talon/linux/xclient.py:479| 
    8:                         talon/linux/xclient.py:375| # [stack splice]
    7:                         talon/linux/xclient.py:249| 
    6:                         talon/linux/xclient.py:233| 
    5:                         talon/linux/xclient.py:223| 
    4: lib/python3.9/site-packages/xcffib/__init__.py:333| 
    3: lib/python3.9/site-packages/xcffib/__init__.py:579| 
    2: lib/python3.9/site-packages/xcffib/__init__.py:666| 
    1: lib/python3.9/site-packages/xcffib/__init__.py:657| 
xcffib.xproto.DrawableError
```

**Comment by lunixbochs** [comment]
are you saying it works every time in gnome, and i3 does not work most of the time?

the ability for us to force focus on a window in i3 might depend on your settings.

does keyboard input work fine in all cases now if you manually click on the window?

**Comment by splondike** [comment]
Yesterday I meant it only sometimes worked under GNOME (only reliably in the condition of my second dot point), and never under i3. However today on -574 I retried in GNOME and it seems to be ~100% reliable :confused:. I managed to have it fail once I think, but wasn't able to reproduce that again. I get those stacktraces under GNOME still when reloading my test file, but since the feature works there they seem to be unimportant. -571 still fails on GNOME, so I guess you fixed something in -574. I can click to focus under GNOME.

It still never works under i3 however, and I can't click to focus. In case it helps I dumped the `xprop` for the canvas under 0.3.1 (public) and -574 when run under i3 below:

0.3.1(public)
```
_NET_WM_USER_TIME(CARDINAL) = 5047572
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_STAYS_ON_TOP
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = 
_NET_WM_NAME(UTF8_STRING) = "Talon"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x180000e
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		window id # of group leader: 0x180000e
WM_CLIENT_MACHINE(STRING) = "jigsaw"
_NET_WM_PID(CARDINAL) = 26445
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 25165837
WM_CLASS(STRING) = "talon", "Talon"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		user specified size: 100 by 100
		window gravity: Static
```
-574
```
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 800 by 600
		program specified minimum size: 100 by 100
		program specified maximum size: 100 by 100
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY
WM_CLIENT_MACHINE(STRING) = "jigsaw"
_NET_WM_PID(CARDINAL) = 26694
WM_CLASS(STRING) = "talon", "talon"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "Talon Canvas"
WM_NAME(STRING) = "Talon Canvas"
```

I tried manipulating the properties of the -574 window using `xprop -id <id> -set <prop> <prop value>` to see if I could work out if this was the problem. I think I successfully set WM_PROTOCOLS and _NET_WM_WINDOW_TYPE to match the public values with no success (though it all felt a bit flaky). I wasn't able to set WM_HINTS however (figuring out xprop was a bit hard), that's my best guess about what's missing.

**Comment by lunixbochs** [comment]
fixed on next beta
