### ISSUE TITLE
not able to disable context group right after load

### ISSUE THREAD

**Issue by christianhultin** [talonvoice/talon#61]
the following code does not seem to work:
```
dictate_group = ContextGroup('dictate')
dictate = Context('dictate', group=dictate_group)
dictate_group.load()
dictate_group.disable()
```
More explicitly, it is able to load the new context group "dictate_group"  but does not disable it. However if i disabled the context group at a later stage, say with a keyword, it works quite brilliantly. It seems like a timing issue

**Comment by lunixbochs** [comment]
this is not a problem in the beta, which uses an enabled flag instead of stateful functions
