### ISSUE TITLE
[linux] Talon-Rust: mouse-zoom unreadable due to brightness/translucency

### ISSUE THREAD

**Issue by Kn0rk** [talonvoice/talon#610]
Talon (beta) Build:
114-0.3.1-
57
571
574

System:
Ubuntu 22.04 X11 with i3

As seen in the video the zoom window is increasing the brightness and is half translucent.

https://user-images.githubusercontent.com/12850488/234552067-16323a08-f7ad-4393-b8ff-e9dacc07964a.mp4

Going back to running version 114-0.3.1-63-g48c8 resolves the issue.

**Comment by lunixbochs** [comment]
fixed in next beta
