### ISSUE TITLE
ERROR cannot get _NET_CURRENT_DESKTOP

### ISSUE THREAD

**Issue by saidelike** [talonvoice/talon#614]
Ubuntu 22.04
Talon beta 0.3.1-597-gbbe9

I get this error when running talon with `run.sh`

```
2023-05-10 12:32:38 ERROR cannot get _NET_CURRENT_DESKTOP
   11:           app/resources/loader.py:152| 
   10:                 talon/__init__.py:43 | 
    9:       talon/scripting/__init__.py:17 | 
    8:  talon/scripting/speech_system.py:12 | 
    7: talon/experimental/screen_lock.py:1  | 
    6:                       talon/ui.py:226| 
    5:                 talon/linux/ui.py:378| 
    4:                 talon/linux/ui.py:33 | 
    3:            talon/linux/xclient.py:104| 
    2:            talon/linux/xclient.py:428| # [stack splice]
    1:            talon/linux/xclient.py:178| 
AttributeError: failed to fetch property
```

Talon works fine otherwise.

**Comment by saidelike** [comment]
NOTE: I am using the default window manager which is GNOME and wayland window manager (https://www.tuxedocomputers.com/en/Whats-the-deal-with-X11-and-Wayland-_1.tuxedo):

```
$ echo $XDG_SESSION_TYPE
wayland
```

**Comment by saidelike** [comment]
I can confirm that by switching to using X instead of wayland (following https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-22-04-desktop) that the error disappears.

```
$ sudo vim /etc/gdm3/custom.conf 
```

```
[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false
```


Since X is recommended for using talon, since otherwise not everything works (e.g. my terminal wasn't known and `focus terminal` wasn't working with wayland and now with X it works), it should probably just say that instead. Or at least this issue documents it.

**Comment by lunixbochs** [comment]
I'm unwilling to do wayland specific work until wayland is capable of full Talon support, so I'm closing this.
