### ISSUE TITLE
on_pop() to click changing primary click settings [Windows 11]

### ISSUE THREAD

**Issue by matthew-hagemann** [talonvoice/talon#615]
Talon: 0.3.1
System: Windows 11

I have the mouse buttons reversed on Windows 11 (Right is now primary click). When using on_pop() to click, the primary mouse click is reverted on my mouse back to the left mouse button.

Steps to reproduce:
1. By default, left is primary click, right is secondary.
2. Update mouse settings to set right click as primary. On Windows 11: Settings -> Bluetooth & devices -> Mouse -> Primary click -> Right
3. Set on_pop() to perform primary click . I am using knausj_talon, so the code looks something like this in `/plugin/mouse/mouse.py`:
```
@ctx.action("user.noise_trigger_pop")
def on_pop():
        ctrl.mouse_click(button=0, hold=16000)
```
4. Use pops to click the primary mouse button (10-20 times should do it).
5.  In settings, primary click is still showing as right, however has reverted back to left click if I use my mouse. 

Things that do not trigger the primary key to swap:
1. Using the mouse with Talon closed.
2. Using the mouse with Talon open but not popping.

I am currently getting around this issue by using X-Mouse Button Control to change right mouse to left and left to right, so it definitely feels like there is something funny going on with the interaction with Windows 11 and its mouse button settings.

It's a weird one, let me know if you would like any further details!

**Comment by lunixbochs** [comment]
fixed in beta v0.3.1-600
