### ISSUE TITLE
Icon disappears on windows 11

### ISSUE THREAD

**Issue by FireChickenProductivity** [talonvoice/talon#619]
The tray icon occasionally disappears on windows 11. Talon Version: 0.3.1-604-g7a0a, Branch: beta, OS: Windows-10-10.0.22621. 

This might be triggered by talon wake or sleep.

**Comment by lunixbochs** [comment]
if anyone has a recurring repro for this, if you can launch Talon via Talon Console and check it for any output around the time of the icon disappearing, that might help me track it down

**Comment by lunixbochs** [comment]
Is this happening still on latest beta?

**Comment by Reederoo** [comment]
I experienced the talon tray icon disappearing on windows 10 today. Unfortunately I don't know how to reproduce it. It's only happened once so far to me. Using version 663

**Comment by lunixbochs** [comment]
fixed in next beta
