### ISSUE TITLE
Mouse Jump enabled while Head Control is enabled

### ISSUE THREAD

**Issue by eemmtt** [talonvoice/talon#622]
Talon 0.3.1-652-g67d6
Windows 10

I'm getting Mouse Jump behavior in addition to Head Control with the pictured settings:
![image](https://github.com/talonvoice/talon/assets/52972088/b91625ef-b0e6-43ce-a5df-63962ff7204c)

With Head Control turned off there is no Mouse Jump:
![image](https://github.com/talonvoice/talon/assets/52972088/8dc0485e-967e-4f5c-94b9-9df178e5d28a)

**Comment by lunixbochs** [comment]
@eemmtt Oh! I think you may misunderstand what the settings are intended to do. Mouse Jump is talking about teleporting the cursor when you move your physical mouse. Head Control is a special mode for controlling the mouse on the entire screen, not just with relative motion in a small region.

- Eye Control - if you look somewhere on the screen, the mouse cursor will move there (unless head tracking or your physical mouse are actively moving the mouse)
- Head Control - if you move your head, the mouse moves in a relative area. If you are not looking near the mouse cursor, and you move your head, the mouse cursor will teleport to where you are looking.
- Mouse Jump - if you are not looking near the mouse cursor, and you move your physical mouse, it will teleport to where you are looking.
- Gaze Focus - this focuses apps when you look at them, it's unrelated to mouse movement.

**Comment by eemmtt** [comment]
Ah! Thanks for clarifying--
It would be helpful to have a Head Control mode without the teleport functionality (or #544 ) for "hover to inspect" type interactions which display information away from the cursor.

**Comment by lunixbochs** [comment]
When you have gaze control disabled, the teleport should only happen if you move your head. So if you hold your head still you should be able to read tooltips.
