### ISSUE TITLE
zoom mouse takes focus

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#623]
Version: 0.3.1-662-g6fcb, Branch: beta, OS: Windows-10-10.0.19045

I'm not sure whether this is a bug or feature, but I noticed the canvas for the zoom mouse takes focus from the active application. 

This causes issues with features like Andreas quick pick (https://github.com/AndreasArvidsson/andreas-talon/tree/master/plugins/quick_pick) which can snap windows to a given location and currently relies upon ui.active_window(). Instead of attempting to resize the expected window, it will attempt to resize the talon canvas and fail when selected via the zoom mouse. 

The simple workaround is to cache the active window when the quick pick comes up.

**Comment by lunixbochs** [comment]
is this fixed in 389?

**Comment by knausj85** [comment]
Verified fixed in Version: 0.4.0-389-g05a6, Branch: beta, OS: Windows-10-10.0.19045
