### ISSUE TITLE
Stream decks are reconnected on unlock even without a `deck()` definition

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#631]
I think the intention of the Stream Deck support is that if the user has Stream Decks but doesn't add a `deck()` definition to any Talon file, Talon won't try to connect to the deck. This is useful because connections to the decks are exclusive (unlike gamepads, etc.), so if the user wants to use the native software (or any other framework for managing them) and Talon at the same time, they still can, simply by deciding whether to define such a statement.

This logic seems to work fine, except in the case of unlocking the computer (or perhaps resuming from sleep?). In this case, Talon appears to try to reconnect to decks even if there aren't any `deck()` statements defined. 

This has an unfortunate effect of racing with the official Stream Deck software, and Talon often wins the race, breaking the official software's connection. Unfortunately, AFAIK, the only way to fix this scenario is to restart both Talon (to release its connection) and the Stream Deck software (to make it reacquire it), which is pretty messy. Users also may not realize the source of the problem if they had a stream deck, were using the official software, and upgraded to the beta. They would simply notice that their deck becomes unresponsive after unlocking occasionally.

I currently hit this and have to restart Talon about once a day on average because of this, which isn't terrible, but I imagine others are running into it.

**Comment by lunixbochs** [comment]
this should be fixed in current beta, let me know if it's not.
