### ISSUE TITLE
Talon system tray icon disappears (crashes) immediately after starting

### ISSUE THREAD

**Issue by dennischenfeng** [talonvoice/talon#635]
Steps to reproduce:
1. Install Talon from the official website, for Windows
2. In windows settings, ensure that the Talon icon shows in the system tray area (ensure it's not hidden).
3. Start Talon app by double-clicking desktop icon
4. I notice that the icon appears for 1 second and then disappears. The icon that appears is the Talon logo with a slash through it (which I believe just denotes sleep mode)
5. I tried running the Talon app as administrator (right-click desktop icon and do Run as Admin), but same results.
6. I tried restarting computer and retrying, but same results
7. I tried uninstalling, then restarting, then re-installing, but same results.
8. I tried to look for any .log file in the %APPDATA%\talon folder, but none existed.

Any ideas for troubleshooting steps? 
Because the system tray icon crashes, I can't really access any further steps in the installation process (like installing the speech system).

My system: Windows 11 Home, version 22H2 (latest update as of today)

**Comment by lunixbochs** [comment]
Look in the windows event log for an application crash, post the text summary here.

Enable crash dumps (minidumps) and send me the one for Talon if it's crashing.

**Comment by dennischenfeng** [comment]
Thanks for the quick response!

Here's the text summary of the event viewer crash:
"""
Faulting application name: talon.exe, version: 1.0.0.0, time stamp: 0x00000000
Faulting module name: atio6axx.dll, version: 31.0.12044.3, time stamp: 0x63582573
Exception code: 0xc0000005
Fault offset: 0x0000000000131cc2
Faulting process id: 0x0x25C8
Faulting application start time: 0x0x1D9F89C471DCC65
Faulting application path: C:\Program Files\Talon\talon.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0386187.inf_amd64_e45f6929dd019ce6\B385477\atio6axx.dll
Report Id: 74219a46-0065-44ae-bc32-acfc2991a1ce
Faulting package full name: 
Faulting package-relative application ID: 
"""

I also tried to find a minidump file (unfamiliar with this concept before today), so I followed the "Enable memory dump setting" section of 
https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/generate-a-kernel-or-complete-crash-dump
And I tried to find the Minidump file in `%SystemRoot%` but didn't find any.

Does that help diagnose the problem? Please let me know if I can give any more info.

**Comment by lunixbochs** [comment]
atio6axx.dll is your GPU driver crashing, maybe update it.
someone in a quick google search says the AMD Adrenalin software causes driver crashes as well.

the crash dump page you found looks like it's for full system crashes (blue screens), not application crashes.

**Comment by dennischenfeng** [comment]
Thank you!
Indeed I uninstalled and reinstalled the AMD Radeon software (Adrenalin) and Talon is working now.
