### ISSUE TITLE
"Could not get window rect" after restarting Brave

### ISSUE THREAD

**Issue by davidsgrogan** [talonvoice/talon#636]
After I restart Brave to get an updated version, talon throws an exception getting the window rect. (Fairly certain I've seen this with Chrome too.)

To reproduce:
1. Go to URL chrome://restart
2. Wait for browser to restart
3. In talon repl: `actions.sleep("3s"); ui.active_window().rect`
4. Focus Brave/Chrome in those 3 seconds
5. repl now shows
```
>>> actions.sleep("3s"); ui.active_window().rect
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "talon/mac/ui.py", line 285, in rect
AttributeError: Could not get window rect.
```

I'm on public 0.4.0 on macOS 13.6.

**Comment by lunixbochs** [comment]
Does this issue go away after brave has been running for a bit?

**Comment by davidsgrogan** [comment]
Yesterday this reproduced 10/10 times. Now it it doesn't reproduce at all. 😕 

So I'm not yet able to answer.

**Comment by lunixbochs** [comment]
Typically this happens because the app doesn't have Accessibility "working" yet when it starts. In that case, Talon will retry repeatedly to acquire accessibility access to the app.

**Comment by davidsgrogan** [comment]
Yeah, this seems to resolve after a while.
