### ISSUE TITLE
Licencing info is missing

### ISSUE THREAD

**Issue by ebardie** [talonvoice/talon#638]
https://talonvoice.com/ has a non-clickable "Licencing Agreement" line.

I don't see any info in the website about the availability of source code or licencing.

Please could you be a little more explicit on these subjects?

**Comment by lunixbochs** [comment]
That link is clickable for me on every major browser. It's a basic anchor tag with no javascript. The app also shows you the license agreement when you run it, and the About window inside the app shows license information as well.

**Comment by ebardie** [comment]
Not sure why the link wasn't working here, it is now. Sorry for the time sink 🙏
