### ISSUE TITLE
clip.MimeData adds multiple Mac pasteboard items

### ISSUE THREAD

**Issue by nriley** [talonvoice/talon#642]
I'm implementing an action that copies a link to a URL as RTF, with (e.g.) a web page title as the link text.

I'd like it to also include the text of the URL so pasting in a destination app that doesn't support RTF still preserves the URL. But when I do this, Talon adds the text as a 2nd pasteboard item, rather than an alternative data type for the first item.

Here's an example with HTML (as the syntax is a bit easier to parse than RTF).

```py
>>> x = clip.MimeData()
>>> x.html = '<a href="https://talonvoice.com/">Talon</a>'
>>> x.text = 'https://talonvoice.com/'
>>> clip.set_mime(x)
```

This is what it looks like in [Pasteboard Viewer](https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12):

<img width="388" alt="image" src="https://github.com/talonvoice/talon/assets/68303/3f94768a-9756-4c19-a190-fdc155f624ce">

And if I paste into (say) TextEdit, I get both items together:

> https://talonvoice.com/
> [Talon](https://talonvoice.com/)

It would be more helpful if `clip.MimeData` added multiple data types (e.g., plain text, HTML, RTF) to a single NSPasteboardItem as alternatives, like this:

<img width="126" alt="image" src="https://github.com/talonvoice/talon/assets/68303/cbffa746-bcf3-4800-b89e-60252915a936">

**Comment by lunixbochs** [comment]
fixed in next beta
