### ISSUE TITLE
Dictation mode doesn't show in the menu bar menu on macOS unless enabled via voice.

### ISSUE THREAD

**Issue by YousufSSyed** [talonvoice/talon#645]
Right now on Mac the only way to turn on dictation mode is by saying "dictation mode" and then it shows up.
<img width="260" alt="Screenshot 2023-12-07 at 3 53 37 AM" src="https://github.com/talonvoice/talon/assets/42646062/3601df90-c39a-4236-8391-9e18ad5ed875">
<img width="259" alt="Screenshot 2023-12-07 at 3 53 46 AM" src="https://github.com/talonvoice/talon/assets/42646062/d16d1737-bafe-4626-b727-6c03afa462fe">

**Comment by lunixbochs** [comment]
fixed in next beta
