### ISSUE TITLE
certain talon settings don't appear in debug window

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#652]
Version: 0.4.0-241-g6957, Branch: beta, OS: Windows-10-10.0.22621

I happened to notice that these settings don't appear in the fancy debug window, which is a bit unfortunate

insert_wait
key_hold
key_wait

**Comment by lunixbochs** [comment]
are you sure they're set?

**Comment by lunixbochs** [comment]
unset-settings (ones using default values) didn't appear in registry.settings, fixed in next beta
