### ISSUE TITLE
TextArea does not respond to left/right/up/down keys

### ISSUE THREAD

**Issue by rntz-rai** [talonvoice/talon#655]
```
from talon.experimental import textarea
a = textarea.TextArea()
a.show()
```

Click on the resulting window. Enter some text (this works). Press left/right/up/down (nothing happens). Similar for derived keys, eg `shift-left` or `cmd-shift-left`.

Mac OS Sonoma  14.4.1
talon 0.4.0-322-gf6ba

**Comment by rntz** [comment]
(created this issue with my work account by accident, oops)

This affects the community repo's draft window, for instance.

**Comment by lunixbochs** [comment]
thanks for the report! looks like winit renamed these from e.g. Left -> ArrowLeft. fixing this by renaming them back.
