### ISSUE TITLE
Mouse jump needs an action to trigger it manually

### ISSUE THREAD

**Issue by MoocowTG** [talonvoice/talon#659]
I'd like to use the mouse jump feature but I'm unable to trigger it manually as there is no action to do so.

Toggling gaze control for 50ms is a workaround, but this does not work as well as mouse jump, as gaze tracking seems to fail at the edges of your screen. Mouse jump will place your cursor at the nearest edge, but toggling gaze will fail to place it at all.

I'd like to request a tracking.control_mouse_jump() action to trigger the same thing as moving the mouse would do when mouse jump is enabled.

**Comment by lunixbochs** [comment]
just shipped in the beta, see the beta release notes
