### ISSUE TITLE
macOS: canvas emojis don't correctly render

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#662]
I tried setting a few different `paint.typefaces` (`Helvetica`, `Arial`, `.AppleSystemUIFont`), in addition to the default, but they all render as square boxes:

<img width="222" alt="Screenshot 2024-08-14 at 1 36 50 PM" src="https://github.com/user-attachments/assets/3a6a45ed-70a7-442b-8e02-4b7a262ee6cf">

**Comment by lunixbochs** [comment]
```
paint.typeface = "Apple Color Emoji"
```

**Comment by phillco** [comment]
Thanks. Is it possible to combine emoji and text in a single `draw_text` call, or do they have to be separate, with separate fonts?

**Comment by lunixbochs** [comment]
I took a quick look and didn't see anything for that
