### ISSUE TITLE
Should `NoValueType` (returned from `settings.get(id, default)` if there's no default on the setting) be falsy?

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#669]
Otherwise `if settings.get("user.private_cursorless_use_preferred_scope", False):`, if there's no default on the setting itself, won't actually work the way people think.

Or is getting `NoValueType` here even correct?

See https://github.com/cursorless-dev/cursorless/pull/2687

**Comment by lunixbochs** [comment]
triaged and fixed this - it was due to recent registry changes in the beta only causing the NoValue default to end up as a value in registry.settings

fixed in beta 521. users should never see NoValue.
