### ISSUE TITLE
[windows] Full screen canvas has black background

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#670]
On Windows if I create a full screen canvas using the code below it will draw an opaque black window covering the screen. I am able to draw on top of this canvas (e.g. a coloured rectangle), just the initial colour is black+opaque. If I adjust the x/y/width/height of the canvas by 1 pixel then the initial canvas is fully transparent and can still be drawn on.

```python
from talon import canvas, cron, ui
from talon.types import Rect

def _paint(canvas):
    pass

can = canvas.Canvas.from_rect(ui.main_screen().rect)
can.register("paint", _paint)
can.show()
can.freeze()
# Hiding so that I can use the computer again, otherwise the full screen opaque overlay makes that impossible.
cron.after("2s", can.hide)
```

This is an annoyance because I can't have a full screen transparent overlay without the hack of adjusting one of the dimensions by 1 pixel. 

System details: Can reproduce on Talon version 0.4.0 (public) and 0.4.0-521 (beta). Using Windows 11 (bare metal, no VM). My screen resolution is 1920x1080 and I'm using the Intel UHD Graphics 630 GPU with I think native Windows drivers (that came with factory reset Optiplex 3070). Can't reproduce on PopOS Linux in a VM on the Optiplex or OSX on a M1 Macbook Pro.

**Comment by lunixbochs** [comment]
This is an issue in Windows, not Talon. You can't create a transparent overlay that is exactly the size of a monitor or Windows switches to fullscreen mode and blanks the desktop. Use Canvas.from_screen.
