### ISSUE TITLE
mouse_click(1) does not work properly on xfce4

### ISSUE THREAD

**Issue by thislgtm** [talonvoice/talon#674]
### Description
For external hardware it is important to remap keys onto actions. Since Talon [supports](https://talon.wiki/customization/talon%20library%20reference/key_action/) only few [keys](https://github.com/torvalds/linux/blob/059dd502b263d8a4e2a84809cf1068d6a3905e6f/include/uapi/linux/input-event-codes.h#L75) I remapped external functionality to mimic some rarely used key combinations like `super-f11`.

When using the mouse through talon the right click does not work in a custom talon file.

### Setup
* OS: Archlinux 6.12.4
* Window manager: xfce4

### Reproduce
1. `$ echo "key(super-f11): mouse_click(1)" > ~/.talon/user/test.talon`
2. Run talon.
3. Press super+f11

### Behavior
Context menu (default right click behavior) does work in certain GUI applications like browser but not in i.e. xfce4 window manager i.e. in xfce4-terminal. 

Some GUI elements/apps seem to have strange behavior with `mouse_click(0)` such as the main application menu button in xfce4. It looks mouse clicked and stays as such without opening the menu.

![image](https://github.com/user-attachments/assets/ac97ed48-7a94-4b50-a372-7a2a202bedca)
**unclicked**

![image](https://github.com/user-attachments/assets/374fed36-a622-4800-b02b-994f604b8db5)
**clicked**

![image](https://github.com/user-attachments/assets/3ca8457e-5a21-45a2-8035-a26f5a8ae6a0)
**mouse_click(0)**

### Expected Behavior
Right click works in every GUI application.

### Solution
No idea ;-;

**Comment by timo** [comment]
please try using `key(super-f11:up)` instead of just `key(super-f11)` to cause the mouse click. it's very possible that these programs are just not accepting super + mouseclick, since by the time talon clicks, you're still holding down the super key

**Comment by thislgtm** [comment]
> please try using `key(super-f11:up)` instead of just `key(super-f11)` to cause the mouse click

Thank you for the quick reply. This works once. But no further click is recognized until I click manually with the hardware mouse.

> it's very possible that these programs are just not accepting super + mouseclick, since by the time talon clicks, you're still holding down the super key

Manually holding super and clicking works as one would expect.

**Comment by lunixbochs** [comment]
I think super-f11:up runs when you release f11, not when you release super
you might have luck doing key(super:up) to release super in your handler

**Comment by thislgtm** [comment]
That does not work.
 
Basically the same problem as in [this issue](https://github.com/talonvoice/talon/issues/675#issuecomment-2564550334). Some keys are only for premium users.

**Comment by lunixbochs** [comment]
> Some keys are only for premium users

Show some respect. This is a free support area for a free privacy-preserving product.

Anyway I checked and f35 has always been in the key list, if the keycode is not found then it's probably just missing from your xmodmap / x11 keyboard layout.

**Comment by thislgtm** [comment]
I apologize.

You are doing a great job. Setting up a hands free environment can be frustrating ;-;

**Comment by thislgtm** [comment]
Anyway I can not get things to work. I tried with F2 key:
```
key(f2:up): mouse_click(0)
```
I can only click something once. Then I have to click using the mouse to be able to click again with F2.

Another experiment is this:
```
key(f4:down):
    print("down")
    key(backspace:down)

key(f4:up):
    print("up")
    key(backspace:up)
```
while the prints reflect exactly what is expected, backspace is not triggered at all :/ I tried to figure out how to install the keyboard package in the talon venv to debug this or implement it myself, but the activate script is missing or at least I am used to having one.

**Comment by lunixbochs** [comment]
reliable keypress production from within hotkey handlers in talon isn't really a goal, especially on linux. it's really annoying to get right and there are much higher priorities. even if you shelled out to xdotool you'd likely see similar issues as long as the hotkey handler is executing. if you really want to do this with talon, my recommendation would be to use python and the cron api and try to find a way to run your code after you've released all of the keys on your keyboard.

**Comment by thislgtm** [comment]
I ordered the tobii 5 eyetracker will I have the same problem with that?

Will stream deck pedals suffer from the same press/release issue with talon beta?

**Comment by lunixbochs** [comment]
no, the tobii 5 and stream deck don't use the hotkey handler

the issue you're running into is we're in the middle of handling a hotkey from x11, with keys pressed on your keyboard, while attempting to generate new key presses. most platforms have issues when you try to do this.
