### ISSUE TITLE
`insert()` does only work when speech is used

### ISSUE THREAD

**Issue by thislgtm** [talonvoice/talon#675]
### Description
Using key as input trigger ignores `insert()` without notice.

### Setup
* OS: Archlinux 6.12.4
* Window manager: xfce4

### Reproduce
1. `$ echo 'key(super-b): insert("test")' > ~/.talon/user/test.talon`
2. Run talon.
3. Press super+b

### Behavior
Nothing happens.

### Expected Behavior
Prints `test` at cursor.

NOTE: This _does_ work when using speech as input trigger such as `some words: insert("test")`

### Solution
?

**Comment by timo** [comment]
please try the same suggestion i posted on #674 - talon is probably pressing the keys to write "test" while you're still holding super, so the effect is that super-t, super-e, super-s, then super-t are being pressed

**Comment by thislgtm** [comment]
I was able to add a little delay of fifty milliseconds in order to confirm your suggestion. It would be nice to have [KEY_MACRO1](https://github.com/torvalds/linux/blob/059dd502b263d8a4e2a84809cf1068d6a3905e6f/include/uapi/linux/input-event-codes.h#L693)-30 available such that we 1) don't interfere with mapped keys 2) do not need modifier keys to find rarely used keys combos.

Thank you for solving my problem. You want me to create a new issue on that topic as a feature request?

**Comment by lunixbochs** [comment]
does KEY_MACRO1 have an x11 code? we're not operating at the kernel layer, see keysymdef.h and XF86keysym.h

**Comment by thislgtm** [comment]
> does KEY_MACRO1 have an x11 code? we're not operating at the kernel layer, see keysymdef.h and XF86keysym.h

Unfortunately not. But I figured that Linux implements KEY_F13-24 which doesn't seem to work with talon:
```
key(f23): "test"
```
results in:
> ValueError: could not find keycode for key: 'f23'

But these could be implemented since there are XK_F1-30 in x11.

**Comment by lunixbochs** [comment]
talon has up to f35 on the beta already

**Comment by thislgtm** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by thislgtm** [comment]
In case someone ends up here:

```
$ echo 'key(f13): "test"' > ~/.talon/user/test.talon
$ echo "keycode 183 = F13" > override.xmodmap
$ xmodmap override.xmodmap
$ talon # start talon
# Press whatever mapped F13 
```

In order to permanently change the xmodmap see i.e. https://wiki.archlinux.org/title/Xmodmap#Custom_table

Unfortunately this will not resolve issues with talons key handling:
```
# This will only allow to click once.
key(f13:up): mouse_click(1)

# The following will fire on key up event.
key(f13:down): key(backspace:down)

# This and late backspace:down will end up in deletion of key press before action.
key(f13:up): key(backspace:up)
```

**Comment by lunixbochs** [comment]
I repeat: what you're doing (sending input from inside a hotkey event) is not a current goal of talon's hotkey system, especially on linux.

I expect if you call a tool like xdotool while the hotkey handler is running, it will have the same problem as using talon to simulate the event.
