### ISSUE TITLE
contexts should be able to match against the url of a browser

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#71]

**Comment by lunixbochs** [comment]
accessibility API is coming which will facilitate this for accessible browsers. for non-accessible browsers, will need to write browser plugins.

**Comment by dwiel** [comment]
The accessibility api is not in this latest release?

**Comment by lunixbochs** [comment]
should be there but it's not finalized, so I might need to make breaking changes still

**Comment by dwiel** [comment]
Gotcha

**Comment by lunixbochs** [comment]
This is possible in the beta in multiple ways. You can implement `actions.browser.address` and `actions.browser.title` (perhaps using the window title, or accessibility api)
```
@ctx.actions_class('browser')
class Actions:
    def address() -> str:
        return page address
    def title() -> str:
        return page title
```

and scope match in talon files with these keys:

```
'scheme': parsed.scheme,
'host': parsed.netloc,
'port': parsed.port,
'path': parsed.path,
'url': url,
```

e.g.

```
browser.scheme: https
browser.host: google.com
browser.url: https://google.com/...
```
