### ISSUE TITLE
Uninstall languages  Problems

### ISSUE THREAD

**Issue by mgmmgm14** [talonvoice/talon#74]
I can not delete languages ​​from the voice engine in the captain, when he tried to delete English United States this error appears in the log

[], 'ts': 2188301495}
2018-11-15 14:58:58    IO From cffi callback <function on_menu at 0x000000010a9a6f20>:
2018-11-15 14:58:58    IO Traceback (most recent call last):
2018-11-15 14:58:58    IO   File "talon/menu.py", line 168, in on_menu
2018-11-15 14:58:58    IO   File "talon/menu.py", line 47, in __call__
2018-11-15 14:58:58    IO   File "/Applications/Talon.app/Contents/Resources/talon_plugins/speech.py", line 216, in lang_download
    self.menu.remove(self.active_langs.pop('en_CA'))
2018-11-15 14:58:58    IO KeyError: 'en_CA'

and the menu starts to get  bugy
aegis [15:02]
Yeah sorry about the menu bugginess (editado)
I have a change set planned that will make it more reliable

Does it still fail if you restart talon?
Mauricio [15:04]
the menu is fixed if I restart  talón, but I can never delete any language
it's a problem because I can not put to default the Spanish from the start
aegis [15:05]
I understand
If you go into system preferences and enable dictation
You can enable then delete English from there (editado)
Since I use the Mac dictation dataset in talon
Mauricio [15:07]
there is no English in the dictation of Mac  on my computer
aegis [15:07]
Enable. Then delete.
You need to turn english on, even if that means “installing english” which will install nothing.
Mauricio [15:14]
I had to uninstall in Mac options, I had done it before but the problem is that English United States is mapped to English Canada in talón, Then I had to install and uninstall English Canada.

I tried to install it and uninstall it again and it keept doing the same, it's not important because I already know how to fix it, doing what you said in the Mac options. I'm telling you so you can keep it in mind in the future.

**Comment by lunixbochs** [comment]
should be fixed in next beta
