### ISSUE TITLE
Webview transparency/translucency

### ISSUE THREAD

**Issue by nickvisut** [talonvoice/talon#75]
Currently, there is no setting to adjust the transparency of web views, either 1) the background or 2) the web view as a whole.

Use case: plug-ins or scripts could make use of overlays without sacrificing screen real estate, or at least mitigating the usage of screen real estate.

Note: a good step in this direction could be to allow at least for 1) just the main web view background to be 100% transparent, allowing overlays to then selectively apply transparency to children/descendants with CSS. This could be in addition to 2) allowing for the entire webview to be user-configurable in translucency.

**Comment by lunixbochs** [comment]
webview is being deprecated for multiplatform, you can make transparent canvases, and imgui can be used for layout.
