### ISSUE TITLE
Tracker not working after sleep/wake

### ISSUE THREAD

**Issue by lkjh654** [talonvoice/talon#79]
Tracker stops working after sleep/wake

version: 0.0.8.23
sleep method: triggered by the system after a period of inactivity
tracker plugging method: USB Hub (Satechi TYPE-C PRO HUB ADAPTER)
is the screen closed: No
how long is it asleep: 10 minutes
log:
 
```KeyError: '$data'
2019-01-10 15:04:26 ERROR cb error topic="screen_wake" cb=<function <lambda> at 0x0000000113d6db00>
    3:              talon/rctx.py:133|
    2: talon_plugins/eye_mouse.py:560| ui.register('screen_wake', lambda e: t..
    1:               talon/eye.py:163|
KeyError: '$data'```

**Comment by lunixbochs** [comment]
Talon has some mitigations for this now. If it's still happening, try removing USB hubs from the equation, then let me know.
