### ISSUE TITLE
Dragon: window moves/resizes don't always work the first time

### ISSUE THREAD

**Issue by wizonesolutions** [talonvoice/talon#80]
When using Talon to maximize a window, it can sometimes take three or four times to succeed.

Sample code:
````python
def resize_window(x, y, w, h):
    print("Resizing: ", x, y, w, h)
    win = ui.active_window()
    rect = win.screen.rect.copy()
    rect.x += rect.width * x
    rect.y += rect.height * y
    rect.width *= w
    rect.height *= h
    win.rect = rect
````

@lunixbochs has said that this is due to Dragon Enhanced Accessibility.

I can reproduce with Slack but not with PyCharm. I was using it with `1, 1, 1, 1` arguments.

Steps to Reproduce:
- install something using win.rect, e.g. https://github.com/wizonesolutions/talon_community/blob/feature-window-management/misc/window_management.py
- if using that script, then say `screen full`

Expected Results:
- window is maximized

Actual Results:
- window may slowly animate and partially resize, but does not maximize. repeating the command several times eventually maximizes it.

Version/Build:
v0.0.8.24

Configuration:
https://github.com/wizonesolutions/talon_community/blob/feature-window-management/misc/window_management.py

Dragon 6.0.8

**Comment by lunixbochs** [comment]
should be fixed in 0.0.8.25
