### ISSUE TITLE
 Broken gray calibration screen when tryin: to calibrate without an eye tracker

### ISSUE THREAD

**Issue by nickvisut** [talonvoice/talon#81]
When an eye tracker is not connected (either because a user doesn't have one, or there's something wrong with the connection), attempting to run a calibration fails by showing the grey overlay without any calibration circles. Furthermore, pressing escape to dismiss the overlay doesn't work, although restarting Talon does (possible if you have a secondary screen, not sure if only one screen since everything is obscured by the overlay).
![screen shot 2019-02-01 at 6 16 17 pm](https://user-images.githubusercontent.com/2823112/52158495-b99e3000-264d-11e9-8ca8-871afda8bf43.png)

**Comment by lunixbochs** [comment]
Fixed in the next beta in a couple of different ways.
