### ISSUE TITLE
Provide a supported workflow without runtime draconity injection

### ISSUE THREAD

**Issue by anonfunc** [talonvoice/talon#84]
Context is 2019 Feb 17 discussion.
Some AV sees the dynamic injection of shared libraries to be a sign of malware, so the current workflow is:

- Edit `/Applications/Talon.app/Contents/Resources/talon_plugins/speech.py`, make `inject_draconity()` a no-op
- Download `Dragon-launcher` to `/Applications/Dragon.app/Contents/MacOS`
- Run Dragon-launcher instead of Dragon.

Dragon-launcher is available from @lunixbochs (aegis in Slack).

Things discussed:
- Talon setting to control injecting draconity
- Separate Dragon-Loader.app bundle
- Talon launching Dragon with appropriate hooks.

**Comment by anonfunc** [comment]
Note that scripting this has ramifications for Mojave's microphone access settings.  Wrapping the script in an Automater application allows Dragon to prompt for microphone access, an Alfred workflow did not.

**Comment by lunixbochs** [comment]
Are you still using Dragon-launcher?

**Comment by lunixbochs** [comment]
If anyone runs into this again, I still have the ability to send them Dragon-launcher, for everyone else there's wav2letter.
