### ISSUE TITLE
talon does not start on login

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#85]
i have the checkbox checked, yet it still does not start on login.

**Comment by lunixbochs** [comment]
Apparently this happens if you move the app after registering for start on login, perhaps I can detect an app move and uncheck the box. In theory, if you run into this, you moved the app and should uncheck/recheck the box.

**Comment by lunixbochs** [comment]
as of the next talon beta, the box will uncheck itself if you move the app, which should fix any confusion around this
