### ISSUE TITLE
talon does not notice files inside folders moved into the user directory

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#86]

**Comment by lunixbochs** [comment]
is this only when they're inside a directory that's moved?

**Comment by dwiel** [comment]
More specifically what I tried was moving a talon community directory into
the user directory and nothing was noticed. It's possible that moving files
one at a time is ok, i haven't tried.

**Comment by lunixbochs** [comment]
that was the problem, moving directories in/out/renaming them is fixed in the newapi branch
