### ISSUE TITLE
Game controller API for Talon

### ISSUE THREAD

**Issue by christianhultin** [talonvoice/talon#89]
Being able to map gam controller actions to keyboard strokes, mouse movements or even more advanced actions such as applescripts. This would be very useful e.g. in a scenario where the user is unable to use the mouse, but can instead use two analogue sticks for mouse movement (one fast and one slow for precision) and buttons for clicks of different kinds.

**Comment by lunixbochs** [comment]
just implemented in the rust beta, see #vip for information

**Comment by christianhultin** [comment]
Great!
