### ISSUE TITLE
`crew plus` - how to examine the grammar for simple rules?

### ISSUE THREAD

**Issue by tuomassalo** [talonvoice/talon#9]
How to make `crew <foo>`/`trail <foo>` commands (find next/prev <foo> in buffer) work for symbols? At the moment my Atom implementation (https://github.com/tuomassalo/atom-talon) searches for the string 'plus' if I say `crew plus`. (Of course, it might even be the desired thing sometimes.)

Maybe I could go through the active grammar somehow and find all the simple 'word -> symbol(s)' rules, then change `crew plus` to `crew +`? Any pointers?

A bit surprisingly, VoiceCode does find the next plus sign with `crew plus`. I've actually found it to be very handy, that's why I think it should also work here.

**Comment by lunixbochs** [comment]
You would use a word mapping or replacement scheme for this, where dictating `plus` would output `+` instead. The different script sets have a different way of doing this.
