### ISSUE TITLE
Calibration of eyetracker removes dimming of eyetacker lights

### ISSUE THREAD

**Issue by christianhultin** [talonvoice/talon#92]
Te eyetracker is currently set to dil the lights when ”control mouse”-mode is not active, this feature works as expected. However after calibration of the eyetracker, turning of ”control-mouse”-mode does not dim the eyetrackers lights anymore. Restarting Talon will solve the issue and enable automatic dimming once again

**Comment by lunixbochs** [comment]
Can anyone confirm if this is still an issue in the beta?

**Comment by lunixbochs** [comment]
I'm closing as talon has changed a lot since then and I can't repro, please reopen if it's still an issue for you
