### ISSUE TITLE
Conflicts with some Talon letters

### ISSUE THREAD

**Issue by JSenecal2** [talonvoice/talon#93]
I've seen a few conflicts between Talon letters and other commands, which causes recognition errors. While I can fix these for myself by using nonstandard letters, I asked that these conflicts be considered the next time the Talon alphabet is updated:

cap is a frequently used command in Dragon mode. This is especially problematic if both Talon and Dragon are active at the same time. I think Cap should mean the same thing in both Talon and Dragon (capitalize the next word) to make it easier for those who use both modes.

fine versus find is easily misrecognized. Find is a frequent command for cmd-F, though I only see it in the Finder context in the common scripts.

command odd is often misrecognized as command dot. While not a problem for spelling, this does make it hard to type cmd-o by voice.

whale can be misrecognized as 12 by those who have the teens active as numbers.

**Comment by lunixbochs** [comment]
I don't agree with talon and dragon being active at the same time, if I'm designing toward a dictation+command fused mode it will be running entirely in talon, so I'm not super keen to design around dragon's quirks when used that way

I've gotten feedback on fine/odd, I'm open to suggestions

Would you be ok with a more complex number recognizer that is prefixed if you want more than just digits? like `numb 12` instead of `12`. I want to make arbitrary number capture a thing, like `one million one hundred thousand and twelve`, so I'd rather design toward that than patch the whale/12 collision directly

**Comment by JSenecal2** [comment]
I will sometimes try activating both Talon and Dragon at the same time to play around and see how it works, but if I’m trying to get something done I'll use one or the other. Now that you fixed the bug that Dragon had typing into many applications, I’m using Dragon mode more when dictating pure English so that I can use the correction facility again (a feature I missed greatly). 

My problem with cap as a letter is that I’m used to that meaning “capitalize the next word” from my many years of using un-enhanced Dragon. I think it would be better to use cap instead of champ as the default formatter for capitalizing the next letter, and use some other character for the letter C (I’ve made this change in my personal scripts).

Currently I need to use the tens and teens to type the year. If I say 2 0 1 9 rapidly, I get nothing. But if I say 20 19, the digits appear normally. As I remember, this is a known issue. This is simply my work around, which is actually more convenient. 

Having a separate command to type numbers is fine. I suggest allowing numeral as an alias for this command so that the same command will work in both Dragon and Talon modes.

**Comment by lunixbochs** [comment]
I think the number situation is much better these days, is there still an issue worth solving in the short term here?

**Comment by lunixbochs** [comment]
I'm going to close this, command specific issues should be posted on whatever repo is defining the commands
