### ISSUE TITLE
feature request: webview visible in all spaces

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#95]
Right now, webviews are only visible on the space they were last shown on. It would be nice if there is an option to make webviews visible in all spaces. This would be helpful for making a history webview which always shows the most recently spoken phrases, no matter what space is currently visible.

**Comment by lunixbochs** [comment]
I think imgui in the beta can do this. Webviews are deprecated because they would be too much of a pain to support on multiple platforms, and they're buggy as is on Mac.
