### ISSUE TITLE
win.visible_rect doesn't seem correct

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#98]
The following code results in the following logs:
```
    win = ui.active_window()
    print("win.screen", win.screen)
    print("ui.screens()", ui.screens())
    print("win.screen.visible_rect", win.screen.visible_rect)
```

```
2019-06-20 10:43:43    IO win.screen Screen(x=-3840.0, y=0.0, size=(3840.0, 2160.0), mm=(1354.6666463216147, 761.9999885559082))
2019-06-20 10:43:43    IO ui.screens() (Screen(x=0.0, y=0.0, size=(2560.0, 1440.0), mm=(596.5504497563073, 335.5596279879229)), Screen(x=2560.0, y=0.0, size=(1680.0, 1050.0), mm=(286.38925744383124, 178.99328590239455)), Screen(x=-3840.0, y=0.0, size=(3840.0, 2160.0), mm=(1354.6666463216147, 761.9999885559082)))
2019-06-20 10:43:43    IO win.screen.visible_rect Rect(-3840.0, 0.0, 960, 2160)
```

In the last log line, you can see the `visible_rect` has width 960, even though the screen itself has width 3840. Perhaps my understanding of what `visible` means in this context is incorrect?

**Comment by lunixbochs** [comment]
This is how I'm getting `visible_rect`:

```
#import <AppKit/AppKit.h>

int main() {
    for (id screen in [NSScreen screens]) {
        NSLog(@"\nscreen: %@\nframe: %@\nvisibleFrame: %@\n\n", screen, NSStringFromRect([screen frame]), NSStringFromRect([screen visibleFrame]));
    }
}
```

Run with `gcc screens.m -framework AppKit && ./a.out`

Looks fine on my machine. Are you sure you didn't accidentally mutate screen.visible_rect?

```
>>> ui.screens()[0].visible_rect
Rect(0.0, 23.0, 2304.0, 1273.0)
>>> ui.screens()[0].visible_rect.x = 1000
>>> ui.screens()[0].visible_rect
Rect(1000, 23.0, 2304.0, 1273.0)
```

I could add support for "frozen" rects to make that less likely

**Comment by dwiel** [comment]
Looks like that is exactly what happened. Instead of returning an immutable object, maybe just return a copy so mutations dont affect future uses?

**Comment by lunixbochs** [comment]
Ok, just made Screen.rect / visible_rect read-only properties that return a copy of the rect, so they will behave more like Window in that respect now (sans the setter)

**Comment by dwiel** [comment]
Nice
