### ISSUE TITLE
feature request: setter for `ui.Rect.left`

### ISSUE THREAD

**Issue by dwiel** [talonvoice/talon#99]
Currently, ui.Rect.left only has a getter. It would be convenient if it also had a setter.

**Comment by lunixbochs** [comment]
Added setters for left/right/top/bot/center in newapi, untested

**Comment by lunixbochs** [comment]
I'm actually a little conflicted about this. left is more ambiguous than X, because left could either set X, or set X *and* stretch the width so `right` isn't modified. I've implemented the latter.

**Comment by dwiel** [comment]
Makes sense
